### ISSUE TITLE
How to fill JSON array one by one?

### ISSUE THREAD

**Issue by djdance** [SwiftyJSON/SwiftyJSON#1003]
I try to add new items to empty JSON array. But it is always empty. Why? Correct me please. 

```

            var refs:JSON = []  //or refs = JSON([])

            for i in 0..<5 {

                refs[refs.count].string = "test\(i)"

            }

            print("refs=\(refs)")  //always print refs=[]
```

I already asked this [here](https://github.com/SwiftyJSON/SwiftyJSON/issues/782), but nothing changed since that time. Or I don't understand what's wrong.

**Comment by svallex** [comment]
Subscript lets only update existing values but doesn't let append new values (**if self.rawArray.indices.contains(index)**):
```swift
fileprivate subscript(index index: Int) -> JSON {
        ...
        set {
            if self.type == .array &&
                self.rawArray.indices.contains(index) &&
                newValue.error == nil {
                self.rawArray[index] = newValue.object
            }
        }
}
```
So you can use "merged" instead, for example:
```swift
for i in 0..<5 {
    refs = try! refs.merged(with: ["test\(i)"])
}
```
