### ISSUE TITLE
Why can't we parse a rawString back to json object?

### ISSUE THREAD

**Issue by artworkad** [SwiftyJSON/SwiftyJSON#101]
```
var obj = JSON("...")
var str = obj.rawString()
var anotherObj = JSON(str)
```

this does not work. Why?

**Comment by yungfu** [comment]
I got the same issue with version 1.3.1
var obj = JSON("...")
var str = obj.rawString()
var anotherObj = JSON(str)
I cannot fetch any property of "anotherObj". Yes, rawData() can work here, but I really need store the string value, why it cannot unserialize the rawString

**Comment by peterjuras** [comment]
I had the same issue. I get it working by using JSON.parse(myString) instead:

**Comment by korgx9** [comment]
How to remove white spaces and newlines with rawString()?

**Comment by zizhengwu** [comment]
I came across the same issue and wasted a lot of time here. The solution provided by @peterjuras finally solve my problem. This is definitely an awful bug.

**Comment by tommc1985** [comment]
I've had the same issue, have been doubting myself for days. Thank you @peterjuras, you're solution worked.

**Comment by pawangiri** [comment]
I feel the above solution should be part of the official document. @peterjuras Thanks for sharing.

**Comment by r-a-o** [comment]
Parse is deprecated, use `JSON.init(parseJSON:  "your string")`

**Comment by leochoo** [comment]
> `JSON.parse` is deprecated, use `JSON.init(parseJSON: "your json string")`

Where did you find this info??

**Comment by r-a-o** [comment]
@leochoo A quick search through the `SwiftyJSON.swift` source file looking for `init()` methods. 

https://github.com/SwiftyJSON/SwiftyJSON/blob/184c6884998c41f71a73c459f9b525b7121be846/Source/SwiftyJSON.swift#L125
