### ISSUE TITLE
Swift 5 support for Carthage

### ISSUE THREAD

**Issue by lemonkey** [SwiftyJSON/SwiftyJSON#1012]
### What did you do?

Tried to compile under Xcode 10.2.

### What did you expect to happen?

My app compiling successfully.

### What actually happened instead?

Build failed due to module being built with Swift 4.2 compiler while app was being built using Swift 5 under Xcode 10.2. **Swift 5 is ABI stable, but it isn't module stable yet.**

### Environment

List the software versions you're using:

 - SwiftyJSON: 4.2.0
 - Xcode Version: 10.2
 - Swift Version:  Xcode Default (5.0)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Carthage: 0.32.0
 - Swift Package Manager: Apple Swift Package Manager - Swift 5.0.0 (swiftpm-14490.60.2)

**Comment by LordMorty** [comment]
I filed a [Pull Request](https://github.com/SwiftyJSON/SwiftyJSON/pull/1013) Fixing the issue for my case (which doesn't involve Carthage). Feel free to review!

**Comment by muzoman** [comment]
If set the SWIFT_VERSION for this this module to 4.2 then it compiles fine.

**Comment by wongzigii** [comment]
https://github.com/SwiftyJSON/SwiftyJSON/releases/tag/4.3.0
You can use 4.3.0 version by Carthage now.

**Comment by lemonkey** [comment]
Thanks!

**Comment by ovyhlidal** [comment]
Is this available also for Cocoapods? Thanks
