### ISSUE TITLE
Build error with Carthage.

### ISSUE THREAD

**Issue by OleksandrKatrynets** [SwiftyJSON/SwiftyJSON#1020]
### What did you do?

Today morning I just tried to build my project and got this:
```
*** Fetching SwiftyJSON
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/SwiftyJSON/SwiftyJSON.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/.../Library/Caches/org.carthage.CarthageKit/dependencies/SwiftyJSON)) failed with exit code 1
Command PhaseScriptExecution failed with a nonzero exit code
```

### What did you expect to happen?

Build should be succeeded

### What actually happened instead?

Build failed

### Environment

 - Carthage `github "SwiftyJSON/SwiftyJSON" ~> 4.0`
 - Xcode Version: 10.2 (10E125)
 - Swift Version: 5.0

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Carthage: 0.32.0

**Comment by wongzigii** [comment]
You should switch to 4.3.0 version

**Comment by OleksandrKatrynets** [comment]
@wongzigii 
I changed version to this: `"SwiftyJSON/SwiftyJSON" ~> 4.3`
And while `carthage update` I got this error:
```
*** Fetching SwiftyJSON
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/SwiftyJSON/SwiftyJSON.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/itkerry/Library/Caches/org.carthage.CarthageKit/dependencies/SwiftyJSON)) failed with exit code 1
```
