### ISSUE TITLE
Built error  SWIFT_VERSION '5.0' is unsupported, 

### ISSUE THREAD

**Issue by hawkeye1981** [SwiftyJSON/SwiftyJSON#1028]
### What did you do?

Trying to build an app using SwiftyJSON 5.0.0 but working in swift 4.2

### What actually happened instead?

Build Error: error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'SwiftyJSON')
### Environment

List the software versions you're using:

 - SwiftyJSON: 5.0.0
 - Xcode Version: Version 10.1 (10B61)
 - Swift Version:  Xcode.default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.6.1
 - Swift Package Manager  Swift 4.2.0 (swiftpm-14460.2)

**Comment by macfanatic** [comment]
I had this issue on SwiftyJSON 4.3, Xcode 10.1 and Swift 4.2

Downgrading to SwiftyJSON 4.2 fixed the issue.
