### ISSUE TITLE
Xcode Generates 100 errors when archiving app with SwiftyJSON

### ISSUE THREAD

**Issue by MichaelJBerk** [SwiftyJSON/SwiftyJSON#1035]
I have an app that I am working on updating for iOS 13 that uses SwiftyJSON
Under Xcode 11 Beta 4, when I try to archive the app, Xcode gives me 100 errors, all starting with "Undefined Symbol: method descriptor"... The issue seems to be with SwiftyJSON, as the complier can't get past it.

 - SwiftyJSON: *5.0.0*
 - Xcode Version: *11.0 (11M374r)* 
 - Swift Version: *Xcode Default*
 - Cocoapods: *1.7.4* (Use `pod --version` in Terminal)

**Comment by MichaelJBerk** [comment]
I ended up switching from using Cocoapods to using the Swift Package Manager, and now it works

**Comment by spaquet** [comment]
This is an auto link failure

```
ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use auto-linked library 'swiftMetal'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftUIKit'
ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
ld: warning: Could not find or use auto-linked library 'swiftDispatch'
ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find or use auto-linked library 'swiftCore'
```

Previous versions of Xcode 11 were not affected.

**Comment by MichaelJBerk** [comment]
Looking through the Beta 4 release notes, they do indeed mention this issue:

> Targets that contain Swift code with the Enable Bitcode build setting set to Yes fail to link correctly when built with the Archive action. (52804818)

Thankfully, there's also an official workaround:

> Workaround: Add a custom build setting with the name LD_VERIFY_BITCODE, and set it to NO. Make a note to yourself to delete this custom build setting once this issue is resolved.

source: https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_4_release_notes

**Comment by spaquet** [comment]
@MichaelJBerk thx
