### ISSUE TITLE
Xcode 12.0 Deployment target warning

### ISSUE THREAD

**Issue by marcheimendinger** [SwiftyJSON/SwiftyJSON#1071]
### What actually happened?

Starting with Xcode 12.0, I get a deployment target warning: `The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99`.

### Environment

 - SwiftyJSON: *5.0.0*
 - Xcode Version: *12.0 (12A7209)*
 - Swift Package Manager *5.3.0*

**Comment by ritteraf** [comment]
https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/

**Comment by telipskiy** [comment]
@ritteraf it's a fast and easy fix if you use Cocoapods, but I have no idea how to disable this warning in Swift Package Manager

**Comment by Isvvc** [comment]
Other projects I've seen have simply been removing the `platforms` section of `Package.swift` to silence warnings. Not entirely sure the other implications of doing that though.

**Comment by minestarnl** [comment]
Maybe a version should be kept at this `Package.swift` and a newer version should be released that supports iOS 9 and upwards?

**Comment by dch09** [comment]
Anyone figured it out already?

**Comment by chessboy** [comment]
Any movement on this? SwiftyJSON is the **best**, but a warning showing in Xcode when I demo is the worst :( Thanks for any updates.

**Comment by chessboy** [comment]
> https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/

Yes, there's workaround for CocoaPods, but this issue is  specifically for use with SPM.

**Comment by markuspersson** [comment]
Also using SwiftyJSON with SPM and get the same warning. Any news on this?

**Comment by wongzigii** [comment]
Updated for Xcode 12.0
