### ISSUE TITLE
With Xcode 12 not working

### ISSUE THREAD

**Issue by bhaveshCog0919** [SwiftyJSON/SwiftyJSON#1079]
build successfully but error showing info.plist not found.

**Comment by gitpushdev** [comment]
Had the same issue, upgraded cocoapods, clean project, clean Derived data and worked again

**Comment by wongzigii** [comment]
https://khushwanttanwar.medium.com/xcode-12-compilation-errors-while-running-with-ios-14-simulators-5731c91326e9

checkout this post @bhaveshCog0919 @gitpushdev
