### ISSUE TITLE
Remove key

### ISSUE THREAD

**Issue by mistralaix** [SwiftyJSON/SwiftyJSON#1080]
### Question:

Hi I would like to know if it's possible to remove a key from the JSON object ?
I saw this issue (https://github.com/SwiftyJSON/SwiftyJSON/issues/475) but no one answered.

Is there a way to make a custom one ?

### Example:
```
{
  foo: {
    a: "bar", 
    b: ["1", 2, {trois: 3}]
  }
}
```
json["foo"]["b"][0] = nil

```
{
  foo: {
    a: "bar", 
    b: [2, {trois: 3}]
  }
}
```

json["foo"]["b"] = nil

```
{
  foo: {
    a: "bar"
  }
}
```

Thank you for your help!

**Comment by kbirand** [comment]
did you get a solution
