### ISSUE TITLE
根据4.0的博客中写道，领域能力推荐使用包：ability，这个包下包括领域能力和DomainService。但是我点比较困惑，一般领域服务可能是以接口的形式存在，如果我拉包名叫ability或者domainservice的话，那我服务服务接口的实现应该放在哪里比较合适，是在ability再建一个子包，叫ability.impl吗？.

### ISSUE THREAD

**Issue by Vietthang91** [SwiftyJSON/SwiftyJSON#1099]
根据4.0的博客中写道，领域能力推荐使用包：ability，这个包下包括领域能力和DomainService。但是我点比较困惑，一般领域服务可能是以接口的形式存在，如果我拉包名叫ability或者domainservice的话，那我服务服务接口的实现应该放在哪里比较合适，是在ability再建一个子包，叫ability.impl吗？

__Originally posted by @cy503328434 in https://github.com/alibaba/COLA/issues/180__

**Comment by wongzigii** [comment]
Closing for off topic.
