### ISSUE TITLE
It seems not easy to manipulate an array or dictionary?

### ISSUE THREAD

**Issue by phu4ku** [SwiftyJSON/SwiftyJSON#110]
for example, delete one item, append one item. the setter can change the whole array or dictionary. but how can i just manipulate an array or dictionary?

**Comment by ArtSabintsev** [comment]
Having the exact same issue.

**Comment by ArtSabintsev** [comment]
Figured it out! On your returned JSOn object, just call the optional vars `.array` or `.dictionary`. 

If your object is an array and you rightfully call `.array`, then you can use all the .array` methods, like append. If it happens to not be an array, `nil` is returned.

```swift
let json = JSON(data: data)
let array = json.array // Returns an [AnyObject]?, which means you'll get an [AnyObject] or nil
```

**Comment by ArtworkAD** [comment]
@ArtSabintsev but array is immutable, you cannot append to it

**Comment by ArtSabintsev** [comment]
Then you can make a new immutable array and populate it with the data in the immutable array.

**Comment by alexhunsley** [comment]
I'm having the same problem. I just cannot get the JSON to update.
```
                   let wholeJSON: JSON = .... // my json tree
                   let someObject: JSON = ... // some object from inside wholeJSON

                    guard var myDict = someObject.dictionary else {
                        fatalError("Didn't find dict")
                    }

                    // modify the dict
                   myDict["a"] = "b"

                   // is this necessary? But even with this line below, still don't
                   // get the json updated
                   someObject.dictionary = myDict

                   // the call below doesn't show any of my changes in the data
                   wholeJSON.rawData()
```
