### ISSUE TITLE
Warning that in Swift 6 will be an error

### ISSUE THREAD

**Issue by faabaliamacias** [SwiftyJSON/SwiftyJSON#1122]
### What did you do?

See a warning in the code: Type 'Any' is not optional, value can never be nil; this is an error in Swift 6

It happens in public var object: Any { 
...

![image](https://user-images.githubusercontent.com/30280368/184070713-67a8996e-cf08-41f0-94cb-93744b937df6.png)
### What did you expect to happen?

With correction not show the warning

### What actually happened instead?

It shows the warning Type 'Any' is not optional, value can never be nil; this is an error in Swift 6

### Environment

List the software versions you're using:

 - SwiftyJSON: *5.0.1*
 - Xcode Version: *14 beta 5 (14A5294e)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *Xcode Default* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.13.1* (Use `pod --version` in Terminal)

**Comment by HangyuYe** [comment]
With same warning

**Comment by smixik** [comment]
Same here

**Comment by gongzhang** [comment]
Same here. I think we can just delete this case, right?

**Comment by owenDecorus** [comment]
> "Swift 6" on warning? The latest version is 5.7 🤥 https://www.swift.org/download/

No lying going on here. What this error means is that the issue will become a build error, and not just a warning, when we inevitably get Swift 6. 

To add to the issue, I am seeing this as well. It's not really an issue right now obviously as everything is still working fine but, for whatever reason, we won't be able to build in Swift 6 because of this.

**Comment by gongzhang** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/4470629/195330322-314b4293-37bc-4f2d-8a35-0ecd1b1139fa.png">

Swift 5.7 does allow `Any` value to store a wildcard `nil`. Therefore the `case nil` is already useless in Swift 5.7. I think wrap the case in `#if swift(<5.7)` is a solution.

**Comment by luoxiu** [comment]
Actually,  it allows:

```swift
let n: Int? = nil
let x: Any = n as Any
```

> <img alt="image" width="563" src="https://user-images.githubusercontent.com/4470629/195330322-314b4293-37bc-4f2d-8a35-0ecd1b1139fa.png">
> 
> Swift 5.7 does allow `Any` value to store a wildcard `nil`. Therefore the `case nil` is already useless in Swift 5.7. I think wrap the case in `#if swift(<5.7)` is a solution.

**Comment by gongzhang** [comment]
Indeed you can assign `nil` to `Any`, sorry I was wrong.

👍 After further research, even if `nil` is assigned explicitly, it is not equal to a _naked_ `nil`. (Because the value is `Optional<Int>.none`)

```swift
let a: Int? = nil
let b: Any = a as Any

if case nil = b { // false
    // ❌ never
}

if case Optional<Int>.none = b { // true
    // ✅ matched
}

```

> Actually, it allows:
> 
> ```swift
> let n: Int? = nil
> let x: Any = n as Any
> ```
> 
>  > <img alt="image" width="563" src="https://user-images.githubusercontent.com/4470629/195330322-314b4293-37bc-4f2d-8a35-0ecd1b1139fa.png">
> > Swift 5.7 does allow `Any` value to store a wildcard `nil`. Therefore the `case nil` is already useless in Swift 5.7. I think wrap the case in `#if swift(<5.7)` is a solution.

**Comment by luoxiu** [comment]
Changing `case nil:` to ` case Optional<Any>.none:` will fix this issue, already raised a pr here: https://github.com/SwiftyJSON/SwiftyJSON/pull/1124.

**Comment by gongzhang** [comment]
@luoxiu 🤔 Is it really possible to get into the branch of `Optional<Any>.none`? I still feel that `case nil` should be removed directly.

**Comment by luoxiu** [comment]
> @luoxiu 🤔 Is it really possible to get into the branch of `Optional<Any>.none`? I still feel that `case nil` should be removed directly.

Yes, take a look at the test I added to pr.

**Comment by gongzhang** [comment]
@luoxiu hmmm... looks good to me

**Comment by HangyuYe** [comment]
We need to wait for a new swift package to fix the issue, or is there some workaround to skip this warning on the current swift pak.
