### ISSUE TITLE
Type 'Any' is not optional, value can never be nil; this is an error in Swift 6

### ISSUE THREAD

**Issue by tejasfarera** [SwiftyJSON/SwiftyJSON#1125]
Property `object` giving warning which will be causing compilation error in swift version 6.
![Screenshot 2022-11-16 at 3 18 12 PM](https://user-images.githubusercontent.com/35726411/202146981-3027c2fc-10ae-469c-9985-6c5f20dc269e.png)

**Comment by pthexton** [comment]
@tejasfarera this looks to be fixed already in main

https://github.com/SwiftyJSON/SwiftyJSON/commit/764c0c8b944574cd63592a452c23865f54b66d0d

**Comment by tejasfarera** [comment]
It is fixed as seen in [764c0c8](https://github.com/SwiftyJSON/SwiftyJSON/commit/764c0c8b944574cd63592a452c23865f54b66d0d) and will be available in the future version, so closing the issue for now.
