### ISSUE TITLE
New version release - When?

### ISSUE THREAD

**Issue by Zandor300** [SwiftyJSON/SwiftyJSON#1133]
When will the latest version on the `master` branch be pushed as an update to the package managers?

I am using Cocoapods.

**Comment by gongzhang** [comment]
Same question here 🙋 And is this project dead?

**Comment by tsfischer** [comment]
Also interested in the health of this project. One of the products I develop relies heavily on SwiftyJSON, passing around the `JSON` object as a native object in many cases. At the time the code was written, SwiftyJSON was hugely adopted by the community and the risk of doing this seemed minimal, but with native OS support now it seems this library has languished.

**Comment by gongzhang** [comment]
https://github.com/SwiftyJSON/SwiftyJSON/issues/1090

**Comment by gongzhang** [comment]
@tsfischer 😭Exactly. At least we have 3.4k forks. Any idea about how to find a good fork?

**Comment by Ariandr** [comment]
Hi @LukeTangPL @wongzigii @lingoer

Can anyone of you maintain the project? Or if you cannot spend much time on the project, at least approve PRs and release new Cocoapods versions?

This project is super useful for me and many others, I appreciate your work a lot. It would be great to at least maintain it on the basic level, so there are no build errors.

**Comment by purifier1990** [comment]
> @tsfischer 😭Exactly. At least we have 3.4k forks. Any idea about how to find a good fork?

Yeah, I've also just forked one to address my build issue, I don't know if there is a good fork to migrate, but I'm ok to take over the project for maintain, can't get approve from original author though, maybe just fork from your side and do it on your own...

**Comment by lockieluke** [comment]
is there a good fork?

**Comment by tsfischer** [comment]
We are just finishing up a big project to remove SwiftyJSON from our projects. Good riddance.

**Comment by Ariandr** [comment]
The new version has been released guys, so you can close the issue.

**Comment by wongzigii** [comment]
https://github.com/CocoaPods/Specs/blob/master/Specs/b/e/4/SwiftyJSON/5.0.2
