### ISSUE TITLE
Privacy manifest required by Apple

### ISSUE THREAD

**Issue by infinitepower18** [SwiftyJSON/SwiftyJSON#1143]
Any plans to add a privacy manifest? Apple has explicitly mentioned SwiftyJSON as one of the third party SDKs that must include a privacy manifest.

https://developer.apple.com/support/third-party-SDK-requirements

**Comment by angelmic** [comment]
+1

**Comment by JLLA113** [comment]
+2

**Comment by rick711003** [comment]
+1

**Comment by linhaosunny** [comment]
@wongzigii Any Plan support it for cocoapods?

**Comment by Nathan-Molby** [comment]
https://github.com/SwiftyJSON/SwiftyJSON/issues/1145#issuecomment-2007709500

**Comment by linhaosunny** [comment]
> [#1145 (comment)](https://github.com/SwiftyJSON/SwiftyJSON/issues/1145#issuecomment-2007709500)

@Nathan-Molby i use a [script tool](https://github.com/Wooder/ios_17_required_reason_api_scanner) to scan didn't find any usage of apple's privacy APIs , maybe it no need to add empty PrivacyInfo.xcprivacy in those framework.

**Comment by wongzigii** [comment]
Closing with https://github.com/SwiftyJSON/SwiftyJSON/pull/1150
