### ISSUE TITLE
Is this repository no longer maintained? why？

### ISSUE THREAD

**Issue by platojobs** [SwiftyJSON/SwiftyJSON#1146]
Please renew it, God！

**Comment by derwaldgeist** [comment]
Wondering the same. Last update 2 years ago, and a lot of open issues. I'd love to use this library, but am unsure if it's a good idea?

**Comment by woxihejinghao** [comment]
use codebale

**Comment by Ariandr** [comment]
It is maintained, there is a new release, you can close the issue.

**Comment by derwaldgeist** [comment]
Awesome to hear it!
