### ISSUE TITLE
PrivacyInfo file

### ISSUE THREAD

**Issue by supergithuber** [SwiftyJSON/SwiftyJSON#1153]
I use pod to import SwiftyJSON

If I use "pod 'SwiftyJSON', '5.0.1'", I will get podspec from 'https://github.com/CocoaPods/Specs/blob/master/Specs/b/e/4/SwiftyJSON/5.0.1/SwiftyJSON.podspec.json' which doesn't contain PrivacyInfo.xcprivacy file 

If I use "pod 'SwiftyJSON', :git=>"https://github.com/SwiftyJSON/SwiftyJSON"" to import SwiftyJSON, which is not a stable version.

Cound you please publish a new version or tag to pod center reop?  Thx

**Comment by wongzigii** [comment]
Use the latest 5.0.2
