### ISSUE TITLE
Update to 5.0.2 with cocoapods

### ISSUE THREAD

**Issue by simvi** [SwiftyJSON/SwiftyJSON#1154]
Hello, I've tried to update the lib with Cocoapods, the latest available version is 5.0.1, but there is a 5.0.2 available:

When I tried to fix this version I have an error:
 I have an error:
`[!] CocoaPods could not find compatible versions for pod "SwiftyJSON":
  In Podfile:
    SwiftyJSON (= 5.0.2)
`

But It works when I specify the commit: 
`pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON/', :commit => 'af76cf3ef710b6ca5f8c05f3a31307d44a3c5828'`

Can you set this new version available with cocoapods ?
Thanks a lot !

 - SwiftyJSON:  5.0.1
 - Xcode Version: 15.3
 - Swift Version: 5
 - Cocoapods: 1.15.2

**Comment by luoxiankang2** [comment]
I updated CocoaPod to do a pod search and could only find version 5.0.1

**Comment by SunZhiC** [comment]
Please publish pod 5.0.2 @wongzigii

**Comment by simvi** [comment]
In the meantime you can specify the commit in the podfile: 
`  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON/', :commit => 'af76cf3ef710b6ca5f8c05f3a31307d44a3c5828'
`

**Comment by Igor-Poltavtsev** [comment]
hey, any updates?

**Comment by lixiang1994** [comment]
I updated CocoaPod to do a pod search and could only find version 5.0.1

**Comment by Vyazovoy** [comment]
@wongzigii, thanks for publishing it but I think you've published a bit different version of the podspec. Please take a look at [these lines](https://github.com/CocoaPods/Specs/blob/master/Specs/b/e/4/SwiftyJSON/5.0.2/SwiftyJSON.podspec.json#L31-L36). Original podspec does not contain them. It causes build failures and there is no reason to exclude the arch. Could you please republish?

**Comment by wongzigii** [comment]
Republished. Done

**Comment by Shannon-Yang** [comment]
@wongzigii Yes, version 5.0.2 works very well👍, thank you
