### ISSUE TITLE
Private library that relies on SwiftyJSON, pod lib lint cannot pass

### ISSUE THREAD

**Issue by Shannon-Yang** [SwiftyJSON/SwiftyJSON#1155]
My private library depends on SwiftyJSON. When I execute 
```ruyb
pod lib lint --verbose --skip-import-validation --allow-warnings SYMoyaNetwork.podspec
```
I get the following error

### What actually happened instead?

- NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  note: Building targets in dependency order
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork] xcodebuild:  note: Target dependency graph (5 targets)
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'SwiftyJSON' from project 'Pods')
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'Alamofire' from project 'Pods')
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'Moya' from project 'Pods')
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'SYMoyaNetwork' from project 'Pods')
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'Alamofire' from project 'Pods')
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'Alamofire-Alamofire' from project 'Pods')
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'SwiftyJSON' from project 'Pods')
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'Moya' from project 'Pods')
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  note: Using codesigning identity override: 
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:92:23: error: 'Data' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:92:12: note: add @available attribute to enclosing initializer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:82:15: note: add @available attribute to enclosing struct
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:201:43: error: 'init(integerLiteral:)' is only available in macOS 10.10 or newer
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:555:130: error: 'Data' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:555:17: note: add @available attribute to enclosing instance method
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:541:1: note: add @available attribute to enclosing extension
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:563:43: error: 'Encoding' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:563:14: note: add @available attribute to enclosing instance method
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:583:49: error: 'Encoding' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:583:19: note: add @available attribute to enclosing instance method
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:868:21: error: 'URL' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:868:16: note: add @available attribute to enclosing property
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:865:1: note: add @available attribute to enclosing extension
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:107:28: error: 'Data' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:107:28: note: add 'if #available' version check
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:105:12: note: add @available attribute to enclosing initializer
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:126:28: error: 'data(using:allowLossyConversion:)' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:126:28: note: add 'if #available' version check
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:125:9: note: add @available attribute to enclosing initializer
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:567:63: error: 'localizedDescription' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:567:63: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:573:48: error: 'Encoding' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:573:48: note: add 'if #available' version check
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:572:14: note: add @available attribute to enclosing instance method
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:573:67: error: 'Encoding' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:573:67: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:578:63: error: 'localizedDescription' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:578:63: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:591:13: error: 'init(data:encoding:)' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:591:13: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:610:44: error: 'replacingOccurrences(of:with:options:range:)' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:610:44: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:610:89: error: 'replacingOccurrences(of:with:options:range:)' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:610:89: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:625:13: error: 'init(data:encoding:)' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:625:13: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:641:50: error: 'replacingOccurrences(of:with:options:range:)' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:641:50: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:641:95: error: 'replacingOccurrences(of:with:options:range:)' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:641:95: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:761:86: error: 'caseInsensitiveCompare' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:761:86: note: add 'if #available' version check
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:756:16: note: add @available attribute to enclosing property
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:740:1: note: add @available attribute to enclosing extension
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:873:30: error: 'range(of:options:range:locale:)' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:873:30: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:874:39: error: 'URL' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:874:39: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:875:58: error: 'addingPercentEncoding(withAllowedCharacters:)' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:875:58: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:875:103: error: 'CharacterSet' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:875:103: note: add 'if #available' version check
    - ERROR | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:877:39: error: 'URL' is only available in macOS 10.10 or newer
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  SwiftyJSON/Source/SwiftyJSON/SwiftyJSON.swift:877:39: note: add 'if #available' version check
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 14.2.99. (in target 'Alamofire-Alamofire' from project 'Pods')
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.9, but the range of supported deployment target versions is 10.13 to 14.2.99. (in target 'SwiftyJSON' from project 'Pods')
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 14.2.99. (in target 'Moya' from project 'Pods')
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 14.2.99. (in target 'Alamofire' from project 'Pods')
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  Pods.xcodeproj: warning: The tvOS Simulator deployment target 'TVOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'Moya' from project 'Pods')
    - NOTE  | [SYMoyaNetwork/SYMoyaNetwork, SYMoyaNetwork/SYMoyaHandyJSON, SYMoyaNetwork/SYMoyaObjectMapper, and more...] xcodebuild:  Pods.xcodeproj: warning: The tvOS Simulator deployment target 'TVOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'Alamofire-Alamofire' from project 'Pods')

### Reason
The reason is probably that s.osx.deployment_target in SwiftyJSON.podspec is set to 10.9 and needs to be modified to 10.10 or above.

### Environment

List the software versions you're using:
 - SwiftyJSON: *5.0.2*
 - Xcode Version: *15.2* 
 - Swift Version: *5.9* 

 - Cocoapods: *1.15.2*

**Comment by Vyazovoy** [comment]
@rock88, I've just posted similar info [here](https://github.com/SwiftyJSON/SwiftyJSON/issues/1154#issuecomment-2050249231). 
As a temporary workaround you can define the dependency as:
```
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :tag => '5.0.2'
```
So that you will have the Apple Privacy Manifest and it will compile normally.

**Comment by rock88** [comment]
@Vyazovoy yes, if you have `Podfile` you can use this approach. But our internal dependencies are hosted in separate repositories and we need to do `pod lib lint` and `pod repo push` to update/publish them.

So we can't use something like:
```ruby
s.dependency 'SwiftyJSON', '~> 5.0.2' # Due to the podspec not compiling on Arm devices
s.dependency 'SwiftyJSON', '~> 5.0.1' # Due to the fact that the `pod lint lint` will use a new version of SwiftyJSON
```

So we can't use another version of SwiftyJSON in Podfile:
```ruby
pod install

[!] CocoaPods could not find compatible versions for pod "SwiftyJSON":
  In Podfile:
    SwiftyJSON (from `https://github.com/SwiftyJSON/SwiftyJSON.git`, tag `5.0.2`)

    InternalLibrary (= 1.0.0) was resolved to 1.0.0, which depends on
      SwiftyJSON (= 5.0.1)
```

It's not a problem at the moment, I can wait for the podspec to be fixed.

**Comment by wongzigii** [comment]
I've republished 5.0.2. No problem.

**Comment by wongzigii** [comment]
https://github.com/CocoaPods/Specs/blob/master/Specs/b/e/4/SwiftyJSON/5.0.2/SwiftyJSON.podspec.json#L32

**Comment by Vyazovoy** [comment]
Thank you, @wongzigii! Now it works as expected 🎉
BTW, #1154 can be closed now.

**Comment by wongzigii** [comment]
@Shannon-Yang Can you confirm the latest 5.0.2 work as expect?

**Comment by Shannon-Yang** [comment]
@wongzigii Yes, version 5.0.2 works very well👍, thank you

**Comment by Jsoncapone** [comment]
Ya sick you ow lol
