### ISSUE TITLE
Swift Optional Values from JSON

### ISSUE THREAD

**Issue by rebump** [SwiftyJSON/SwiftyJSON#116]
Anyone else having a problem with getting the swift optional examples working?  If the "key" doesn't exist in the JSON file, it throws an error instead of returning nil.

If I use an "if let" construct like in the examples it does not work nor does just setting a variable like:

`let test: Float? = item["color","red"].float`

and if "red" does not exist in the JSON file, it throws an "EXC_BAD_INSTRUCTION" error at this line in the dictionary subscript getter in SwiftyJSON:

`if let object_: AnyObject = self.object[key] {`

Full getter below:

```
  private subscript(#key: String) -> JSON {
    get {
      var returnJSON = JSON.nullJSON
      if self.type == .Dictionary {
        if let object_: AnyObject = self.object[key] {
          returnJSON = JSON(object_)
        } else {
          returnJSON._error = NSError(domain: ErrorDomain, code: ErrorNotExist, userInfo: [NSLocalizedDescriptionKey: "Dictionary[\"\(key)\"] does not exist"])
        }
      } else {
        returnJSON._error = self._error ?? NSError(domain: ErrorDomain, code: ErrorWrongType, userInfo: [NSLocalizedDescriptionKey: "Dictionary[\"\(key)\"] failure, It is not a dictionary"])
      }
      return returnJSON
```

The JSON file works with (pulled from a larger JSON file that validates in a validator):

```
          "color": {
            "red": 0.0,
            "green": 0.5,
            "blue": 0.5,
            "alpha": 0.5
          }
```
 but if you remove the "red" entry you get that error with the Optional.

```
          "color": {
            "green": 0.5,
            "blue": 0.5,
            "alpha": 0.5
          }
```

**Comment by schurch** [comment]
I'm seeing this too.

**Comment by skaugust** [comment]
I'm also getting this issue, running XCode 6.1.1. If you run this code on an actual device you'll get a slightly different exception. I think there's a safety check/assert that's failing, because the code is trying to access an object that's already been released. But there shouldn't be any object accessed, because this key is supposed to be missing, right?

**Comment by riveralabs** [comment]
I'm not exactly sure what's happening with that optional value in self.object[key] yet but this seems to fix the issue.

```swift
var tmpObject: AnyObject? = self.object[key] ?? nil
if let object_: AnyObject = tmpObject {
    returnJSON = JSON(object_)
} else {
    returnJSON._error = NSError(domain: ErrorDomain, code: ErrorNotExist, userInfo: [NSLocalizedDescriptionKey: "Dictionary[\"\(key)\"] does not exist"])
}
```

**Comment by dylan** [comment]
+1

**Comment by justinHowlett** [comment]
+1

**Comment by sbarex** [comment]
I found another possible patch for ```private subscript(#key: String) -> JSON``` explicity casting `self.object` as `[String : AnyObject]`:
```swift
            if self.type == .Dictionary {
                if let object_: AnyObject = (self.object as [String : AnyObject])[key] { // <-- casting here
                    returnJSON = JSON(object_)
                } else {
                    returnJSON._error = NSError(domain: ErrorDomain, code: ErrorNotExist, userInfo: [NSLocalizedDescriptionKey: "Dictionary[\"\(key)\"] does not exist"])
                }
            }
```

**Comment by tangplin** [comment]
#200

**Comment by sakthinath** [comment]
Hi,
I am using Swify Json latest update . In this I am facing Swifty Json Unwrapping Optional Issue Please Give any solution for this .**`Swift.ImplicitlyUnwrappedOptional<Swift.String>.some("1")`**
