### ISSUE TITLE
JSON cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by cadrogui** [SwiftyJSON/SwiftyJSON#120]
Hi, im trying to use Swifty in my project and get this error message "JSON cannot be constructed because it has no accessible initializers" in this line:

````
Alamofire.request(.GET, "http://li.homeip.net:8091/query/search/", parameters: ["q": self.queryBox.text])
            
            .responseJSON{ (_, _, responseSphinx, _) in
                
                println(responseSphinx)
                
                let Sphinx = JSON(responseSphinx) // here gives the error
                
        }
````

how can i solve?

to use SwiftyJSON i drag the .xcodeproj to my project navigator, and link the binaries in build phases, an Embebed Frameworks

thanks.

**Comment by deQuelen** [comment]
Hello, I had this problem too, you can simply change 
`let Sphinx = JSON(responseSphinx)`
by
`var Sphinx = SwiftyJSON.JSON(responseSphinx!)`

**Comment by ozcan-durak** [comment]
@cadrogui  If possible can you share how you achieve to work Sphinx search with swift on mobile, I just saw couple of you code and thought you have achieved it. I m a beginner IOS developer and would like to learn but couldnt find any example or demo. Or if possible can you share a demo example on github how to work with sphinx. 

Regards
