### ISSUE TITLE
Get 'command failed due to signal segmentation fault 11' when I use JSON as parameter type

### ISSUE THREAD

**Issue by JakeLin** [SwiftyJSON/SwiftyJSON#125]
I just create a simple function like this  `func foo(j:JSON) { }`

When Xcode 6.2 compiler throws out error 'command failed due to signal segmentation fault 11' . But if I remove it, it compiles properly.

Thanks
Jake

**Comment by lucasderraugh** [comment]
I've run into this same issue. Love to know if you found any solution.

**Comment by JakeLin** [comment]
No, I haven't.I wanted all the logic stay in my Framework target before.
But I have to move those logic from my Framework to the app. Here is my
repo.
https://github.com/JakeLin/SwiftWeather/blob/master/Swift%20Weather/ViewController.swift#L66

Please let me know if you find any.

Thanks
Jake

**Comment by christiansheehan** [comment]
I’m also seeing this. Would be great to have fixed!

**Comment by derrek** [comment]
:+1:  same problem here :-(

**Comment by litan1106** [comment]
same problem here with 6.1.1

**Comment by derrek** [comment]
@litan1106 if you scan through the referenced issue https://github.com/SwiftyJSON/SwiftyJSON/issues/129 above you can find a work around.  This issue should probably get closed with a reference to that one since it's got more detail in it.   If you copy the [SwiftyJSON.swift](https://raw.githubusercontent.com/SwiftyJSON/SwiftyJSON/master/Source/SwiftyJSON.swift)  into your project, instead of using cocoapods and/or other methods where you need to include the module, it'll work.  Tests may still break though unless you do some further hackery also listed in the other write up.

**Comment by litan1106** [comment]
yea, i was using git submodule... Thanks.

**Comment by nunogoncalves** [comment]
Hi, I was having this issue and I was reading to throw myself of a cliff. I just found out what the problem was for me. Maybe this will help someone in the future. 

I'm using SwiftyJson through CocoaPods. 

Here's my code: 

```swift
HttpClientManager.get(url,
      headParameters: headParams,
      success: { (responseData: JSON) -> Void in
         //If I comment the next line, I get the seg fault 11
         SwiftEventBus.post(Constants.Events.LOGIN_SUCCESS, sender: responseData[""].string)
      }, failure: { (error: String) -> Void in
         //if I comment the next line, I get the seg fault 11
         SwiftEventBus.post(Constants.Events.LOGIN_FAILURE, sender: error)
      })
```
If I never use the closure variable (responseData in success and error in failure) then I get the segmentation fault 11.

**Comment by michaldudek** [comment]
@nunogoncalves +1 this saved me hours of blaming Xcode for crashing!

**Comment by nunogoncalves** [comment]
@michaldudek I'm glad I could help someone. :) 
Today was another fight with xcode for no reason was keeping indexing files indefinitely and I lost sintax highlighting. Had to uninstall and reinstall xcode to make it back to work. I guess we won't ever stop blaming xcode for something.

**Comment by flybikeGx** [comment]
Maybe it needn't such complex codes to make segmentation fault 11
func wrongswap<T>( var a :  T, var b : T ) { 
    let temp = a
    a = b
    b = temp
}
var a = ""
var b = ""
func wrongswap(&a, &b)

I'm Xcode 6.3.2. In fact i don't know how Swift deals with & , but i guess it's just the confusing & makes compiler reports such a confused seg fault 11. LOL

**Comment by christianlanz** [comment]
Same issue here.

**Comment by rteslaru** [comment]
@nunogoncalves oh man, thanks for saving my sanity here.. That was it for me: not using the closure variable.

**Comment by wxjg** [comment]
When I import a map stock, the same problem happened. I haven't settle it.
`#ifndef MAMap_Bridging_Header_h
#define MAMap_Bridging_Header_h

#import <MAMapKit/MAMapKit.h>
#import <AMapSearchKit/AMapSearchKit.h>

#endif /* MAMap_Bridging_Header_h */`

**Comment by wxjg** [comment]
@IBAction func Login(sender: AnyObject) {
        let parameters = ["username" : InputUsername.text, "pwd" : InputPassword.text]
        let url = "http://172.20.143.60:8080/yuqin/scheduleapp/ScheduleApp_login.action"
        Alamofire.request(.GET, url, parameters: parameters)
        .responseJSON { response in
                //处理结果
                switch (response.result) {
                case .Success(let value):
                    print("BeginOrderResult: \(value)")
                    if value["status"] == 1 {
                        
                        //更新本地保存的密码
                        let userDefault = NSUserDefaults.standardUserDefaults()
                        //userDefault.setObject(newPwd, forKey: "password")
                        userDefault.synchronize()
                    }
                case .Failure(let error):
                    NSLog("Error: %@", error)
                }
        }
}

same problem that  segmentation fault 11

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
