### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [SwiftyJSON/SwiftyJSON#126]
CocoaPods [officially](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) supports Swift libraries now. Even though its still in beta, it works fine and there's a few third party Swift libraries already supporting CococaPods.

Can you add SwiftyJSON to CocoaPods as well?

**Comment by larssondaniel** [comment]
+1

**Comment by mente** [comment]
Support is already on but podspec is not yet published to cocoapods.org itself. You can point it manually:
```ruby
   pod "SwiftyJSON", :git => "https://github.com/SwiftyJSON/SwiftyJSON"
```

**Comment by lingoer** [comment]
CocoaPods supports added.
```ruby
pod "SwiftyJSON"
```
Note that it requires your iOS deploy target >= 8.0

**Comment by Isuru-Nanayakkara** [comment]
:+1: Tested. Works great. Thanks.
