### ISSUE TITLE
example: needs to be better

### ISSUE THREAD

**Issue by gaming-hacker** [SwiftyJSON/SwiftyJSON#132]
the example is really too simple as it uses a local file.

add something like getting and parsing a playlist from youtube.

**Comment by freynolds** [comment]
I'm having issues creating a new object from raw to post!
There is only one example and its not very clear how to do this

**Comment by brendancboyle** [comment]
I eventually figured it out through trial and error, however I would have appreciated a complete example of FileManager integration. My current application has to constantly save and read JSON filed from the Documents directory of my application and the object deflation and re-inflation was a little convoluted.

**Comment by entotsu** [comment]
+1

**Comment by ldiqual** [comment]
@gaming-hacker @freynolds @brendancboyle @entotsu Sorry guys for the delay on this. I'm not too sure which example you're referring to, are you talking about the playground code maybe? If not, then I would argue that reading a file, local or remote, is not the responsibility of SwiftyJSON as a parsing library and would not need a detailed example in the readme.

**Comment by brendancboyle** [comment]
@Idiqual Wow I forgot I even commented on this. I checked out the current examples you have and they all look great. I use this package in a majority of my projects and I love it. You can probably close this issue as it is no longer relevant. Thanks!

**Comment by ldiqual** [comment]
@brendancboyle Thanks for following up, glad to hear the library works for you! Closing this
