### ISSUE TITLE
create JSON from rawrepresentable enum value?

### ISSUE THREAD

**Issue by refried** [SwiftyJSON/SwiftyJSON#133]
``` swift
enum Alert: String {
    case None = "none"
    case Breathe = "select"
    case Loop = "lselect"
}

let j: JSON = JSON(Alert.Loop) // type 'Alert' does not conform to protocol 'AnyObject'

func rawFromRR<T:RawRepresentable>(v: T) -> T.RawValue {
    return v.rawValue
}

let k: JSON = JSON(rawFromRR(Alert.Loop)) // this is ok
```

Maybe even support it as part of the AnyObject initializer? Although maybe not possible.

**Comment by ldiqual** [comment]
@refried I'm a bit confused, what would you expect `JSON(Alert.Loop)` to produce exactly? If you need to assign the raw value of an enum case to a JSON value, you can just do something like `json["key"] = enumCase.rawValue`. But maybe you're thinking about something else, let me know.

**Comment by ldiqual** [comment]
@refried Bump.

**Comment by refried** [comment]
I don’t know, I opened this ticket 2 years ago.  I suppose I would have expected it to produce json for the raw value underlying the enum.

**Comment by ldiqual** [comment]
@refried Oh wow, yes it's a super old issue, I thought it was from January of this year. Given that you can just use `Enum(rawValue: json["foo"].stringValue)` and `json["foo"] = enum.rawValue` I'm not sure I see the value of such a feature. I also don't see community support behind the proposal so I'm gonna go ahead and close this. Feel free to ping me if you'd like to reopen. Thanks!
