### ISSUE TITLE
build swiftyjson failed use carthage

### ISSUE THREAD

**Issue by haolong886** [SwiftyJSON/SwiftyJSON#140]
i can build Alamofire successfully, but build swiftyjson failed, error messages below:

>     SDKROOT = iphonesimulator8.1
>   
> === BUILD TARGET SwiftyJSON OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===
> 
> Check dependencies
> 
> Write auxiliary files
> write-file /Users/coolhand/Library/Developer/Xcode/DerivedData/SwiftyJSON-fremfbacgegukqfhjwfehvcuninn/Build/Intermediates/SwiftyJSON.build/all-product-headers.yaml
> 
> === BUILD TARGET SwiftyJSONTests OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===
> 
> Check dependencies
> 
> ** BUILD SUCCEEDED **
>  
> Build settings from command line:
>     SDKROOT = iphoneos8.1 
>   
> === BUILD TARGET SwiftyJSON OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===
> 
> Check dependencies
> 
> Write auxiliary files
> write-file /Users/coolhand/Library/Developer/Xcode/DerivedData/SwiftyJSON-fremfbacgegukqfhjwfehvcuninn/Build/Intermediates/SwiftyJSON.build/all-product-headers.yaml
> 
> === BUILD TARGET SwiftyJSONTests OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===
> 
> Check dependencies
> Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
> CodeSign error: code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 8.1'
>

**Comment by sman591** [comment]
Same issue here

**Comment by Mike724** [comment]
Also having this problem.

**Comment by jspahrsummers** [comment]
This is occurring because SwiftyJSON is building its Release configuration with a Distribution certificate. It can be [switched to Development](https://github.com/Carthage/Carthage/issues/370#issuecomment-77203572), or you can use `--configuration Debug` with Carthage to work around the issue.
