### ISSUE TITLE
Can not convert [JSON] to JSON

### ISSUE THREAD

**Issue by kilnyy** [SwiftyJSON/SwiftyJSON#143]
Suppose arrJSON's type is [JSON].

Program like following can not work.
```
json.array = arrJSON
let json:JSON = arrJSON
```

Does anybody have some idea to convert [JSON] to JSON?

**Comment by rishimukherjee** [comment]
I am trying to do the same thing. The SwiftyJSON library does not have a set for arrayValue and dictionaryValue. I asked it here: http://stackoverflow.com/questions/28233330/cannot-assign-json-array-or-json-object-to-a-json-using-swiftyjson-in-ios
But, no solution till now.

**Comment by kilnyy** [comment]
@rishimukherjee 
Currently I use following code to solve this, but I thing there should be some more clear solution.
```
let str = "[" + ",".join(arrJSON.map({$0.rawString()!})) + "]"
let json = JSON(data: str.dataUsingEncoding(NSUTF8StringEncoding)!)
```

**Comment by rishimukherjee** [comment]
@kilnyy 
Thank you :)
Is there a way to do this for a dictionary too?

**Comment by lwu** [comment]
Looks like this is a bug in the documentation, try json.arrayObject = rather than json.array =

**Comment by kilnyy** [comment]
@lwu 
`json.arrObject = ["1", "2", '3']` this works well, because type of `["1", "2", '3']` is `[String]`

`json.arrObject = arrJSON` this does not work when type of `arrJSON` is `[JSON]`. 
it has an compiler error `'JSON' is not identical to 'AnyObject'`.

I think the reason is in object setter of JSON struct
```
            case let array as [AnyObject]:
                _type = .Array
            case let dictionary as [String : AnyObject]:
                _type = .Dictionary
```
JSON here is an struct, but swift can not convert struct to AnyObject.

So I still not find any way to convert [JSON] to JSON clearly.

**Comment by Nelyus** [comment]
@kilnyy  what about that workaround, a bit less messy
```swift
json.arrObject = arrJSON.map({$0.object})
```

**Comment by lwu** [comment]
This extension worked for me (same idea as @Nelyus):

    // Patch SwiftyJSON to support constructing a JSON out of [JSON]
    extension JSON {
         public init(_ jsonArray:[JSON]) {
            self.init(jsonArray.map { $0.object })
        }
    }

**Comment by kilnyy** [comment]
It works, and really more clear than my solution, thank you!
