### ISSUE TITLE
Url slashes ' / ' are being replaced with ' \/ '

### ISSUE THREAD

**Issue by mdorta** [SwiftyJSON/SwiftyJSON#145]
So this is my code:

Alamofire.request(.GET, url, parameters: nil).responseJSON { (req, res, json, error) in
        self.showProfileInfo.text = JSON(json!).rawString()
        println(JSON(json!))
}

And in the println result on the console and in the UITextView I have this response:

{
"url" : "http:\/\/localhost:8000\/",
}

As you can see the value of url is not "http://localhost:8000/", what I can do for fixing this? If I print the json variable that Alamofire gives me it's displayed properly.

**Comment by tangplin** [comment]
The `rawString` is not the String with escape character.
Try this:
```swift
self.showProfileInfo.text = JSON(json!)["url"].stringValue
```
