### ISSUE TITLE
po'ing json in the console crashes xcode

### ISSUE THREAD

**Issue by jtremback** [SwiftyJSON/SwiftyJSON#147]
doing

``` swift
let json = JSON(json!)
```

then breaking and typing `po json` into the console crashes xcode.

**Comment by jeffalgera** [comment]
I think this is an Xcode specific issue and not SwiftyJSON.  Just curious, are you bridging from Objective-C as well in this project?

**Comment by jtremback** [comment]
yes, I was bridging some ObjC. I'll see if this has gone away in the new xcode.

**Comment by ldiqual** [comment]
This issue is kind of old and there hasn't been any update from @jtremback so I'll go ahead and close it. Let me know if you need to reopen it.
