### ISSUE TITLE
No Cocoapods support for iOS 7

### ISSUE THREAD

**Issue by donshefer** [SwiftyJSON/SwiftyJSON#151]
The requirements say you support iOS 7 but the pod only supports iOS 8.

Is this right? Does that mean to support iOS 7 I have to include the files manually?

**Comment by brendanmartens** [comment]
I am also wondering about this.

**Comment by lingoer** [comment]
Yes, you have to include the files manually.

**Comment by brendanmartens** [comment]
Is that because of how SwiftyJSON is bundled for cocoapods? I was reading up a bit and it sounds like there is a new framework type that only ios8+ can use... is SwiftyJSON using that?

**Comment by lingoer** [comment]
Yes, because the cocoapods is using that type.

**Comment by germanger** [comment]
So... including SwiftyJson with a pod wont work with IOS 7 ? but if I include SwiftyJson without a pod, it will?

**Comment by brendanmartens** [comment]
That's correct, although the reasons are a bit nuanced (it has to do with how a swift project must be built in order to be managed by cocoapods, IIRC).
