### ISSUE TITLE
SwiftyJSON seems to have issues with the new 6.3B

### ISSUE THREAD

**Issue by ejpusa** [SwiftyJSON/SwiftyJSON#157]
Have you tried to run Swifty under 6.3B?  Having no luck here. thanks

**Comment by Jasdev** [comment]
I'm gonna try to make a PR for this tonight :)

**Comment by insidegui** [comment]
The Swift compiler produces around 40 error messages when trying to compile SwiftyJSON on 6.3

**Comment by Jasdev** [comment]
@insidegui https://github.com/SwiftyJSON/SwiftyJSON/pull/158#issuecomment-74677249
