### ISSUE TITLE
Create JSON From String

### ISSUE THREAD

**Issue by mikewalkerjr** [SwiftyJSON/SwiftyJSON#159]
I was wondering if it is possible to create a JSON object from a String read from SQLite DB? I take the JSON object and call json.description to store the JSON string into the DB, but when I read the string back out, I can't seem to access any of the JSON values.

**Comment by shawnmitchell** [comment]
https://github.com/SwiftyJSON/SwiftyJSON/issues/9

**Comment by mikewalkerjr** [comment]
Perfect. Thank you.
