### ISSUE TITLE
Cannot set value

### ISSUE THREAD

**Issue by chitza** [SwiftyJSON/SwiftyJSON#161]
I'm trying to modify an existing JSON object but I get compile errors

```
class func add(coupon: JSON) {
    coupon["isFavorite"].int = JSON(1) // error: '@lvalue $T8' is not identical to 'Int?'
    coupon["isFavorite"] = JSON(true) // error: '@lvalue $T7' is not identical to 'JSON'
    coupon["isFavorite"].bool = true // error: '@lvalue $T6' is not identical to 'Bool?'
    coupon["isFavorite"].boolValue = true // '@lvalue $T6' is not identical to 'Bool'
    inner.coupons.append(coupon)
}
```

What's the proper way of modifying a JSON object?

**Comment by danielkiedrowski** [comment]
For me works: someJSON["foo"] = JSON("bar")

**Comment by ldiqual** [comment]
@chitza This issue has been inactive for a while so I'm gonna go ahead and close it. As first glance, it seems that you're trying to modify a `let` value (params are always let, if you need to modify them, just do `var param = param` then modify the param in question). Let me know if you want to reopen this.

**Comment by chitza** [comment]
Hi,

I haven't used this library in an while, so go ahead and close it.
