### ISSUE TITLE
Test failing on string-typed subscript getter

### ISSUE THREAD

**Issue by mrroach9** [SwiftyJSON/SwiftyJSON#162]
In Xcode 6.3 beta 2, things like json["name"] will return null. SubscriptTests.swift is therefore failing.

**Comment by chschu** [comment]
Could you please try again with the latest master? A similar issue has been fixed there.

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
