### ISSUE TITLE
i can't pass json object to singleton object

### ISSUE THREAD

**Issue by mirzadelic** [SwiftyJSON/SwiftyJSON#165]
Singleton object:

```
import Foundation
import SwiftyJSON

class SharedAd {
    var adItem: JSON!
    class var sharedInstance : SharedAd {
        struct Static {
            static let instance : SharedAd = SharedAd()
        }
        return Static.instance
    }

    var ad: JSON! {
        set {
            self.adItem = newValue
        }
        get {
            return self.adItem
        }
    }
}
```

main controller:

```
        Alamofire.request(.GET, url).responseJSON { (request, response, json, error) in
            if (json != nil) {
                var jsonObj = JSON(json!)
                SharedAd.sharedInstance.ad = jsonObj
                self.notificationCenter.postNotificationName("adChange", object: nil)
            }
        }
```

Why can't i pass this data?

![screen shot 2015-03-02 at 12 27 48](https://cloud.githubusercontent.com/assets/1878794/6439863/9b8f9c1e-c0d7-11e4-8b90-a8eaf5ceb2fc.png)
![screen shot 2015-03-02 at 12 28 04](https://cloud.githubusercontent.com/assets/1878794/6439864/9b9222fe-c0d7-11e4-91f1-40d6a3644ec4.png)

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it. At first glanced, it seems like an old crash in the swift compiler, it should be fixed by now.
