### ISSUE TITLE
SwiftyJSON crash when comparing strings: EXC_BAD_ACCESS / swift_unknownRetain

### ISSUE THREAD

**Issue by clozach** [SwiftyJSON/SwiftyJSON#166]
This is, perhaps, a duplicate...but the [original](https://github.com/SwiftyJSON/SwiftyJSON/issues/163) is pretty opaque.

TL;DR—String comparisons are sometimes causing a crash. Here's the SwiftyJSON code that's failing...

```
public func ==(lhs: JSON, rhs: JSON) -> Bool {

    switch (lhs.type, rhs.type) {
    case (.Number, .Number):
        return (lhs.object as NSNumber) == (rhs.object as NSNumber)
    case (.String, .String):
        return (lhs.object as String) == (rhs.object as String) // CRASH REALLY OCCURS HERE
```

And here's a more complete writeup on StackOverflow: http://stackoverflow.com/questions/28790277/crash-in-swiftyjson-during-string-comparison-swift-unknownretain

**Comment by clozach** [comment]
I found the problem, and I think it's a bug in Swift 1.1, the Foundation framework, or the interaction between the two. Long story short, it's possible to pass a string to this method whose underlying type is _TtCSs19_NSContiguousString, and that type throws an exception when cast to String, _but only_ when run in Release mode.

As mentioned in the StackOverflow post, I've submitted a bug to Apple & published here: http://openradar.appspot.com/radar?id=5314531127459840

As mentioned in the Open Radar, I'm happy to share the demo that reproduces this problem & can be reached at chris.lozach@activehours.com.

**Comment by gGololicic** [comment]
Will this bug be fixed anytime soon? I have the same problem

**Comment by clozach** [comment]
@gGololicic per the update at the top of the open radar report, Apple says, "There are no plans to address this." Per my stackoverflow writeup, I'd recommend the workaround of using `.stringValue` when switching on/matching values that may be a String.

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
