### ISSUE TITLE
SwiftyJSON behaves different codesigned as Release AdHoc

### ISSUE THREAD

**Issue by freynolds** [SwiftyJSON/SwiftyJSON#168]
This already happened two times for me with two different situations

Last week I had this issue (that I could solve)
This works in development (beeing item:JSON and event valid)
`switch item["event"] { ... }`
But crashes if signed as Ad Hoc
I found that using 
       `switch item["event"].stringValue { ... }`
Fixes it

And now I'm having an issue with the following
```
var json = JSON(userData.identities)
json[0]["name"] = json[0]["nickname"]
json[0]["id"] = json[0]["providerUID"]
```
I need to change the data from a provider to map it to our login data.
The first line `json[0]["name"] = json[0]["nickname"]` 
The second one `json[0]["id"] = json[0]["providerUID"]` crashes in release...

It's very annoying that the code has two different behaviours depending if its a release or not. It must be some Swift bug or something.

Any ideas?

**Comment by yannickl** [comment]
I have the same behaviour, it works perfectly in debug mode but I have bugs in release mode. It mainly crashed here https://github.com/SwiftyJSON/SwiftyJSON/blob/master/Source/SwiftyJSON.swift#L99.

I can't find why, I suspect the Swift compiler but without certitude.

**Comment by msegers** [comment]
Was hoping to find something, got the same problem as of now.

**Comment by freynolds** [comment]
On Swift 1.2 with the last version of SwiftyJSON my app is working fine
