### ISSUE TITLE
malloc: *** error for object when running on iPhone 6 (iOS 8.2)

### ISSUE THREAD

**Issue by benjaminhorner** [SwiftyJSON/SwiftyJSON#173]
I don't get the error when running in the Simulator on 8.2, bu when I build on my iPhone 6 (also running iOS 8.2) I get the following error.

malloc: **\* error for object 0x170054100: Invalid pointer dequeued from free list
**\* set a breakpoint in malloc_error_break to debug

XCode is also pointing to the following method : 

//MARK: - Comparable
extension JSON: Comparable {}

public func ==(lhs: JSON, rhs: JSON) -> Bool {

```
switch (lhs.type, rhs.type) {
case (.Number, .Number):
    return (lhs.object as NSNumber) == (rhs.object as NSNumber)
case (.String, .String):
    return (lhs.object as String) == (rhs.object as String)
case (.Bool, .Bool):
    return (lhs.object as Bool) == (rhs.object as Bool)
case (.Array, .Array):
    return (lhs.object as NSArray) == (rhs.object as NSArray)
case (.Dictionary, .Dictionary):
    return (lhs.object as NSDictionary) == (rhs.object as NSDictionary)
case (.Null, .Null):
    return true
default:
    return false
}
```

}

and more precisely to line : 

case (.String, .String):
        return (lhs.object as String) == (rhs.object as String)

**Comment by S0215** [comment]
Ok

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
