### ISSUE TITLE
Swift 1.2 - Is SwiftyJSON still usefull ?

### ISSUE THREAD

**Issue by thedamfr** [SwiftyJSON/SwiftyJSON#175]
Hi !

I'm an happy user of SwiftyJSON !
I was reading this article : http://nshipster.com/swift-1.2/
When I saw this

``` swift
var users: [User] = []

// load and parse the JSON into an array
if let
    path     = NSBundle.mainBundle().pathForResource("users", ofType: "json"),
    url      = NSURL(fileURLWithPath: path),
    data     = NSData(contentsOfURL: url),
    userList = NSJSONSerialization.JSONObjectWithData(data, options: nil, error: nil) as? [[String: AnyObject]] 
{
    // extract individual users
    for userDict in userList {
        if let
            id      = userDict["id"] as? Int,
            name    = userDict["name"] as? String,
            email   = userDict["email"] as? String,
            address = userDict["address"] as? [String: AnyObject]
        {
            users.append(User(id: id, name: name, ...))
        }
    }
}
```

Amazing, no ? What the impact on SwiftyJSON ?

Bisou

**Comment by jeeftor** [comment]
Good question

**Comment by totiz** [comment]
I've used SwiftyJSON for a while, and I thinks swift 1.2 is a big improvement.
To answer your question, yes it impact SwiftyJSON in term of more easier to use.
In term of "Do I want SwiftyJSON in swift 1.2?", the answer is still "YES" as example below.

Example 1,
```
// Without SwiftyJSON
    for userDict in userList {
        if let
            id      = userDict["id"] as? Int,
            name    = userDict["name"] as? String,
            email   = userDict["email"] as? String,
            address = userDict["address"] as? [String: AnyObject]
        {
            users.append(User(id: id, name: name, ...))
        }
    }

// With SwiftyJSON
    for userJson in userListJson.arrayValue {
        if let
            id      = userJson["id"].int,
            name    = userJson["name"].string,
            email   = userJson["email"].string,
            address = userJson["address"].dictionaryObject
        {
            users.append(User(id: id, name: name, ...))
        }
    }
```
This example is quite similar for bot with and without SwiftyJSON.


Example 2: Use default value if some keys have no value
```
// Without SwiftyJSON
    for userDict in userList {
        let id = userDict["id"] as? Int ?? 0
        let name = userDict["name"] as? String ?? ""
        let email = userDict["email"] as? String ?? ""
        let address = userDict["address"] as? [String: AnyObject] ?? [:]
        users.append(User(id: id, name: name, ...))
    }

// With SwiftyJSON
    for userJson in userListJson.arrayValue {
        let id = userJson["id"].intValue
        let name = userJson["name"].stringValue
        let email = userJson["email"].stringValue
        let address = userJson["address"].dictionaryObject ?? [:]
        users.append(User(id: id, name: name, ...))
    }
```

Example 3: Key chain (assume address is dictionary)
```
// Without SwiftyJSON
    let street = (userList[0]["address"] as? [String: AnyObject])?["street"] as? String

// With SwiftyJSON
    let street = userListJson[0]["address"]["street"].string
```

Just some example, you will see a lot benefits  when you dealing with more complex json data (bot get and set).

**Comment by stuffmc** [comment]
That said, SwiftyJSON has to be updated for 1.2 — right now it doesn't compile.

**Comment by totiz** [comment]
Use XCode6.3 Branch.

**Comment by stuffmc** [comment]
@totiz → thanks, but this has as well tons of errors :( Mainly `Expected type after 'as'` errors...

**Comment by totiz** [comment]
Cloud you show me some lines of code that you have errors, That we can discuss in more detail.

**Comment by stuffmc** [comment]
Sorry! My error. Somehow I had a bunch of errors but I tried again today and all worked fine. Thanks!

**Comment by j-h-a** [comment]
@thedamfr can you explain what is so amazing about the example posted? I have only been learning swift for 1 week so I have never seen swift before 1.2, so this looks normal - what couldn't you do before?

**Comment by thedamfr** [comment]
@j-h-a you should give a read to NSHipster's post mentioned in the first post : http://nshipster.com/swift-1.2/

But to make it short 
1.2 introduced the coma syntax in the "if let" binding. 
```swift
if let begin = begin, let middle = middle, let over = over where begin < over {
}
```

The equivalent approach in swift <1.2 would have been an ugly if pyramid.
```swift
if let begin = begin {
    if let middle = middle {
        if let over = over {
            if begin < over {
                println("it's over")
            }
        }
    }
}
```

**Comment by stuffmc** [comment]
Just to complete @thedamfr (note for @j-h-a) in Swift 1.2 you can use only 1 `let` this way:

    if let begin = begin, middle = middle, over = over where begin < over {
    }

**Comment by thedamfr** [comment]
Thx @stuffmc fixed it.

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
