### ISSUE TITLE
Is an UIColor getter useful for SwiftyJSON

### ISSUE THREAD

**Issue by lastMove** [SwiftyJSON/SwiftyJSON#179]
Hi,
I have made an extension to SwiftyJson that add a "color" and "colorValue" computed property (Just getter).
so 

    json["colorHexString"].color

returns an optional UIColor. It works with String and Number.

Is it useful or not?
If yes I will make a Pull Request.
Thanks and regards.

**Comment by zhigang1992** [comment]
IMHO
SwiftyJSON should only handle those json types.

Properties like `color` and `date`, they are not a part of json types, they are all just `strings`.

But feel free to post your work somewhere, or as a separate repo.

It might be valuable to other ppl.
