### ISSUE TITLE
Podfile claims iOS 8 required, Website claims iOS 7

### ISSUE THREAD

**Issue by cellularmitosis** [SwiftyJSON/SwiftyJSON#180]
Hi,

Your podspec claims that iOS 8+ is required, but README.md claims iOS 7+.

Which one is it?

Thanks,
Jason

**Comment by skofgar** [comment]
It's because of a cocoapods framework: https://github.com/SwiftyJSON/SwiftyJSON/issues/151

**Comment by keab42** [comment]
I'm having trouble when following the guide for iOS 7. It says to just drop the xcodeproj into the project if I'm using workspaces.

Does that mean to drop it in underneath my project or into the workspace at the same level as my project and the cocoapods project?

Do I also then need to include an import statement?

**Comment by arm0nic** [comment]
You have to put it inside your projects folder (for example in supporting files group). Once this is done you don't have to import anything as it is in the same namespace.

**Comment by ShahNewazKhan** [comment]
Thanks! Adding the SwiftyJSON.swift file directly to the supporting files group solved the ios 7 issue for me!
