### ISSUE TITLE
Check if object is JSON object

### ISSUE THREAD

**Issue by justinmakaila** [SwiftyJSON/SwiftyJSON#183]
I would like to be able to check if `json[key]` is a JSON object.

The REST API I'm interacting with may embed a string for a key where circular embeds would happen. For instance:

```
"user": {
  "id": "dasoghweoghw",
  "account": {
    "id": "3285usodahg",
    "service": "twitter",
    "owner": "dasoghweoghw"
  },
  ...
}
```

My serialization method expects `user.account.owner` to be of type `User`, but because the API avoids embedding circular data, it crashes every time.

A workaround I've used in the past:

```
if let owner = json["owner"].string {
  println("Nothing to serialize...")
} else {
  self.owner = User(json: json["owner"])
}
```

Another idea:

```
if let json["owner"].string == nil {
  self.owner = User(json: json["owner"])
}
```

Any suggestions on how to handle this?

**Comment by zhigang1992** [comment]
```swift
if let a = Optional.Some(json["aoeua"]) where a.string == nil {
}
```

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
