### ISSUE TITLE
Use of unresolved identifier 'JSON'

### ISSUE THREAD

**Issue by pekpon** [SwiftyJSON/SwiftyJSON#184]
Hey i'm in trouble installing SwiftJSON in my project.
I'm using cocoapods 0.36 and xcode 6.2, deploy target >= 8.0

I'm using Alamofire and when I i'm trying to parse the json with this piece of code:

    Alamofire.request(.GET, "http://localhost:3000/products")
            .responseJSON { (req, res, json, error) in
                var json = JSON(json!)
        }

Xcode is showing the next error:

     Use of unresolved identifier 'JSON'

Why? Thanks!

**Comment by jayasme** [comment]
Please try to use following constructor of JSON class:
 
public init(data:NSData, options opt: NSJSONReadingOptions = .AllowFragments, error: NSErrorPointer = nil)

**Comment by lezeualex** [comment]
i already have this constructor class

**Comment by pferdefleisch** [comment]
try `import SwiftyJSON` at the top of the file where you are using JSON.

**Comment by neelamsharma12** [comment]
@pekpon , I had the same issue. To resolve this just import SwiftyJSON at the top of your file in which you are using it

**Comment by pekpon** [comment]
Thanks to all! ;)
