### ISSUE TITLE
I can't push an object in a json array.

### ISSUE THREAD

**Issue by Hanggi** [SwiftyJSON/SwiftyJSON#185]
I got a json array from http, and I want to push an object in this array, but nothing happend.

I want to:

    // json = [{...}, {...}, {...}]
      json[3] = [...]
    // or
      json.push(...)
    // or
      json.addObject(...)

how to do it?

**Comment by chschu** [comment]
That doesn't seem to be possible currently. The subscript setter can only update existing entries for the array case.

Modifying the wrapped Array via `json.arrayObject!.append(...)` could work.

**Comment by zhigang1992** [comment]
Should be working now
```swift
var json:JSON = [1,2,3]
var detailArray = json.arrayValue
detailArray.append(JSON(12))
print(detailArray)
```
