### ISSUE TITLE
'JSON' is not convertible to 'JSON'

### ISSUE THREAD

**Issue by willsteinmetz** [SwiftyJSON/SwiftyJSON#189]
I ran into an issue when I was writing a function in a different class that had a parameter of type JSON. I'm absolutely certain that the variable being passed in is of type JSON and is not nil. However, the compiler keeps throwing an error of type `'JSON' is not convertible to 'JSON'`.

What is interesting is that if I move the function into the same class as the calling function, the code will compile just fine. This is a problem because it would require me to copy that function into multiple classes which would not be good. Also, it is a very strange issue to have the compiler say that it can't convert an object to a type that it is already.

**Comment by bugs181** [comment]
I would suggest sharing some reproducible code with us. As it stands, I feel there is insufficient information to help you further. I believe I saw this once but it was a syntactical error on my part.

**Comment by harshag** [comment]
I am facing exactly same issue. Code snippet and more details are here,
http://stackoverflow.com/questions/36763094/cannot-convert-value-of-type-json-to-expected-argument-type-json

**Comment by harshag** [comment]
After banging my head for several hours found out that issue was due to including SwiftyJSON file for both app and test targets.

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
