### ISSUE TITLE
使用中发现解析效率比较低

### ISSUE THREAD

**Issue by l12ab** [SwiftyJSON/SwiftyJSON#190]
处理一个2层的json，拿一个值出来要大概几毫秒，一次要拿6个值，然后要循环20次
let username = json[0]["name"].stringValue   类似这样的每次取6个值，循环20次
在模拟器里测试循环这20次大概要300-600毫秒，真机iphone5测试 大概是1-2.5秒

**Comment by dcharbonnier** [comment]
Je donnerai bien un coup de main, dommage qu'il ne soit pas possible de s'entendre sur une langue commune....

**Comment by baby03201** [comment]
I try to translate the problem @l12ab asked:
Question title: Low performance issue 
Process a two layer Json will cost few miliseconds to get the result.
If we need to get 6 results once and loop 20 times:
Ex.  let username = json[0]["name"].stringValue ( loop 20 times and get 6 different values )
In simulator this will take around 300 - 600 ms,
but in real phone(iPhone 5), it took around 1.0 - 2.5 s

**Comment by tangplin** [comment]
@l12ab 能把JSON文件给我吗？

**Comment by l12ab** [comment]
https://tppa.sinaapp.com/api/wfdm/testforswfityjson
做了个测试页，可选GET参数
page 数值
wfdm 汉字

**Comment by meng-zhang** [comment]
@l12ab 看到你的这个issue后 我就一直没有使用SwiftyJSON  不过刚才我按照你的做法和你给的sample做了一个测试，发现很快啊。我把代码贴过来，你看看是不是这样测试的，如果不是，能不能贴一下你的代码？

English translation for everyone:  
@l12ab I decided not to use SwiftyJSON as I saw your issue here. I did a test using your instruction and sample just now, turns out it was not that slow. Please take a look of my test code below. If this is not the correct way to reproduce it, could you please provide me your own testing code?

```Swift
        Alamofire.request(.GET, "https://tppa.sinaapp.com/api/wfdm/testforswfityjson")
            .responseJSON { (_, _, json, _) in
                let json = JSON(json!)
                
                let start = CFAbsoluteTimeGetCurrent()
                for index in 0...19 {
                    let cfzl = json[index]["cfzl"].stringValue
                    let wfms = json[index]["wfms"].stringValue
                    let qzcs = json[index]["qzcs"].stringValue
                    let wfgd = json[index]["wfgd"].stringValue
                    let fltw = json[index]["fltw"].stringValue
                    let fkjemax = json[index]["fkjemax"].stringValue
                                    }
                let timeTaken = CFAbsoluteTimeGetCurrent() - start
                println(timeTaken)
        }
```

XCode 6.3.1

模拟器(simulator): iPhone 8.3
结果是: 0.0225430130958557

真机 (real device): iPhone 6 plus   iOS8.3
结果是: 0.144482016563416

 + @tangplin

**Comment by l12ab** [comment]
网络请求后调用方法handleResult()

```
let startTime = NSDate().timeIntervalSince1970
println("start-\(startTime)")
self.handleCodeSearchResult(json)
let endTime = NSDate().timeIntervalSince1970
println("end-\(endTime)")
let elapsedTime = endTime - startTime
println(elapsedTime)
```


```
func handleCodeSearchResult(json:JSON) {
        var totalCount: Int?
        if let countOfItems = json.array?.count{
            totalCount = countOfItems
        }
        var i = 0
        while i < totalCount {
            var cQzcs = json[i]["qzcs"].stringValue
            println("\(i)-qzcs-\(NSDate().timeIntervalSince1970)")
            var cCfzl = json[i]["cfzl"].stringValue
            println("\(i)-cfzl-\(NSDate().timeIntervalSince1970)")
            var cFkjemin = json[i]["fkjemin"].stringValue
            println("\(i)-fkjemin-\(NSDate().timeIntervalSince1970)")
            var cFkjemax = json[i]["fkjemax"].stringValue
            println("\(i)-fkjemax-\(NSDate().timeIntervalSince1970)")
            var cExpired = json[i]["expired"].stringValue
            println("\(i)-expired-\(NSDate().timeIntervalSince1970)")
            var desc = ""
            var cQzcsDesc = ""
            var cCfzlDesc = ""
            if cQzcs != "" {
                cQzcsDesc = "\n强措:\(cQzcs)"
            }
            if cCfzl != "" {
                cCfzlDesc = "\n处罚种类:\(cCfzl)"
            }
            desc = "违反:"+json[i]["wfgd"].stringValue+"\n处罚:"+json[i]["fltw"].stringValue+cQzcsDesc+cCfzlDesc+"\n有效期:"+json[i]["dateb"].stringValue+"至"+json[i]["datee"].stringValue
            println("\(i)-desc(4 json values)-\(NSDate().timeIntervalSince1970)")
            var fkje = ""
            if cFkjemin == cFkjemax {
                fkje = "\(cFkjemax)"
            }else{
                fkje = "\(cFkjemin)-\(cFkjemax)"
            }
            var codeData = [json[i]["code"].stringValue, json[i]["wfms"].stringValue, "\(desc)", "\(fkje)", json[i]["jfs"].stringValue]
            println("\(i)-data(3 json values)-\(NSDate().timeIntervalSince1970)")
            ++i
        }
    }
```

output in simulator iPhone 6  (8.2)

start-1429962807.5562
0-qzcs-1429962807.60147
0-cfzl-1429962807.60249
0-fkjemin-1429962807.60353
0-fkjemax-1429962807.6054
0-expired-1429962807.60745
0-desc(4 json values)-1429962807.62691
0-data(3 json values)-1429962807.63184
1-qzcs-1429962807.63318
1-cfzl-1429962807.63491
1-fkjemin-1429962807.63594
1-fkjemax-1429962807.63747
1-expired-1429962807.63941
1-desc(4 json values)-1429962807.64528
1-data(3 json values)-1429962807.65024
2-qzcs-1429962807.65208
2-cfzl-1429962807.65378
2-fkjemin-1429962807.65704
2-fkjemax-1429962807.65813
2-expired-1429962807.66059
2-desc(4 json values)-1429962807.66812
2-data(3 json values)-1429962807.6836
3-qzcs-1429962807.68708
3-cfzl-1429962807.68834
3-fkjemin-1429962807.6893
3-fkjemax-1429962807.69098
3-expired-1429962807.69393
3-desc(4 json values)-1429962807.70208
3-data(3 json values)-1429962807.70772
4-qzcs-1429962807.7451
4-cfzl-1429962807.77093
4-fkjemin-1429962807.77388
4-fkjemax-1429962807.78971
4-expired-1429962807.79165
4-desc(4 json values)-1429962807.82777
4-data(3 json values)-1429962807.83446
5-qzcs-1429962807.85104
5-cfzl-1429962807.89115
5-fkjemin-1429962807.89324
5-fkjemax-1429962807.91149
5-expired-1429962807.91483
5-desc(4 json values)-1429962807.93198
5-data(3 json values)-1429962807.93487
6-qzcs-1429962807.93595
6-cfzl-1429962807.937
6-fkjemin-1429962807.94115
6-fkjemax-1429962807.943
6-expired-1429962807.94423
6-desc(4 json values)-1429962807.94926
6-data(3 json values)-1429962807.95494
7-qzcs-1429962807.95725
7-cfzl-1429962807.95942
7-fkjemin-1429962807.96165
7-fkjemax-1429962807.96517
7-expired-1429962807.96654
7-desc(4 json values)-1429962807.97006
7-data(3 json values)-1429962807.97301
8-qzcs-1429962807.97573
8-cfzl-1429962807.97669
8-fkjemin-1429962807.97809
8-fkjemax-1429962807.97924
8-expired-1429962807.9805
8-desc(4 json values)-1429962807.9851
8-data(3 json values)-1429962807.99079
9-qzcs-1429962808.00148
9-cfzl-1429962808.0038
9-fkjemin-1429962808.00479
9-fkjemax-1429962808.00574
9-expired-1429962808.00681
9-desc(4 json values)-1429962808.03581
9-data(3 json values)-1429962808.04027
10-qzcs-1429962808.04173
10-cfzl-1429962808.04277
10-fkjemin-1429962808.04394
10-fkjemax-1429962808.04495
10-expired-1429962808.0463
10-desc(4 json values)-1429962808.06056
10-data(3 json values)-1429962808.07081
11-qzcs-1429962808.07187
11-cfzl-1429962808.07282
11-fkjemin-1429962808.0738
11-fkjemax-1429962808.08233
11-expired-1429962808.09182
11-desc(4 json values)-1429962808.0989
11-data(3 json values)-1429962808.10396
12-qzcs-1429962808.10725
12-cfzl-1429962808.10902
12-fkjemin-1429962808.11058
12-fkjemax-1429962808.11174
12-expired-1429962808.11422
12-desc(4 json values)-1429962808.11989
12-data(3 json values)-1429962808.12298
13-qzcs-1429962808.12456
13-cfzl-1429962808.12553
13-fkjemin-1429962808.12649
13-fkjemax-1429962808.12743
13-expired-1429962808.12838
13-desc(4 json values)-1429962808.13288
13-data(3 json values)-1429962808.177
14-qzcs-1429962808.18092
14-cfzl-1429962808.18208
14-fkjemin-1429962808.19266
14-fkjemax-1429962808.19972
14-expired-1429962808.20121
14-desc(4 json values)-1429962808.20872
14-data(3 json values)-1429962808.21156
15-qzcs-1429962808.2126
15-cfzl-1429962808.21397
15-fkjemin-1429962808.216
15-fkjemax-1429962808.21955
15-expired-1429962808.23482
15-desc(4 json values)-1429962808.25705
15-data(3 json values)-1429962808.26584
16-qzcs-1429962808.26734
16-cfzl-1429962808.26905
16-fkjemin-1429962808.27024
16-fkjemax-1429962808.27151
16-expired-1429962808.27247
16-desc(4 json values)-1429962808.27592
16-data(3 json values)-1429962808.2795
17-qzcs-1429962808.29531
17-cfzl-1429962808.2966
17-fkjemin-1429962808.29758
17-fkjemax-1429962808.30002
17-expired-1429962808.35788
17-desc(4 json values)-1429962808.36999
17-data(3 json values)-1429962808.38016
18-qzcs-1429962808.38141
18-cfzl-1429962808.38378
18-fkjemin-1429962808.38609
18-fkjemax-1429962808.38868
18-expired-1429962808.40601
18-desc(4 json values)-1429962808.42831
18-data(3 json values)-1429962808.44655
19-qzcs-1429962808.44777
19-cfzl-1429962808.45955
19-fkjemin-1429962808.46407
19-fkjemax-1429962808.46701
19-expired-1429962808.48486
19-desc(4 json values)-1429962808.48849
19-data(3 json values)-1429962808.49219
end-1429962808.49237
0.936176061630249

936毫秒，平均每次468毫秒（每次取了12次值）
这个耗时浮动也较大，刚刚测了20多次，在400多-900多之间浮动，上面是耗时最多的一次
我手上只有iPhone 5真机，性能比模拟器差，耗时肯定更高，就不测了。

**Comment by l12ab** [comment]
@meng-zhang 你的那段代码我在我这里试了一下，耗时约200-500毫秒。

后来调试中发现，json.array?.count 或者json.arrayValue.count也很耗时，约30-50毫秒，所以换了方法

把while循环改成for (index: String, subJson: JSON) in json， 内部的json[i]换成subJson，然后耗时降到了30-90毫秒。
但是还是没有你的22毫秒快，而且我在想，如果你的那段代码也改成这样，会不会更快

```swift
func handleCodeSearchResult(json:JSON) {
        var i = 0
        for (index: String, subJson: JSON) in json {
            let cQzcs = subJson["qzcs"].stringValue
            let cCfzl = subJson["cfzl"].stringValue
            let cFkjemin = subJson["fkjemin"].stringValue
            let cFkjemax = subJson["fkjemax"].stringValue
            let cExpired = subJson["expired"].stringValue
            var cQzcsDesc = ""
            var cCfzlDesc = ""
            if cQzcs != "" {
                cQzcsDesc = "\n强措:\(cQzcs)"
            }
            if cCfzl != "" {
                cCfzlDesc = "\n处罚种类:\(cCfzl)"
            }
            let desc = "违反:"+subJson["wfgd"].stringValue+"\n处罚:"+subJson["fltw"].stringValue+cQzcsDesc+cCfzlDesc+"\n有效期:"+subJson["dateb"].stringValue+"至"+subJson["datee"].stringValue
            var fkje = ""
            if cFkjemin == cFkjemax {
                fkje = "\(cFkjemax)"
            }else{
                fkje = "\(cFkjemin)-\(cFkjemax)"
            }
            var codeData = [subJson["code"].stringValue, subJson["wfms"].stringValue, "\(desc)", "\(fkje)", subJson["jfs"].stringValue]
            ++i
        }
    }
```

**Comment by l12ab** [comment]
@tangplin @meng-zhang 刚刚升级到了Xcode 6.3.1，性能再一次提升，如果使用json[i]模式，耗时100-200毫秒，如果是subJson模式，耗时20-60毫秒。看来

**Comment by meng-zhang** [comment]
@l12ab  所以我觉得这个速度是可以接受的吧？

**Comment by l12ab** [comment]
@meng-zhang 嗯，能接受了。不过苹果这swift 1.1版本性能确实差了点。然后能麻烦编辑一下上面的回复，把我发的那个网址去掉吗？ 我自己发的已经去掉了

**Comment by meng-zhang** [comment]
@l12ab 去掉了

**Comment by l12ab** [comment]
@meng-zhang 谢谢~~
