### ISSUE TITLE
Array<JSON> is not convertible to 'JSON'

### ISSUE THREAD

**Issue by zarghol** [SwiftyJSON/SwiftyJSON#191]
I wanted to parse a array of type MyObject. I have
   <code> func toJSON() -> JSON </code>
into my class, but with an array, I can't do <code>myArray.map { $0.toJSON() } </code> and then have a JSON with the result... I got this error : "Array<JSON> is not convertible to 'JSON'"
I test in Swift 1.0 and 1.2
I think, write a JSONable protocol should be good to help to transform user classes into JSON :)

Please can you fix this, or help me to fix ?
Thanks !

**Comment by chschu** [comment]
You could use the (quite new) array-based initializer: `JSON(myArray.map { $0.toJSON() })`, which has been added in 28ab56bc653298111f623b1269088355f65a6b8b.

I don't think this can be done with an implicit type conversion in Swift.
