### ISSUE TITLE
No mechanism to create empty object.

### ISSUE THREAD

**Issue by richburdon** [SwiftyJSON/SwiftyJSON#197]
There doesn't seem to be a mechanism to create an empty dictionary object? Since [] in swift can be interpreted as an empty array or empty object. And,

var json:JSON = JSON([])

creates an empty array, so you can't add properties.

E.g., This would seem to be appropriate, but doesn't work

var json:JSON = JSON()
json["id"].intValue = 123
println(json)
{
  "id": 123
}

**Comment by chschu** [comment]
In Swift, [:] represents an empty dictionary, but SwiftyJSON doesn't have an dictionary-based initializer yet. This should be quite easy to add.

**Comment by chschu** [comment]
Just checked it: `var json:JSON = [:]` works, because `JSON` implements the `DictionaryLiteralConvertible` protocol.

**Comment by dbsima** [comment]
I think this issue can be closed.

**Comment by alokrajiv** [comment]
@chschu Any idea why `var parcelData : JSON = [:]` is throwing me a warning of `'init(nilLiteral:)' is deprecated: use JSON.null instead. Will be removed in future versions`.
{Swift 3, Xcode 9.0, SwiftyJSON v3.1.4}

**Comment by alokrajiv** [comment]
@chschu its resolved...was just xcode bug i guess...sorry & thanks!
