### ISSUE TITLE
'NSString?' is not convertible to 'String?' error with Swift 1.2

### ISSUE THREAD

**Issue by nico75005** [SwiftyJSON/SwiftyJSON#198]
Just updated to Xcode 6.3 and with the last version of SwiftyJSON I get this error on line 454 (`return NSString(data: data, encoding: encoding)`):

`'NSString?' is not convertible to 'String?'`

**Comment by nico75005** [comment]
One way to fix it seems to be by adding `as? String` at the end of the line.

**Comment by rcgary** [comment]
@nico75005 There is a `xcode6.3` branch have not merged into `master` yet, if you want to use on Swift 1.2, you need wait the merge or get code from `xcode6.3` for now

**Comment by nico75005** [comment]
Okay sorry I didn't pay attention about the branch. Thanks!
