### ISSUE TITLE
Not working with Swift 1.2

### ISSUE THREAD

**Issue by Euphrates-Media** [SwiftyJSON/SwiftyJSON#208]
Hi

I tried to use v2.2 but I get this error from CococaPods:

```
[!] Unable to satisfy the following requirements:

- `SwiftyJSON (>= 2.2)` required by `Podfile`
```

And when I try to use previous versions, there are lots of error which appeared in Swift 1.2, such as using `as!` instead of `as`

**Comment by j-h-a** [comment]
Use the xcode6.3 branch for now, which works with Swift 1.2

    use_frameworks!
    pod "SwiftyJSON", :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode6.3'

I think that branch will eventually get merged into master, then you can use the normal 2.x in your Podfile again.

**Comment by Euphrates-Media** [comment]
Thanks for quick reply! Worked!

**Comment by thedamfr** [comment]
Since xcode 6.3 is released, that would be great to submit a new version of the pod that require sdk 8.3

**Comment by RShergold** [comment]
I agree with @thedamfr 

Could you at the very least make a change to the readme with this fix @j-h-a ?

**Comment by j-h-a** [comment]
This isn't my project - I could make the change and send a pull-request like anyone else I suppose. I've only been learning Swift for 2 days and was trying this for fun/learning. It's probably best to let the maintainer do things like this as he might be planning to merge the branch soon anyway, and I don't know the state of this other branch (experimental? unstable? work-in-progress?).

I think the maintainer is @tangplin - is it best to add such a note to the readme for now, or will this become the master soon?

**Comment by tangplin** [comment]
SwiftyJSON 2.2.0 has been pushed.
