### ISSUE TITLE
Publish Podspec for version 2.2.0

### ISSUE THREAD

**Issue by evenh** [SwiftyJSON/SwiftyJSON#210]
Please consider publishing the Podspec for version 2.2.0, since it's now supports Swift 1.2 and is in the master branch.

**Comment by damienadermann** [comment]
:+1:

**Comment by Progeny** [comment]
I agree with evenh! Please publish the pod to the trunk!

**Comment by arm0nic** [comment]
Would be great!

**Comment by bluesky0109** [comment]
skydeMacBook-Pro-2:MobileOffice-Swift sky$ pod update
Update all pods
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `SwiftyJSON (>= 2.2)` required by `Podfile`
skydeMacBook-Pro-2:MobileOffice-Swift sky$ 

skydeMacBook-Pro-2:MobileOffice-Swift sky$ pod search SwiftyJSON
-> SwiftyJSON (2.1.3)
   SwiftyJSON makes it easy to deal with JSON data in Swift
   pod 'SwiftyJSON', '~> 2.1.3'
   - Homepage: https://github.com/SwiftyJSON/SwiftyJSON
   - Source:   https://github.com/SwiftyJSON/SwiftyJSON.git
   - Versions: 2.1.3 [master repo]
skydeMacBook-Pro-2:MobileOffice-Swift sky$ 

I can not get v2.2.0 via cocoapods

**Comment by juggernate** [comment]
:+1:

**Comment by ghecho** [comment]
:+1:

**Comment by wakinchan** [comment]
:+1:

**Comment by tangplin** [comment]
SwiftyJSON 2.2.0 has been pushed.

**Comment by evenh** [comment]
Thank you @tangplin :clap:
