### ISSUE TITLE
无法获取到 2.2版本的

### ISSUE THREAD

**Issue by bluesky0109** [SwiftyJSON/SwiftyJSON#211]
skydeiMac:MobileOffice-Swift sky$ pod update
Update all pods
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `SwiftyJSON (>= 2.2)` required by `Podfile`
skydeiMac:MobileOffice-Swift sky$

**Comment by bluesky0109** [comment]
Please update the Podspec for version 2.2.0, I update the Xcode to V6.3,Swift1.2 can not work with SwiftyJSON2.1.3,thanks.

**Comment by Onetaway** [comment]
have the same problem

**Comment by tangplin** [comment]
SwiftyJSON 2.2.0 has been pushed.
