### ISSUE TITLE
pod -> SwiftyJSON (2.1.3) is out-of-date if we compare it to the version mentioned in README.md file.

### ISSUE THREAD

**Issue by alino91** [SwiftyJSON/SwiftyJSON#212]
In your README.md you mention that:

pod "SwiftyJSON", ">= 2.2"

Whereas when I use CocoaPods in my terminal, pod search SwiftyJSON returns me:

-> SwiftyJSON (2.1.3)

So you should fix that ASAP.

And also I wanted to tell you thank you for this iOS API.

**Comment by tangplin** [comment]
SwiftyJSON 2.2.0 has been pushed.
