### ISSUE TITLE
Cannot subscript a value of type 'JSON' with an index of type '[String]'

### ISSUE THREAD

**Issue by tempire** [SwiftyJSON/SwiftyJSON#213]
Using XCode 6.3 (Swift 1.2), this works just fine:

```
let that = json[["_source", "customer", "first_name"]]
```

However, this next block reports a compiler error:

```
let that = ["_source", "customer", "first_name"]
let thing = json[that]
```

Error: _Cannot subscript a value of type 'JSON' with an index of type '[String]'_

I don't understand why these two would be any different.

**Comment by tangplin** [comment]
@tempire Try:
```swift
let that:[SubscriptType] = ["_source", "customer", "first_name"]
let thing = json[that]
```

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.

**Comment by Domsware** [comment]
I have the same issue here...

**Comment by ldiqual** [comment]
@Domsware Can you try @tangplin 's solution and get back to me with your result? Thanks!
