### ISSUE TITLE
Object prop of JSON type cannot be edited

### ISSUE THREAD

**Issue by wayx** [SwiftyJSON/SwiftyJSON#215]
Hi, I'm stuck trying to edit JSON object.
After some investigation found a problem with JSON type object property (Swift 1.2):

``` swift
class Example
{
    var data: JSON!

    init()
    {
        data = JSON([ 0,1,2 ])
        data[0] = JSON(55)
        println(data[0].intValue) // outputs "0"

        var data2 = JSON([ 0,1,2 ])
        data2[0] = JSON(55)
        println(data2[0].intValue) // outputs "55"
    }
}
```

`public` accessors on class and/or var doesn't help

**Comment by wayx** [comment]
Removing `!` from `data` prop declaration helped.
But it seems like a bug though

**Comment by AnthonyMDev** [comment]
+1

Not sure how to fix this, but it seems like a pretty big bug to me.

Is it possible that this is occurring due to the property being an `Optional`

**Comment by wongzigii** [comment]
#793 has been merged into master. 

For more mutability, please check out [MutabilityTests](https://github.com/SwiftyJSON/SwiftyJSON/blob/master/Tests/SwiftyJSONTests/MutabilityTests.swift)

Cheers.
