### ISSUE TITLE
Crash on .array call

### ISSUE THREAD

**Issue by ProjectDent** [SwiftyJSON/SwiftyJSON#216]
I can't replicate this issue myself. Based on a crashlog from a user, the app is consistently crashing on line 124 of SwiftyJSON, inside the variable setter `public var object: AnyObject`:

```
case let dictionary as [String : AnyObject]:
```

Crashlog:

> 12  Today                         0x00000001001147ac Today.JSON.array.getter : [Today.JSON]? (SwiftyJSON.swift:124)

A level above that is my own app, where the line it crashes on is:

```
if let results = jsonValue["items"].array {
```

**Comment by neelamsharma12** [comment]
@ProjectDent , Could you please check whether jsonValue["items"] is returning array or dictionary as this   piece of code works fine for me. If it is returning dictionary then use jsonValue["items"].dictionary.

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.

**Comment by mansishah278** [comment]
I have the same issue

**Comment by mansishah278** [comment]
![screen shot 2017-11-22 at 5 54 47 pm](https://user-images.githubusercontent.com/22022743/33127406-5cd89e6a-cfae-11e7-9db2-c6b834cea829.png)
