### ISSUE TITLE
Why check for NS data type then set Swift data type?

### ISSUE THREAD

**Issue by DimaVartanian** [SwiftyJSON/SwiftyJSON#217]
Great work here! I'm getting familiar with this library and just trying to figure something out here.

Example when checking for type
`case let string as NSString:
                _type = .String`

Why not just check  for `String` rather than `NSString`?

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
