### ISSUE TITLE
'AnyObject' is not convertible to 'String'; did you mean to use 'as!' to force downcast?

### ISSUE THREAD

**Issue by datomnurdin** [SwiftyJSON/SwiftyJSON#218]
As per subject, I got a lot of this error message inside the library.

```
/Users/MNurdin/Documents/iOS/xxxxx/Library/SwiftyJSON.swift:142:37: 'AnyObject' is not convertible to '[AnyObject]'; did you mean to use 'as!' to force downcast?
```

**Comment by carloperez** [comment]
Are you using Xcode 6.3?

**Comment by datomnurdin** [comment]
yes, i'm using xcode 6.3.

**Comment by LeeVidor** [comment]
Just dowloaded and get with xcode 6.3.1

**Comment by datomnurdin** [comment]
Fixed with xcode 6.3.1.

**Comment by afixibiranchi** [comment]
I am using 6.3.2 and still getting the error.

**Comment by nelsonkd** [comment]
I am getting the error with 6.4. About 40 of them.

**Comment by neonowy** [comment]
40 errors with Xcode 6.4

**Comment by lptr2** [comment]
in Version 7.2 (7C68)
these errors are back
