### ISSUE TITLE
156 compiler errors Mavericks + Xcode 6.2

### ISSUE THREAD

**Issue by dewib** [SwiftyJSON/SwiftyJSON#220]
... am I making a simple blunder or is an upgrade necessary or???

mostly 'Expected type after as' errors

1) downloaded zip opened project results as above for various tests/targets
2) copied file to os x project results as above
3) carthage install opened project result as above

**Comment by xctom** [comment]
Because Swift upgrades to 1.2 in Xcode 6.2 and you should replace all 'as' by 'as!'

**Comment by xctom** [comment]
Just upgrade your Xcode to 6.3. And you will be fine.

**Comment by dewib** [comment]
Thank you, I figured that might be it. This might just be the motivation I needed to upgrade to Yosemite...

**Comment by dewib** [comment]
... it was and all works as expected. I'll face down Logic 9 stability at a later date...
