### ISSUE TITLE
'NSString?' is not convertible to 'String?'

### ISSUE THREAD

**Issue by datomnurdin** [SwiftyJSON/SwiftyJSON#225]
I got this error message after updated my xcode to 6.3.1.

```
/Users/MNurdin/Documents/iOS/RevivalxCollectionView/RevivalxCollectionView/SwiftyJSON.swift:443:24: 'NSString?' is not convertible to 'String?'
```

Code

```
public func rawString(encoding: UInt = NSUTF8StringEncoding, options opt: NSJSONWritingOptions = .PrettyPrinted) -> String? {
        switch self.type {
        case .Array, .Dictionary:
            if let data = self.rawData(options: opt) {
                return NSString(data: data, encoding: encoding) //error message here
            } else {
                return nil
            }
        case .String:
            return (self.object as! String)
        case .Number:
            return (self.object as! NSNumber).stringValue
        case .Bool:
            return (self.object as! Bool).description
        case .Null:
            return "null"
        default:
            return nil
        }
    }

```

**Comment by Enalmada** [comment]
Just did my first hello world project on iOS and SwiftlyJSON and couldn't get anything to work.  Seems like SwiftlyJSON master doesn't yet work with Swift 1.2...
http://iphonedev.tv/blog/2015/2/9/swift-12-fixes-and-breaks-a-few-things-you-should-be-excited

Following those directions I added "as? String" and it worked...
```
return NSString(data: data, encoding: encoding) as? String
```

**Comment by josch1985** [comment]
I got this error too in xcode 6.3.1 :(

**Comment by datayeah** [comment]
yeah, nothing works since this update. 90+ errors on the swiftyjson lib. thanks, apple.

**Comment by aks0020** [comment]
I think this is fixed this is the new line:
 `return NSString(data: data, encoding: encoding) as? String`

**Comment by zjorge** [comment]
That's right aks0020, we need to downcast (optionally) to String.  @datayeah all those errors are the same issue.  Take a look at this: https://www.murage.ca/downcasting-in-swift-1-2-with-as-exclamation/ I fixed adding "?" to optionally convert in all those cases where there was an error.  Not sure if I had to use ? or ! though, but it is working now.

**Comment by FaizanKhanani** [comment]
@aks0020    : thanks man it works
