### ISSUE TITLE
Support JSON initialization from json string

### ISSUE THREAD

**Issue by qixotic** [SwiftyJSON/SwiftyJSON#226]
Would you be opposed to a simple convenience initializer that inits from a json string, e.g.:

    // ex. usage:
    // let json = JSON(string: "{\"foo\": \"bar\"}")
    public init(string: String) {
        if let data = string.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false) {
            self.init(data: data)
        } else {
            self.init(NSNull())
        }
    }

**Comment by qixotic** [comment]
Ah, just noticed https://github.com/SwiftyJSON/SwiftyJSON/pull/31, although there's no mention of initialization from a json string in the README, and what I've written is a simpler change. What do you think? Encourage explicit string to NSData conversion by calling it out in the README still?

**Comment by tangplin** [comment]
f75736d83fb054ac1bef62388823ebe28ab80a6e
