### ISSUE TITLE
Mixing order

### ISSUE THREAD

**Issue by emrahu** [SwiftyJSON/SwiftyJSON#227]
SwiftyJSON mixes the order of dictionary items. Below is a JSON data example before and after SwiftyJSON

This is the value I get from my API, and print it in the console. Dates are ordered
```swift
{
    2015-04-01: {
          total: "64.54",
    },
    2015-04-02: {
          total: "58.25",
    },
    2015-04-03: {
          total: "72.94",
    }
}
```

After I use JSON(data!) and print it, I see the dates are mixed up. Why is this happening, and how do I fix this?
```swift
 {
    2015-04-03: {
          total: "72.94",
    },
    2015-04-01: {
          total: "64.54",
    },
    2015-04-02: {
          total: "58.25",
    }
}
```

**Comment by petershaw** [comment]
I fieled this a time ago. Closed by: directries does not have an order. Well actually that is true, there is no order in the specs but is is very annoying. In various cases we need an order! Think about unit tests and thing about an editor... The order is absolutely mandetory. I hope someone can bring up an order-preserve option to this wonderful lib.

**Comment by emrahu** [comment]
I am generating a chart and dates order in the above example must correspond to days in a month. If order of dates are mixed up my chart displays wrong data. There are cases we need to preserve the order of dictionary items.

**Comment by lizhuoli1126** [comment]
Hey..Is there an order in Dictionary or NSDictionary?..Maybe you should try to keep order by any other ways.
But to be honest. SwiftyJSON is awesome!!! How can I star it twice?

**Comment by petershaw** [comment]
Full ack, but we have to solve the order issue somehow. Pls any suggestions.

**Comment by yasuoza** [comment]
This is not a SwiftyJSON issue, is the design of JSON.

 JSON definition says:

> An object is an unordered set of name/value pairs.
http://www.json.org/

And the order issue is also reported at SO http://stackoverflow.com/questions/15125562/keeping-the-order-of-nsdictionary-keys-when-converted-to-nsdata-with-nsjsonseri.

My suggestion is that make an ordered array of date string keys. Then loop the `totals` dictionary using the keys. Or change the API to return like:

```json
{ "totals": [
    {
      "date": "2015-04-01",
      "total": "123"
    },
    {
      "date": "2015-04-02",
      "total": "456"
    }
 ]
}
```
