### ISSUE TITLE
Is  my code's problem? =。= 

### ISSUE THREAD

**Issue by q462127821** [SwiftyJSON/SwiftyJSON#232]
![93cbdaaf-ce2c-4f40-916c-f4af607ee8e7](https://cloud.githubusercontent.com/assets/8529909/7697207/d895eb84-fe37-11e4-99fb-19921d6b36fe.png)

Is  my code's problem? =。=

**Comment by q462127821** [comment]
dict["value"].dictionaryValue   return  a  not  optional  value,    but  why xcode tips me to  add the “!”, and show  the  value is optional..

**Comment by zhigang1992** [comment]
Is this issue still exist?

**Comment by zhigang1992** [comment]
Seems to be a really interesting issue

**Comment by lingoer** [comment]
The ```dict["value"].dictionaryValue``` do return a none optional value,
It's the second subscription:```valueDict["display"] ``` that produce an optional value.
<img width="582" alt="screen shot 2015-12-04 at 2 57 09 pm" src="https://cloud.githubusercontent.com/assets/3095758/11583696/a022f178-9a97-11e5-8426-c2f6425cc91f.png">
you should directly subscription like ``` dict["value"]["display"] ``` to access the value wrapped in a JSON
