### ISSUE TITLE
JSON from string?

### ISSUE THREAD

**Issue by katopz** [SwiftyJSON/SwiftyJSON#234]
How to parse from string? e.g.
```
"{\n  \"foo\" : \"bar\"\n}"
```
Thanks

**Comment by katopz** [comment]
AFAIK
```swift
let string = "{\n  \"foo\" : \"bar\"\n}"
var json = JSON(data:string.dataUsingEncoding(NSUTF8StringEncoding)!)
```
Anyone know shorter one? Or maybe we need to promote shorter function if it not exist?

**Comment by SamDavies** [comment]
I was stuck for days trying to figure out why my json coming from a django app and Alamofire would not parse.

JSON(data:string.dataUsingEncoding(NSUTF8StringEncoding)!) 

This solved my problem.

**Comment by KiraPerhaps** [comment]
In the old version,i used the following way to solve this:
let jsonData = messageString.dataUsingEncoding(NSUTF8StringEncoding)
let json = JSONValue(jsonData)

Anyway,it's not a perfect solution.

**Comment by vinod1988** [comment]
Please add some shorter function.
let string = "{\n  \"foo\" : \"bar\"\n}"
var json = JSON(data:string.dataUsingEncoding(NSUTF8StringEncoding)!)

**Comment by aksswami** [comment]
There is already parse function for this.
```swift
let string = "{\n  \"foo\" : \"bar\"\n}"
var json = JSON.parse(string)
```

I hope we can close this issue now.

**Comment by katopz** [comment]
@aksswami cool thanks
