### ISSUE TITLE
Can not build after installing with Pod

### ISSUE THREAD

**Issue by justdan0227** [SwiftyJSON/SwiftyJSON#235]
I have a working Hello JSON project working and added 
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'MyJSONProject' do
  pod "SwiftyJSON", ">= 2.2" 

end

target 'MyJSONProjectTests' do

end

and get:
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]

**Comment by tangplin** [comment]
Podfile
```ruby
platform :ios, '8.0'
use_frameworks!

target 'MyApp' do
    pod 'SwiftyJSON', '~> 2.2.0'
end
```
Update the `Cocoapods`
```bash
sudo gem update
```
Update the `spec`
```
pod repo update
```
Install
```
pod install
```

**Comment by justdan0227** [comment]
Sorry this was an issue back in May.  I fixed it about a week after that and forgot to update this.  Thank you for the reply
