### ISSUE TITLE
Subscript is slow

### ISSUE THREAD

**Issue by rishimukherjee** [SwiftyJSON/SwiftyJSON#241]
The json subscript is very slow. My application is huge and uses a lot of swiftyjson. According to instruments, subscipting in Swiftyjson is taking the longest time. What aproach should I take to make it faster?

**Comment by arm0nic** [comment]
Right now I am experiencing similar problems. What I do is once the JSON response is downloaded I translate (map) every needed key value pair and save it (as variable or using Core Data). This way SwiftyJSON only gets called once.

**Comment by rishimukherjee** [comment]
Yeah, I am thinking of converting each response to a static class.

**Comment by Gerst20051** [comment]
:+1:

**Comment by liuweicode** [comment]
unfortunately, I have the same problem, did you solve the problem?

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
