### ISSUE TITLE
Any plan to update to Xcode 7 with latest Swift syntax? 

### ISSUE THREAD

**Issue by coolgeng** [SwiftyJSON/SwiftyJSON#247]
When I switch to Xcode 7-beta, it shows some suggestion to convert my current project to Latest Swift Syntax. 

Also, I see there are a lot Syntax change in the new version like this below: 
Before conversion
    private subscript(#index: Int) -> JSON { 
After conversion
    private subscript(index: Int) -> JSON {

**Comment by coolgeng** [comment]
![pasted_image_at_2015_06_09_11_20_am](https://cloud.githubusercontent.com/assets/345397/8066523/f262a35c-0e9c-11e5-98f1-fe0f0568516f.png)

**Comment by kamoljan** [comment]
+1

**Comment by yuhua-chen** [comment]
+1

**Comment by Kaspik** [comment]
+1

**Comment by dmauro** [comment]
+1

**Comment by tangplin** [comment]
try xcode7 branch

**Comment by halgatewood** [comment]
Worked for me with one warning: stringByAddingPercentEscapesUsingEncoding' was deprecated in Apple watchOS 2.0: Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.

**Comment by coolgeng** [comment]
@tangplin Any plan to merge back to mater? Xcode7 branch works fine.

**Comment by gaming-hacker** [comment]
with latest Xcode beta3, there are many errors.

**Comment by Nelyus** [comment]
@coolgeng I guess when Xcode7 is no longer in beta

**Comment by gaming-hacker** [comment]
@halgatewood did fix the warning or ignore it?

**Comment by tangplin** [comment]
branch Xcode7，try it！

发自我的 iPhone

**Comment by mikewalkerjr** [comment]
anyway to use cocoapods with Xcode 7 branch? Or we have to manually put the files in the project?

**Comment by tangplin** [comment]
I can't download beat3 yet in China!

发自我的 iPhone

**Comment by tangplin** [comment]
This is just in beta. Don't use beta xcode Formal Environment！

**Comment by tangplin** [comment]
If Xcode 7 do release ！

发自我的 iPhone

**Comment by halgatewood** [comment]
@gaming-hacker that cleared up the warnings for me. Thanks!

**Comment by gaming-hacker** [comment]
has anyone gotten this to run with Xcode 7beta3?

i have a simple file for testing
{
  "scaleFactorDB": "3.0",
  "offsetDB": "0.0",
  "diameter": "100.0",
  "font-size": "7",
  "font-color": "#ffcc33",
  "sun-color": "#ff9900",
  "edge-color": "#ff0000",
  "line-color": "#ffdb01",
  "filename": "Huck_TV_sunview_data.json"
}

then use

    let jsonData = NSData(contentsOfFile: filePath)!
    print(jsonData)
<7b0a2020 22736361 6c654661 63746f72 4442223a 2022332e 30222c0a 2020226f 66667365 74444222 3a202230 2e30222c 0a202022 6469616d 65746572 223a2022 3130302e 30222c0a 20202266 6f6e742d 73697a65 223a2022 37222c0a 20202266 6f6e742d 636f6c6f 72223a20 22236666 63633333 222c0a20 20227375 6e2d636f 6c6f7222 3a202223 66663939 3030222c 0a202022 65646765 2d636f6c 6f72223a 20222366 66303030 30222c0a 2020226c 696e652d 636f6c6f 72223a20 22236666 64623031 222c0a20 20226669 6c656e61 6d65223a 20224875 636b5f54 565f7375 6e766965 775f6461 74612e6a 736f6e22 0a7d>

    let json = JSON(data: jsonData)
    print(json)
unknown

**Comment by gaming-hacker** [comment]
i tested my fix and it works well for my data

**Comment by seiyamaeda** [comment]
+1

**Comment by samodrole** [comment]
+1

**Comment by jigneshsheth** [comment]
+1

**Comment by zhigang1992** [comment]
It's done

:beers:

**Comment by coolgeng** [comment]
Cool !!!

**Comment by kamoljan** [comment]
Thank you!
