### ISSUE TITLE
Can not build SwiftyJSON with Carthage

### ISSUE THREAD

**Issue by bigface** [SwiftyJSON/SwiftyJSON#248]
I have a cartfile as 

github "Alamofire/Alamofire"
github "SwiftyJSON/SwiftyJSON" >= 2.2.0

The console output is as follows:

*** Fetching SwiftyJSON
*** Fetching Alamofire
*** Checking out Alamofire at "1.2.2"
*** Checking out SwiftyJSON at "2.2.0"
*** xcodebuild output can be found in /var/folders/jp/6yvbpm056sbd17twhbx6t7_00000gn/T/carthage-xcodebuild.q56nwp.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace

As you can see, the Alamofire has been compiled but the there is no information about SwiftyJSON. In the carthage/checkout folder, both alamofire and swiftyJSON are there. However, in the carthage/build folder, only Alamofire is there while swiftyJSON is missing.

The log file is as follows:

Build settings from command line:
    SDKROOT = iphonesimulator8.3

=== BUILD TARGET Alamofire iOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/peter/Library/Developer/Xcode/DerivedData/Alamofire-hetrsqzpxgymnjgjdhegwmzqherm/Build/Intermediates/Alamofire.build/all-product-headers.yaml

=== BUILD TARGET Alamofire iOS Tests OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos8.3

=== BUILD TARGET Alamofire iOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/peter/Library/Developer/Xcode/DerivedData/Alamofire-hetrsqzpxgymnjgjdhegwmzqherm/Build/Intermediates/Alamofire.build/all-product-headers.yaml

=== BUILD TARGET Alamofire iOS Tests OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

=== BUILD TARGET Alamofire OSX OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/peter/Library/Developer/Xcode/DerivedData/Alamofire-hetrsqzpxgymnjgjdhegwmzqherm/Build/Intermediates/Alamofire.build/all-product-headers.yaml

=== BUILD TARGET Alamofire OSX Tests OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

**Comment by julien-c** [comment]
Same issue here.

**Comment by mcb** [comment]
:+1:  Same here.

**Comment by charlyliu** [comment]
same here

**Comment by PatrykKaczmarek** [comment]
SwiftyJSON doesn't support Carthage right know. For more please read: https://github.com/Carthage/Carthage/issues/532.

Here is fork to use before PR will be merged: https://github.com/Thomvis/SwiftyJSON

PR fixing this issue is in the queue: https://github.com/SwiftyJSON/SwiftyJSON/pull/244

**Comment by alec-c4** [comment]
+1

**Comment by JerryNil** [comment]
same issue here

**Comment by phyllipe** [comment]
same issue for me

**Comment by Pym** [comment]
Just put the `Example.xcodeproj` file from the `Carthage/Checkouts/SwiftyJSON/` directory into a new subdirectory and you'll be fine. We just have to wait for someone to merge the PR #244 :smile:

**Comment by liaolj** [comment]
same issue here

**Comment by liaolj** [comment]
It's ok , thanks to Pym
