### ISSUE TITLE
Bug in referencing nested indices with same name

### ISSUE THREAD

**Issue by peteclark3** [SwiftyJSON/SwiftyJSON#249]
If we take the following json:
```
{
    "past": {
        "result": [
            {
                "foo": 1,
                "bar": 2
            }
        ]
    },
    "present": {
        "result": []
    },
    "future": {
        "result": []
    }
}
```

.. and I try to reference each past, present, future's child "result" as follows:
```
let jsonResponse = JSON(data)    // data = the json above

presentEvents = jsonResponse["present", "result"].array!
pastEvents = jsonResponse["past", "result"].array!    
futureEvents = jsonResponse["future", "result"].array!    
```
or even..
```
presentEvents = jsonResponse["present"]["result"].array!
pastEvents = jsonResponse["past"]["result"].array!    
futureEvents = jsonResponse["future"]["result"].array!    
```

with the variables defined and initialized as follows:
```
var pastEvents : Array<JSON> = []
var presentEvents : Array<JSON> = []
var futureEvents : Array<JSON> = []
```

... it turns out that *every* array (pastEvents, presentEvents, futureEvents) contains an array of one object {foo:1, bar:2}.  I expect just pastEvents to contain the array of one object {foo:1, bar:2} and the others to be empty arrays, but when I execute this code, all three of the variables contain an array of one object {foo:1, bar:2}

Could this be a result of the word "result" being common to each of these "subJsons" ?  Or does the problem lie between my keyboard and chair? :)

**Comment by nazariyg** [comment]
Cannot confirm. Works as expected. Here's the testing code:

        let jsonString = "{ \"past\": { \"result\": [ { \"foo\": 1, \"bar\": 2 } ] }, \"present\": { \"result\": [] }, \"future\": { \"result\": [] } }"
        let dataFromString = jsonString.dataUsingEncoding(NSUTF8StringEncoding)!
        let jsonResponse = JSON(data: dataFromString)

        var pastEvents : Array<JSON> = []
        var presentEvents : Array<JSON> = []
        var futureEvents : Array<JSON> = []
        presentEvents = jsonResponse["present", "result"].array!
        pastEvents = jsonResponse["past", "result"].array!
        futureEvents = jsonResponse["future", "result"].array!
        println(pastEvents)
        println(presentEvents)
        println(futureEvents)

**Comment by zhigang1992** [comment]
feel free to reopen it if needed
