### ISSUE TITLE
String extraction unexpected result

### ISSUE THREAD

**Issue by ndmeiri** [SwiftyJSON/SwiftyJSON#251]
Is this a problem with SwiftyJSON or my implementation?

In my app I'm trying to extract the "comments" field of the following subJson.

```
{"operation_id":"12648",
"dataset_id":"0",
"date":"0000-00-00 00:00:00",
"operation_year":"2015",
"operation_type":"",
"equipment_id":"2",
"tractor_id":"1",
"description":"",
"number_of_passes":"1",
"number_of_tractor_operators":"1",
"number_of_workers":"1",
"comments":"this is a test operation",
"tractor_operator_name":""}
```

Here's my code for that task:
```Swift
self.comments = subJson["comments"].stringValue
```
But `self.comments` is always an empty string.
I think I'm correctly following the example in the SwiftyJSON readme. Any help with this would be greatly appreciated. Thank you.

**Comment by dduan** [comment]
@ndmeiri it'd be helpful if you show how your `subJson` variable came to be.  I couldn't reproduce the issue you describe in storyboard:

![screen shot 2015-06-17 at 11 05 30 am](https://cloud.githubusercontent.com/assets/75067/8214834/d5a7a98e-14e0-11e5-8133-ed6f02989be3.png)

**Comment by ndmeiri** [comment]
First, I get a JSON response from an Alamofire POST request. Then I break that JSON into parts and pass each part to an initializer for my `Operation` class.
```Swift

Alamofire.request(.POST, URLString, parameters: parameters, encoding: .JSON).responseJSON { (_, _, possibleJsonObject, error) in
    
    if let jsonObject: AnyObject = possibleJsonObject {
        let json = JSON(jsonObject)
        var operations: [Operation] = []
        
        // parse out each subJson into an Operation
        for (index: String, subJson: JSON) in json {
            operations.append(Operation(json: subJson))
        }
        
        completion?(operations: operations, error: error)
    } else {
        println(error)
    }
}
```

This is what that initializer looks like.
```Swift

convenience init(json: JSON) {
    self.init()
    
    println(json)
    self.identifier = json["operation_id"].uIntValue
    
    self.startDate = NSDate(timeIntervalSince1970: json["startTimestamp"].doubleValue)
    self.seasonalYear = json["year"].intValue
    
    self.comments = json["comments"].stringValue
    //println(self.comments)
    println(json["number_of_workers"].intValue)
    println(json["number_of_workers"].stringValue)
}
```

Please let me know if any other information would be helpful.

**Comment by zhigang1992** [comment]
You should do this:

        for (index: String, subJson: JSON) in json.arrayValue {
            operations.append(Operation(json: subJson))
        }

Sry 4 late reply, plz feel free to reopen it if needed
