### ISSUE TITLE
Removing within JSON, an example?

### ISSUE THREAD

**Issue by nazariyg** [SwiftyJSON/SwiftyJSON#255]
So how do you go about removing something from JSON, for instance a key from a dictionary?

**Comment by nazariyg** [comment]
This is what I've come up with by this point:

    var d = json.object as! Dictionary<String, AnyObject>
    d.removeValueForKey("key")
    json.object = d

Is there a shorter way?

**Comment by yasuoza** [comment]
This is shorter.

```swift
var json = JSON(["hello": "world", "goodbye": "yesterday"])
json.dictionaryObject?.removeValueForKey("goodbye")
println(json) // {"hello":"world"}
```

**Comment by tangplin** [comment]
```swift
var json = JSON(["hello": "world", "goodbye": "yesterday"])
json.["goodbye"] = nil  //JSON(["hello": "world", "goodbye": NSNull()])
```
