### ISSUE TITLE
Cannot invoke `XCTAssertNotNil` with JSON

### ISSUE THREAD

**Issue by Buju77** [SwiftyJSON/SwiftyJSON#256]
Maybe I didn't get it correctly, but here is my issue:
I'm unit testing if my custom model --> json generator works correctly. So I'm checking the json dictionary directly afterwards. And for some properties I just want to make sure that a json attribute was serialized and should not be empty. I don't care about the value it contains. So my test code looks something like this:

    
    func testVerifyOld(dict: NSDictionary) {
        XCTAssertNotNil(dict["id"]) // works fine before
    }
    
    func testVerifyNew(dict: JSON) {
        XCTAssertNotNil(dict["id"]) // Error: Cannot invoke 'XCTAssertNotNil' with an argument list of type '(JSON)'
    }

now I need to change it to the following. which is a bit more to write than the traditional `NSDictionary` style.

    func testVerifyCorrectNew(dict: JSON) {
        XCTAssert(!dict["id"].stringValue.isEmpty)

        XCTAssertGreaterThan(count(dict["id"].stringValue), 5, "must be filled with something")
    }

Is there a better way in `SwiftyJSON` to check for `NotNil` and `NotEmpty`?

**Comment by BasThomas** [comment]
That's a bug in Swift; you can't check structs for nil. Use these methods instead:

```swift
/*
	Workaround extension for asserting nil on a struct.
	See http://stackoverflow.com/questions/26684207/how-can-one-use-xctassertnil-with-optional-structs for further reference.
*/
extension XCTest {
	
	public func XCTAssertNil<T>(@autoclosure expression: () -> T?, _ message: String = "",
		file: String = __FILE__, line: UInt = __LINE__) {
			
		XCTAssert(expression() == nil, message, file: file, line: line);
	}
	
	public func XCTAssertNotNil<T>(@autoclosure expression: () -> T?, _ message: String = "",
		file: String = __FILE__, line: UInt = __LINE__) {
			
			XCTAssert(expression() != nil, message, file: file, line: line);
	}
}
```

**Comment by zhigang1992** [comment]
Try
```
XCTAssertNotNil(dict["id"].string)
```

Feel free to reopen this if you have more questions
