### ISSUE TITLE
Support for Relation Mapping to Model Object / Data Model Object

### ISSUE THREAD

**Issue by milankamilya** [SwiftyJSON/SwiftyJSON#262]
Thanks for such wonderful library for swift in a short time. 

As we have seen mapping between JSON data to Data Model Object in RestKit & JSONModel, I couldn't find such feature in SwiftyJSON. Using SwiftyJSON, it is a time consuming task to parse JSON. It will be better if there is any such mapping feature. 

Thanks again.

**Comment by ammoqq** [comment]
+1000000000
Will there be any support to mapping ?

**Comment by milankamilya** [comment]
It will be better if you add it.

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
