### ISSUE TITLE
xcode update

### ISSUE THREAD

**Issue by sedwards21** [SwiftyJSON/SwiftyJSON#266]
Xcode update ton of errors

**Comment by SimonTheEngineer** [comment]
+1

**Comment by dividedpudding** [comment]
+1

**Comment by ded** [comment]
It looks like #274 is a duplicate of this. But I'll add my +1. As mentioned earlier, I'd love to help but have no clue where to start since it's literally throwing hundreds of errors when attempting to load in this library

**Comment by tangplin** [comment]
Which Xcode version?

**Comment by SimonTheEngineer** [comment]
XCode 7 beta for me

**Comment by zhigang1992** [comment]
It was because of Xcode version upgrade,

Right now, the master is using Xcode7.

If you have to use Xcode6 and Swift1.2, tryout version 2.2.1 or below.

:beers:
