### ISSUE TITLE
GitHub page example improvements

### ISSUE THREAD

**Issue by anohren** [SwiftyJSON/SwiftyJSON#268]
This example isn't really conveying that line 2, 3 and 5 have the same effect:

```swift
var json: JSON =  ["name": "Jack", "age": 25, "list": ["a", "b", "c", ["what": "this"]]]
json["list"][3]["what"] = "that"
json["list",3,"what"] = "that"
let path = ["list",3,"what"]
json[path] = "that"
```

...since previous examples already make clear that incorrect assignments will fail silently.
A more clear way of writing would be:

```swift
var json: JSON =  ["name": "Jack", "age": 25, "list": ["a", "b", "c", ["what": "this"]]]
json["list"][3]["what"] // evaluates to "this"
json["list",3,"what"] // evaluates to "this"
let path = ["list",3,"what"]
json[path] // evaluates to "this"
```

**Comment by zhigang1992** [comment]
This was actually a example for successful assignment.
Not a evaluation.

:beers: 

Feel free to reopen this issue of you have any other questions.
