### ISSUE TITLE
  'AnyObject' is not convertible to 'String'; did you mean to use 'as!' to force downcast?

### ISSUE THREAD

**Issue by afixibiranchi** [SwiftyJSON/SwiftyJSON#271]
![screen shot 2015-07-13 at 3 59 59 pm](https://cloud.githubusercontent.com/assets/191425/8645250/479024d0-2978-11e5-8a03-8cf1010caba4.png)
I am using 6.3.2 and still getting the error.

**Comment by yasuoza** [comment]
For Xcode >= 6.3, use current latest release https://github.com/SwiftyJSON/SwiftyJSON/releases/tag/2.2.0.

**Comment by amitmahbubani** [comment]
Issue exists at Xcode v6.4

**Comment by FezVrasta** [comment]
6.4 here and I get those 40 errors as well.

**Comment by yasuoza** [comment]
Hey guys, are you using 2.2.0?


Line 173 in above screen shot (now it's line 184) looks different with latest release version 2.2.0. 

https://github.com/SwiftyJSON/SwiftyJSON/blob/2.2.0/Source/SwiftyJSON.swift#L184

**Comment by zhigang1992** [comment]
This issue should have been resolved.

If you're using Xcode7, please use version 2.3.0 and up

If you're using Xcode6, please stay on version 2.2.1
