### ISSUE TITLE
can it support below ios8.0 ？

### ISSUE THREAD

**Issue by xueselangman91** [SwiftyJSON/SwiftyJSON#274]

**Comment by ded** [comment]
+1
I loaded this project into my iOS 8.3 project and it threw hundreds of errors.

Thus... I'm not really sure what to do about it since I have no prior development experience with iOS  <= 7 otherwise I would love to help

**Comment by xueselangman91** [comment]
it is nothing ,what  is the  matter,have you resolved it?

**Comment by iamtomcat** [comment]
It says you can drag in the swifty.json file for iOS 7. Never tried this as the apps I work on only support 8 and above atm. But I don't see what it wouldn't work. Also iOS7 is the minimum version to use swift.

**Comment by zhigang1992** [comment]
It was because of Xcode version upgrade,

Right now, the master is using Xcode7.

If you have to use Xcode6 and Swift1.2, tryout version 2.2.1 or below.

:beers:
