### ISSUE TITLE
Carthage with XCode7 beta 3 skips building SwiftyJSON altogether

### ISSUE THREAD

**Issue by rainypixels** [SwiftyJSON/SwiftyJSON#276]
My `Cartfile` has the following:

    github "SwiftyJSON/SwiftyJSON" "xcode7"

This was working great until I upgraded to XCode7 beta 3. I got an error that Swifty had been built using an older version of the compiler (Alamofire was suffering from the same error). So I deleted SwiftyJSON from carthage checkout and build folders, and ran `carthage update` again. Alamofire re-fetched and re-built, but SwiftyJSON is being skipped altogether. No output regarding SwiftyJSON in the carthage log. 

I'm not sure if this is a SwiftyJSON issue or a carthage issue. I thought to check here first because my other frameworks did update.

Any ideas? Thanks!

**Comment by Donwangugi** [comment]
I am having the same issue.

**Comment by carlosefonseca** [comment]
Try renaming `Example.xcodeproj` to `zExample.xcodeproj` and run `carthage build`.

**Comment by rainypixels** [comment]
@carlosefonseca Worked like a charm. Thanks much!

I'll leave this issue open to be triaged by @tangplin, though.
