### ISSUE TITLE
An integer is parsed as a `String` and getting its `numberValue` returns a `Double`, which crashes related code

### ISSUE THREAD

**Issue by duci9y** [SwiftyJSON/SwiftyJSON#277]
JSON of the form:

    "code": 301

is parsed as a `String`, when it should be parsed as an `Int`. Getting its `numberValue` returns an `NSNumber` containing a `Double`, which crashes some code.

**Comment by tangplin** [comment]
@duci9y you can try ```json["code"].intValue```
