### ISSUE TITLE
Crashes my app a ton

### ISSUE THREAD

**Issue by aTylerRice** [SwiftyJSON/SwiftyJSON#279]
Swifty Json seems to be the cause of about 90% of the crashes in my app. All from this line of code let jsonDict = JSON(data: data, options: NSJSONReadingOptions.AllowFragments, error: nil)

crashlytics doesn't give me much info about how it crashed just that its always this line of code.

Is there someway I can put a try catch around this so it won't crash the entire app?

**Comment by ephemer** [comment]
@aTylerRice might be worth passing an error pointer into the error argument and printing the result in your debugging

**Comment by zhigang1992** [comment]
Also can you provide a sample of you json response?

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
