### ISSUE TITLE
Using ISO-8859-1 instead of UTF-8

### ISSUE THREAD

**Issue by FredLoh** [SwiftyJSON/SwiftyJSON#280]
Hello, is there any way for me to quickly change SwiftyJSON so that it will be able to parse using ISO-8859-1 instead of UTF-8?

Thanks!

**Comment by Rupert-RR** [comment]
With no prior knowledge of SwiftyJSON (I stumbled on this by chance), if you're talking about parsing a JSON string (in 8859-1 encoding) into model objects, then it should be impossible — JSON must be Unicode text (http://www.ietf.org/rfc/rfc4627.txt) so an 8859-1 string cannot be valid JSON.

**Comment by zhigang1992** [comment]
JSON Parsing in `SwiftyJSON` are actually done by `NSJSONSerialization`.

And NSJSONSerialization supports

> The data must be in one of the 5 supported encodings listed in the JSON specification: UTF-8, UTF-16LE, UTF-16BE, UTF-32LE, UTF-32BE. The data may or may not have a BOM. The most efficient encoding to use for parsing is UTF-8, so if you have a choice in encoding the data passed to this method, use UTF-8. 

https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSJSONSerialization_Class/#//apple_ref/occ/clm/NSJSONSerialization/JSONObjectWithData:options:error:
