### ISSUE TITLE
JSON created from an Alamofire response is immutable?

### ISSUE THREAD

**Issue by DevinShelly** [SwiftyJSON/SwiftyJSON#284]
I'm using SwiftyJSON to populate a table view with data pulled from a web api. So I set up an instance variable to hold my JSON:

``` swift
var tableData:JSON!
{
    didSet
    {
        tableView.reloadData()
    }
}
```

Then I make a request somewhere to update the data, and the table gets reloaded:

``` swift
request(method, url, parameters: parameters, encoding: ParameterEncoding.URL).responseJSON(options: NSJSONReadingOptions.AllowFragments) { (request, response, json, error) -> Void in
            self.tableData = JSON(json!)
        }
```

Some of my cells, I want my user to be able the update the underlying data model. So for instance, I have some text fields embedded in a cell, and then using a delegate method, I want to update the JSON, like so:

``` swift
func textFieldDidEndEditing(textField: UITextField)
{
    let key = "anExampleKey"
    tableData[key] = JSON(textField.text)
    println(tableData[key]) // the original value, not textField.text
}
```

This doesn't work, the tableData remains unchanged. However, if I create a JSON object from a dictionary, that does get updated:

``` swift
func textFieldDidEndEditing(textField: UITextField)
{
    let key = "anExampleKey"
    var json = JSON([key:tableData[key].stringValue])
    tableData[key] = JSON(textField.text)
    json[key] = JSON(textField.text)
    println(tableData[key]) // the original value, not textField.text
    println(json[key]) // textField.text
}
```

So it appears that this is a problem limited to SwiftyJSON objects created via the responseJSON in Alamofire. I need to keep the underlying data model up to date based on the changes my user has made. If the cell scrolls off screen, that text field might have its text reset when the table view reuses its parent cell for example. Or if my user decides to save his changes and upload them to the server, I need to have the current values reflected in the data model, not what they were when he last made a request. Any idea why this isn't working and how to achieve it?

**Comment by DevinShelly** [comment]
OK, I've figured it out. It has something to do with implicitly unwrapping a JSON value. If I store it in an optional value or a non-optional variable, I can update it just fine. It's only an implicitly unwrapped variable that refuses to update. I'm not sure why this is, but I threw together the following storyboard to demonstrate it:

```swift
var optionalJSON:JSON?
optionalJSON = JSON(["Test":"This is one"])
optionalJSON?["Test"] = "This is another one"
optionalJSON?["Test"].string /* This is another one */
optionalJSON!["Test"] = "This is another one yet"
optionalJSON!["Test"].string /* This is another one yet */
```

**Comment by ldiqual** [comment]
@DevinShelly I was able to reproduce the issue and will followup in https://github.com/SwiftyJSON/SwiftyJSON/issues/412. Closing this as a duplicate. Thanks!
