### ISSUE TITLE
e-Notation unsupported?

### ISSUE THREAD

**Issue by marsman12019** [SwiftyJSON/SwiftyJSON#285]
When doing:

    if let dataFromString = jsonString.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false) {
	
	    var json = JSON(data: dataFromString)
	
	    var modelsArray = json["models"].arrayValue
    }

If jsonString is this:

    var jsonString = "{ \"models\" : [ { \"modelName\": \"model\", \"set1\": [ 1, 2, 3, 4, 5 ], \"set2\": [ 6, 7, 8, 9, 10 ] }] }"

modelsArray is this:

    {["models": […]], (Enum Value), nil}

If jsonString is this:

    var jsonString = "{ \"models\" : [ { \"modelName\": \"model\", \"set1\": [ 1.797693134862316e+308, 2, 3, 4, 5 ], \"set2\": [ 6, 7, 8, 9, 10 ] }] }"

modelsArray is this:

    {<null>, (Enum Value), nil}

**Comment by zhigang1992** [comment]
This part is actually handled by system `NSJSONSerialziation` class, seems like currently it doesn't actually support number with e format

**Comment by zhigang1992** [comment]
Since it's not in the `http://www.json.org/` standard. And IMHO, it's should be part of JSON Parser's job, instead SwiftyJSON.
