### ISSUE TITLE
Use of undeclared type 'JSON'

### ISSUE THREAD

**Issue by datomnurdin** [SwiftyJSON/SwiftyJSON#286]
Hi, I got this error message even I already import SwitfyJSON

```
Use of undeclared type 'JSON'
```

My code

```
var datas: [JSON] = []
```

Please advice. Thank you.

**Comment by murrayds** [comment]
@datomnurdin more information is proibably needed.

How have you integrated SwiftyJSON: Cocoapods? Carthage? Copy/paste of files?

**Comment by datomnurdin** [comment]
I'm using via Cocoapods.

**Comment by Devxhkl** [comment]
Use import SwiftyJSON in swift files where you use it.

**Comment by hexadecymalny** [comment]
Hi, did someone found solution? I have the same error via CocoaPods. Thanks

**Comment by hexadecymalny** [comment]
I found related thread with the same error and solution. Maybe it will be helpful.
https://github.com/SwiftyJSON/SwiftyJSON/issues/192

**Comment by zhigang1992** [comment]
It's should be working with the latest version now.

:beers:

**Comment by datomnurdin** [comment]
thanks.

**Comment by blackjack-brim** [comment]
This issue literally just happened to me. I'm using cocoapods and i've linked the framework to my project.
I also added the 'import SwiftyJSON' and I still got  the error Use of undeclared type 'JSON'.
Easiest fix at least for me was to use the fully qualified class name.
Example:
//Give Use of undeclared type 'JSON' error
func toJSON() -> JSON
//Works with no issues
func toJSON() -> SwiftyJSON.JSON

Hope this helps you as well.
