### ISSUE TITLE
Xcode JSON智能提示没有JSON(data:)只有 JSON()

### ISSUE THREAD

**Issue by androidcn** [SwiftyJSON/SwiftyJSON#287]
Xcode JSON智能提示没有JSON(data:)只有 JSON()
直接使用

if let data = NSData(contentsOfURL: url, options: .allZeros, error: nil) {
	let json = JSON(data) //智能提示只有这个 不返回数据
	let json = JSON(data:data) //手动输入参数名 返回正确数据
}

**Comment by tangplin** [comment]
仔细看一下OOP编程中的多态再考虑下你问这个问题是不是有价值。

**Comment by androidcn** [comment]
多态我当然懂,但是初学者要使用,智能提示会有更好的帮助

<img width="330" alt="screen shot 2015-08-02 at 11 19 58 am" src="https://cloud.githubusercontent.com/assets/271715/9024563/b25dd628-3908-11e5-9fb2-a07c43b7eff1.png">

**Comment by tangplin** [comment]
请联系Apple解决Xcode的问题。

发自我的 iPhone
