### ISSUE TITLE
Double or Float Type with 2 decimals.

### ISSUE THREAD

**Issue by hopye** [SwiftyJSON/SwiftyJSON#294]
So,  this is my code .
 
```swift
 var plato_price:Double? = restDict["precio"].doubleValue
                                println(restDict["precio"])
                                println(restDict["precio"].doubleValue)
// insert into model
 var plat = MenuItem(name: plato_nombre!, desc: plato_desc!, price: plato_price!)
```

the thing is im getting 10.0 as  when using the double value which my model expects as Double. when println restDict["precio"] the real value is 10.00

i need to get the two decimal spaces.. the same thing happen's when using floatValue

**Comment by iamtomcat** [comment]
This is correct behaviour. Are you just wanting format the value?

It would look like this:
`String(format: "%.2f", arguments: [10.0])`
