### ISSUE TITLE
Bucketload of bugs 

### ISSUE THREAD

**Issue by mrshortman** [SwiftyJSON/SwiftyJSON#295]
I've got 40 errors in the SwiftyJSON.swift file.
They are all exactly the same:
```
'AnyObject' is not convertible to '[*INSERT DATA TYPE HERE* : AnyObject]'; did you mean to use 'as!' to force downcast?
```
What's going on? Downloaded the file 4 times now, it just refuses to work. Using Xcode 6. 
Thanks, 
Adam

**Comment by yasuoza** [comment]
See #271. Latest SwiftyJSON.swift should solve the issue.

**Comment by zhigang1992** [comment]
This issue should have been resolved.

If you're using Xcode7, please use version 2.3.0 and up

If you're using Xcode6, please stay on version 2.2.1
