### ISSUE TITLE
xcode7 merge into master

### ISSUE THREAD

**Issue by wokandroll** [SwiftyJSON/SwiftyJSON#299]
Hi 

I am just wondering what the likely date is for the xcode7 branch to merged into master. I do not want to release the app with a branch version. 

If there is any way I can help, I will just let me know how.

**Comment by sdduursma** [comment]
+ 1

**Comment by Ekhoo** [comment]
+1

**Comment by bcapps** [comment]
+1 @tangplin

**Comment by shouze** [comment]
:+1:

**Comment by Danappelxx** [comment]
:+1:

**Comment by TadeasKriz** [comment]
:+1:

**Comment by cdmwebs** [comment]
Looks like this has been done (1f38ced11).

**Comment by shouze** [comment]
ok so this issue have to be closed.
