### ISSUE TITLE
NSDate always nil

### ISSUE THREAD

**Issue by Urkman** [SwiftyJSON/SwiftyJSON#303]
Date values are always nil...

When using this:
let json = JSON(item) as JSON

Item looks like this:
dict before json: {
    date = "2015-04-15 12:00:00 +0000";
    details = "bla bla bla";
    id = 363;
    name = "Name";
}

After that date is always nil...

**Comment by zhigang1992** [comment]
Can you paste in the code of how you're getting this date value?

**Comment by zhigang1992** [comment]
Feel free to reopen this if you have any more questions.
