### ISSUE TITLE
Any interest in moving away from NSJSONSerialization?

### ISSUE THREAD

**Issue by lukescott** [SwiftyJSON/SwiftyJSON#304]
Is there any interest in moving away from NSJSONSerialization to a full Swift parser?

**Comment by ephemer** [comment]
@lukescott I am working on exactly that. Have you made any progress yourself? I'm working on efficiently parsing nested data structures (e.g. arrays within arrays within dictionaries)

**Comment by lukescott** [comment]
@ephemer I actually finished a stream tokenizer and parser. It's a company project though, and they haven't decided to open source it yet due to an internal project that's dominating most of our time at the moment. They don't want to release something without the ability to maintain it.

**Comment by ephemer** [comment]
Oh ok, interesting. I pushed a repo last night in pure swift (www.github.com/ephemer/strongly-json) that has about 85% of the parsing functionality I'm after.




It currently doesn't deal with string literals or backspaced tokens yet, for example, but both will be easy to add. I've only been working on it for a couple of days so far.





My aim was to make a pure Swift 2.0 solution (no frameworks) for when the language goes open source. Maybe you and/or the company would be interested in contributing to that project instead?

**Comment by lukescott** [comment]
I had the same goal (Swift only, no Foundation). The parser is already done. It already does string literals, numbers w/ exponents, escape sequences including unicode w/ surrogate pairs.

**Comment by hpux735** [comment]
Incidentally, now that open source swift is out, NSJSONSerialization https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSJSONSerialization.swift was included, but is largely unimplemented.  Would any of your code work there?

**Comment by ephemer** [comment]
Yes, I'm in discussions with the Swift dev group about it already

**Comment by DominicFrei** [comment]
@ephemer Any update on that?

**Comment by ephemer** [comment]
Last I checked it'd been implemented, but not by me
Dominic Frei <notifications@github.com> schrieb am Do., 21. Jan. 2016 um
01:20:

**Comment by ldiqual** [comment]
@lukescott Given that https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSJSONSerialization.swift is now fully implemented in swift and does not perform ObjC bridging, I believe this issue is now fixed. Let me know if I need to reopen.
