### ISSUE TITLE
Swift.indexable no longer available?

### ISSUE THREAD

**Issue by eneko** [SwiftyJSON/SwiftyJSON#305]
Getting this error on Xcode 7:
```
Pods/SwiftyJSON/Source/SwiftyJSON.swift:186:66: No type named 'Indexable' in module 'Swift'
```

This is the piece of code:
```
// MARK: - CollectionType, SequenceType, Indexable
extension JSON : Swift.CollectionType, Swift.SequenceType, Swift.Indexable {
    public typealias Generator = JSONGenerator
```

Thanks

**Comment by rajohns08** [comment]
I just pulled the Xcode7 branch, and I am also seeing this error

**Comment by rajohns08** [comment]
Try updating to Xcode 7 beta5 as [Indexable is very new](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Reference/Swift_Indexable_Protocol/RevisionHistory.html#//apple_ref/doc/uid/TP40016310-CH99-DontLinkElementID_6).

**Comment by eneko** [comment]
Yeah, sorry, my bad. Works fine on beta5.
