### ISSUE TITLE
Added new Tag for Swift 2.0 for cocoa-pods Developers

### ISSUE THREAD

**Issue by mikenolimits** [SwiftyJSON/SwiftyJSON#308]
Hi,

Would it be possible to tag a release for swift 2.0, so that we can add SwiftyJSON as a dependency in our pods?

**Comment by aaronhuisinga** [comment]
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7'

You're able to specify a specific branch in your Podfile.

**Comment by mikenolimits** [comment]
Hi Aaron, 

Yes you're right, that would work fine if you were using the package, but it won't work if you are making a Cocoapod yourself and SwiftyJSON is listed as a dependency.

**Comment by mikenolimits** [comment]
:+1:

**Comment by doguhanokumus** [comment]
with the official release of ios9, now would be a great time for this update

**Comment by mikenolimits** [comment]
Maybe someone has a fork for this?

**Comment by doguhanokumus** [comment]
adding swiftyJSON as a dependency is still not working for swift 2. specifiying branch is not working for dependencies. Is this issue going to be addressed soon or shall we start looking for replacements for swiftyJSON?

**Comment by zhigang1992** [comment]
It's tagged, and released to cocoapods

:beers:
