### ISSUE TITLE
Update to the newest swift version?

### ISSUE THREAD

**Issue by shuuchen** [SwiftyJSON/SwiftyJSON#309]
I have downloaded and installed this library but it cannot compile.
I fixed the errors so that it can compile successfully but the ios simulator cannot run.
Do the authors have any plan to update this library to the newest version of swift?
There are many similar issues on board. It seems that the authors' update is highly appreciated.

**Comment by calosth** [comment]
+1
Same here. Months ago I started a project with this dependence. I'm trying to run today with Swift 2.0 and errors everywhere. I hope will see a new version of SwiftyJSON soon.

**Comment by iamtomcat** [comment]
Are you checking out the "xcode7" branch?

**Comment by calosth** [comment]
@iamtomcat Thanks!

**Comment by iamtomcat** [comment]
No worries man. Just so you're aware most libraries that are built on swift generally have a branch where they update to the latest version of swift.

**Comment by calosth** [comment]
Good to know! Thanks again

**Comment by wokandroll** [comment]
Hi I just wondering when the xocde 7 branch was going to get merged into develop. Since xcode 7 has been seeded

**Comment by mwaterfall** [comment]
Any idea when these changes will make it to master / released to Cocoapods / production ready?

**Comment by borut-t** [comment]
+1

**Comment by cmoulton** [comment]
Looks like the xcode7 branch has been merged in to master. Is there a plan to update the podspec?

**Comment by giacgbj** [comment]
+1

**Comment by craigpearce5** [comment]
@cmoulton Looks like the podspec was updated... atleast the readme.

   Requirements
   iOS 7.0+ / Mac OS X 10.9+
   Xcode 7

**Comment by zhigang1992** [comment]
CocoaPods is updated

:beers:
