### ISSUE TITLE
stringByAddingPercentEscapesUsingEncoding deprecated warning

### ISSUE THREAD

**Issue by mosesoak** [SwiftyJSON/SwiftyJSON#311]
Using the latest XCode 7 beta, I get the following warning in the console even with inhibit_all_warnings! set in the podfile:

'stringByAddingPercentEscapesUsingEncoding' is deprecated: Use stringByAddingPercentEncodingWithAllowedCharacters(_:) instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.

It refers to `SwiftyJSON.swift -> extension JSON -> public var URL -> get -> encodedString_`

**Comment by zhigang1992** [comment]
This issue should have been resolved

Feel free to reopen it if you have further questions.
