### ISSUE TITLE
Subset of JSON?

### ISSUE THREAD

**Issue by dyermd** [SwiftyJSON/SwiftyJSON#312]
Is there a way to got from a JSON object and pull out just a subset of the fields? For example, if this was my JSON blob stored in the JSON object.

```json

{
"data": {
  "id":1,
  "name":"my sample",
  "runs":[
  ]
 }
}
```

And I want to remove the `runs` tag so the new object only contains.

```json

{
"data": {
  "id":1,
  "name":"my sample"
 }
}
```

Any suggestions? I have spent the past 4+ hours trying various things.

**Comment by iamtomcat** [comment]
What exactly are you trying to accomplish? 
Why don't you just not use the property?
If you have access to the server you could just not send it.

**Comment by dyermd** [comment]
I am trying to generate a new JSON object that has a subset of the information. The original API call returns data from multiple models. When I send the PATCH call I just need to send data associated with the specific model I need to PATCH, thus trying to strip out a few things.

**Comment by zhigang1992** [comment]
This should have done it
```swift
let string = "{\"data\": {\"id\":1,\"name\":\"my sample\",\"runs\":[\"Something\"]}}"
var json = JSON(data: string.dataUsingEncoding(NSUTF8StringEncoding)!)
json["data"]["runs"] = nil
print(json["data"])
```

feel free to reopen the issue if you have further questions

:beer:
