### ISSUE TITLE
Build failed after cocoapods SwiftyJSON

### ISSUE THREAD

**Issue by singkorn** [SwiftyJSON/SwiftyJSON#314]
I could build and run iOS project with Xcode 6.4. However, after cocoapds SwiftyJSON and build workspace, I received below failed message.

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

**Comment by rikschennink** [comment]
same here

**Comment by zhigang1992** [comment]
Is the issue still exist?

If so can you create a sample project?

**Comment by rikschennink** [comment]
I opened the wrong cocoapods project file so, no problems here.
