### ISSUE TITLE
Handling quote-wrapped non-string values (ints, etc)

### ISSUE THREAD

**Issue by endash** [SwiftyJSON/SwiftyJSON#316]
I deal with a 3rd party API where every value except for `nil` is wrapped in quotation marks, and thus gets parsed as `.String`. Using the `var int: Int?` in this case will always returns nil. The solution, currently, is to conditionally unwrap the `string` representation, and then pass that to `Int.init?` to finally get an `Int?`. This is ungainly, and probably not too rare a problem, as legacy APIs go.

I propose that `var int: Int?` be modified to handle this case implicitly, by checking for a `.String` and returning the result of passing that value to `Int.init?`. This would properly align the semantics of the code with the data, for the developer, rather than the peculiarities of the original serialization.

(Other types might also merit this treatment, but so far I'm only dealing with `Int`s personally)

I can handle the code changes personally, depending on receptiveness/feedback.

**Comment by iamtomcat** [comment]
For some reason I thought this was the case already. It seems weird that the integer setter assumes that a number will be passed.

**Comment by zhigang1992** [comment]
This should do it

```swift
let j:JSON = ["a":"12"]
j["a"].string.flatMap({Int($0)})
```

:beers:

**Comment by endash** [comment]
@zhigang1992 Yeah, that's the workaround I mentioned in the description. Multiply that by a dozen times and it's not very nice, compared to the intuitive, obvious, and terse `j["a"].int`. The priority, as far as the semantics go, should be developer intention and usefulness.  We're using SwiftyJSON to parse our *data* and not *code*, and it stops just short of that goal by insisting that a string in the source JSON has to be parsed as a `String`, even if I know it is an `Int`. 

The JSON spec may say that `"5"` is a string, but I happen to know differently. I care whether an `Int` can be parsed from it, not whether or not *SwiftyJSON* happens to know that it is an `Int`. Developer knowledge should trump naive type detection.
