### ISSUE TITLE
Issue with SwiftyJSON when parsing JSON with unicode characters

### ISSUE THREAD

**Issue by dudeinthemirror** [SwiftyJSON/SwiftyJSON#318]
http://stackoverflow.com/questions/32322881/issue-with-swiftyjson-when-parsing-json-with-unicode-characters

**Comment by iamtomcat** [comment]
Are you sure? This works for me using your json.

```
import UIKit
import SwiftyJSON
import XCPlayground


let jsonPath = NSBundle.mainBundle().pathForResource("test", ofType: "json")

if let jsonData = NSData(contentsOfFile: jsonPath!) {
  let json = JSON(data: jsonData)
  print(json["count"]) //prints 2
}
```

**Comment by dudeinthemirror** [comment]
Hi Tom, thanks for your reply. So, it works fine when reading from a file, however when retrieving the same data via a REST API (in this case Spree), I get the error.
If you don’t mind please try : http://eastereggs.mysimplestore.com/api/taxonomies/1/taxons

From:  Tom Clark
Reply-To:  SwiftyJSON/SwiftyJSON
Date:  Friday, September 4, 2015 at 3:33 AM
To:  SwiftyJSON/SwiftyJSON
Cc:  dudeinthemirror
Subject:  Re: [SwiftyJSON] Issue with SwiftyJSON when parsing JSON with unicode characters (#318)


Are you sure? This works for me using your json.
import UIKit
import SwiftyJSON
import XCPlayground


let jsonPath = NSBundle.mainBundle().pathForResource("test", ofType: "json")

if let jsonData = NSData(contentsOfFile: jsonPath!) {
  let json = JSON(data: jsonData)
  print(json["count"]) //prints 2
}

**Comment by iamtomcat** [comment]
This is what I get when I use the url. Maybe I'm missing something more specific to what your'e trying to do?
![screen shot 2015-09-04 at 5 15 33 pm](https://cloud.githubusercontent.com/assets/6033483/9688674/978fa094-5328-11e5-984f-3dd963289897.png)

**Comment by dudeinthemirror** [comment]
I am using Alamofire to get the data. So, it looks like there is something funky going on somewhere between getting the json back and parsing. Closing this for now, it's clear it's not a SwiftyJSON issue. Thanks for your help Tom !

**Comment by iamtomcat** [comment]
No worries man. Let me know if you need any more help.
