### ISSUE TITLE
Make release from xcode7 branch

### ISSUE THREAD

**Issue by Danappelxx** [SwiftyJSON/SwiftyJSON#321]
Currently cocoapods has very limited support for [setting a pod spec dependency from a branch](https://github.com/CocoaPods/CocoaPods/issues/922#issuecomment-15771597). This is an issue for my framework because it depends on the Xcode 7 branch of SwiftyJSON, but I can't add it to the podspec due to cocoapods limitations.

This could be fixed in a variety of ways, but the one that I can come up from the top of my head is creating an obscure version (so podfiles with no versioning won't get screwed up) to allow us Swift 2 users to not specify a branch.

Thanks!

**Comment by Danappelxx** [comment]
Same as https://github.com/SwiftyJSON/SwiftyJSON/issues/308

**Comment by mikenolimits** [comment]
Would love for this to happen :)
