### ISSUE TITLE
setter does not work,

### ISSUE THREAD

**Issue by yikuo123** [SwiftyJSON/SwiftyJSON#332]
```
let oldValue = json["aaaa"].intValue //oldValue is 1
json["aaaa"].intValue = 999
let newValue = json["aaaa"].intValue //newValue is also 1,but not 999
```

**Comment by ThibaultVlacich** [comment]
You can't assign a new value like that. You have to do like this : 

```swift
json["aaaa"] = 999
```

**Comment by zhigang1992** [comment]
Oddly, this code is actually working fine here

<img width="881" alt="screen shot 2015-10-27 at 1 39 49 pm" src="https://cloud.githubusercontent.com/assets/1057756/10750430/4652a0b2-7cb0-11e5-9e8c-98421bd18fab.png">

**Comment by zhigang1992** [comment]
Since `JSON` is a struct, try preventing copying

```swift
var json:JSON = [:]
var jsonCopy:JSON = json

json["aaaa"].intValue = 999
print(json["aaaa"].intValue) // 999
print(jsonCopy["aaaa"].intValue) //0
```
