### ISSUE TITLE
Xcode 7/Swift 2 support in `master`

### ISSUE THREAD

**Issue by ldiqual** [SwiftyJSON/SwiftyJSON#335]
Now that Xcode 7 is out, can `xcode7` be merged into `master`, as well as a new tag in cocoapods?

**Comment by vincentsong** [comment]
Come on mates!

**Comment by Rhuantavan** [comment]
+1

**Comment by giacgbj** [comment]
+1

**Comment by bluesand** [comment]
+1

**Comment by davidjelliott** [comment]
+1

**Comment by ekimia** [comment]
+1

**Comment by Mazyod** [comment]
Xcode 7 branch is already merged, he just didn't have time to close this issue.

**Comment by zhigang1992** [comment]
merged into master, tag `2.3.0` has been published to CocoaPods

:beers:
