### ISSUE TITLE
Swift 1.2 to Swift 2.0

### ISSUE THREAD

**Issue by Edig** [SwiftyJSON/SwiftyJSON#336]
I juts update the code from swift 1.2 to swift 2.0 and I have several problems

before I use it like this

````
{
response in
            
            if let resp = response.object {
                if let data = resp["data"]?.object {
                    if let story = data["story"]?.object {
                        self.storyInfo = story
                    }
}
````

But when I just .object I have this error:

````initializer for conditional binding must have optional type not AnyObject````

If I change it to ````directoryObject```` everything else its wrong, I need to know the correct way before start modifying because I have over 100 lines to modify.

Best.

**Comment by ThibaultVlacich** [comment]
Just removes the question marks. As said by the error, resp["something"] is not an optional.

**Comment by zhigang1992** [comment]
I'm guessing you only needs to do

```swift
self.storyInfo = response["data"]["story"].string // if it's a string
```
