### ISSUE TITLE
Add watchOS2 as platform

### ISSUE THREAD

**Issue by patricks** [SwiftyJSON/SwiftyJSON#344]
Hi,

I use SwiftyJSON in another CocoaPods podspec as dependency. But since Xcode 7 the lint checker fails, because my Podfile supports the watchOS2 platform and SwiftyJSON doesn't.

I get the following error: 
```
- ERROR | [watchOS] Encountered an unknown error (The platform of the target `Pods` (watchOS 2.0) is not compatible with `SwiftyJSON (2.3.0)`, which does not support `watchos`.) during validation.
```

I saw there is already a pull request for this problem. #320

**Comment by zhigang1992** [comment]
It's merged, watchOS2 should be working properly.

Feel free to reopen this issue if there are any more issues.

:smile:
