### ISSUE TITLE
XCode 7 + Swift 2 + Playground

### ISSUE THREAD

**Issue by xTron23** [SwiftyJSON/SwiftyJSON#347]
Hi,

when i try to import the "SwiftyJSON.swift" file into Playground, i get an error (noch such module "SwiftyJSON".

Does somebody has any idea?

![Uploading SwiftyJSON_Error.png…]()
![Uploading SwiftyJSON_Error.png…]()

**Comment by iamtomcat** [comment]
You need to have your playground within a workspace shared with swifty.

**Comment by xTron23** [comment]
OK, THX. I try this

**Comment by zanfirovidius** [comment]
Hi,

I'm very new at this and I was wondering if you could provide a small tutorial on how to create a playground to a workspace shared. I'm struggling to add to my project SwiftyJSON and Alamofire. I've tried with pods and with manually install but  I've got for both SwiftyJSON and Alamofire at the import section this type of error: "No such module".

At a point I've managed to import to my project only Alamofire (manually) and it worked but now when i'm trying to add also SwiftyJSON i havethis problem.

Can you help?

10x

**Comment by iamtomcat** [comment]
I can probably put together a little project together if you want?

**Comment by zanfirovidius** [comment]
That will be grate.
10x

**Comment by zhigang1992** [comment]
<img width="1440" alt="screen shot 2015-10-29 at 12 49 42 pm" src="https://cloud.githubusercontent.com/assets/1057756/10810398/8e88e594-7e3b-11e5-9e97-98a086d3a853.png">
It's that easy..

But remember, you have to build the target first before you can import it in the playground
