### ISSUE TITLE
Parsing String of JSON using SwiftyJSON

### ISSUE THREAD

**Issue by om23** [SwiftyJSON/SwiftyJSON#348]
Having trouble accessing elements using SwiftyJSON.

Code: let json = JSON(data:menuJson.dataUsingEncoding(NSUTF8StringEncoding)!)
Here json looks like: 
```
{
  "menus" : [
    {
      "menu_name" : "Dinner",
      "sections" : [
        {
          "subsections" : [
            {
              "subsection_name" : "",
              "contents" : [
                {
                  "price" : "6",
                  "type" : "ITEM",
                  "name" : "Fresh Gelati"
                },
                {
                  "price" : "5",
                  "type" : "ITEM",
                  "name" : "Vanilla Custard"
                }
              ]
            }
          ],
          "section_name" : ""
        }
      ]
    }
  ]
}
```

Code: let menu = json["menus"][0].string
      I get nil for menu. Shouldn't this be giving me the array "menus" from the JSON?

I followed the examples in the documentation and still have not been able to parse the json properly.

**Comment by iamtomcat** [comment]
Where is your data coming from? Is it a string, alamofire? Also if you can format your json so it's a little more readable it would be helpful.

**Comment by om23** [comment]
Its coming from Parse as a string.

**Comment by iamtomcat** [comment]
Looking at your example `let menu = json["menus"][0].string` getting a nil make perfect sense as the item you're accessing is not a string and therefore will fail the cast.

If I do this `let temp = json["menus"][0].object` then I get an object back as that's is what is attached to that key. If you want to get the values you have to either directly access each key or iterate through them.

**Comment by om23** [comment]
Hi. I've been trying to access the "price" and "name" elements of the JSON and have been having trouble doing so. Shouldn't I just be able to get the "contents" object?

**Comment by om23** [comment]
I was able to figure out my problem. It seemed like they were being saved as an array so I first saved the first element of the array and then saved as a dictionary. This worked. Thanks for your help!
