### ISSUE TITLE
SwiftJSON cannot work after switching to the Swift new syntax (Pod installation)

### ISSUE THREAD

**Issue by firstprayer** [SwiftyJSON/SwiftyJSON#349]
There are a bunch of errors when I upgrade Xcode and Swift version to the newest. I install the library through pod. Is the pod version not new enough? (I checked that the version I installed is 2.3.0)

**Comment by firstprayer** [comment]
Solved by using the git path for podfile.

**Comment by klampotang** [comment]
What do you mean you used the git path for podfile? I'm getting a bunch of errors and can't figure out what to do
