### ISSUE TITLE
how to use this library with swift 1.2?

### ISSUE THREAD

**Issue by zibann-dev-eugene** [SwiftyJSON/SwiftyJSON#350]
I get compiler errors with master branch.

"Consecutive statements on a line must be separated by ';'"

**Comment by iamtomcat** [comment]
Yeah because the master has been upgraded to use swift 2.0.

**Comment by zhigang1992** [comment]
try with tag `2.2.0`, if it's in CocoaPods do it like this:

```ruby
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :tag => '2.2.0'
```
