### ISSUE TITLE
Swift 2 / Xcode 7 changes version breaks semantic versioning rules. Should be v3 not v2.3!

### ISSUE THREAD

**Issue by mwaterfall** [SwiftyJSON/SwiftyJSON#352]
The changes made for Swift 2 are backwards incompatible with Swift 1, and therefore the version number for that release should have been v3 and not v2.3.

**Comment by thedamfr** [comment]
v3 is not even committed on github ^^

**Comment by AlexChesters** [comment]
:+1:

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
