### ISSUE TITLE
carthage bitcode issue

### ISSUE THREAD

**Issue by silver619** [SwiftyJSON/SwiftyJSON#355]
There is an issue with this on carthage when using archive builds of a project using the created framework, You can check out this link https://github.com/Carthage/Carthage/issues/53 for more detail. Basically you need to add user-defined-setting of "BITCODE_GENERATION_MODE" set to "bitcode" in the framework project before it will be able to work from a carthage builds. I have already cleared this with the guys at Alamofire and it works.

**Comment by tangplin** [comment]
Merged
