### ISSUE TITLE
cannot invode JSON

### ISSUE THREAD

**Issue by longxianlin** [SwiftyJSON/SwiftyJSON#360]
Alamofire.request(.POST, baseUrl, parameters: parameters)
            .responseJSON { _, _, result in
                print(result)
                let json = JSON(data: result)
        }

**Comment by zhigang1992** [comment]
Try 

        Alamofire.request(.POST, baseUrl, parameters: parameters)
            .responseJSON { _, _, result in
                print(result)
                let json = JSON(data: result.value)
        }
