### ISSUE TITLE
using a query path to fetch data like xPath

### ISSUE THREAD

**Issue by alexlee002** [SwiftyJSON/SwiftyJSON#363]
Can u convert the syntax like:

``` swift
JSON[0]["names"][1]["attributes"]["blabla"]
```

to 

``` swift
JSON(query:"[0].names[*].attributes.blabla")
```

"[*]" means any object in an array/dict
"[-1]" means the last object in an array, etc

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
