### ISSUE TITLE
How to parse json string?

### ISSUE THREAD

**Issue by borut-t** [SwiftyJSON/SwiftyJSON#365]
Currently I am using the following code, but it's ugly:

```swift
if let data = jsonString.dataUsingEncoding(NSUTF8StringEncoding) {
    let json = JSON(data: data)
    return json.dictionaryObject
}
```

Is there a way to convert json string to JSON using SwiftyJSON?

**Comment by zhigang1992** [comment]
IMHO

I think **serialization** should not be apart of SwiftyJSON.

You can simply use iOS own JSON Serialization API, or any 3rd party library to do so.

If you're look for code examples here is one

```swift
let a = "{\"a\":\"b\"}"
let b = try? NSJSONSerialization.JSONObjectWithData(a.dataUsingEncoding(NSUTF8StringEncoding)!, options: [])
```

**Comment by zhigang1992** [comment]
Well, I don't think there is any way other than this.

If you think it's too ugly maybe you can try this:

```swift
jsonString.dataUsingEncoding(NSUTF8StringEncoding).flatMap({JSON(data: $0).dictionaryObject})
```

Not sure if it helps

**Comment by borut-t** [comment]
No problem. I thought there is smth. similar implemented within library. Thanks!
