### ISSUE TITLE
JSON.isEmpty returns true by default.

### ISSUE THREAD

**Issue by Katafalkas** [SwiftyJSON/SwiftyJSON#369]
Not sure if its a bug or not, but the comment and actual results are different
![screen shot 2015-10-22 at 10 57 40](https://cloud.githubusercontent.com/assets/1636440/10659911/fd7f444c-78ab-11e5-92b7-2453490da4c4.png)

comments says that by default it returns false, but it actually returns true. This behavior also differs from the past versions.

**Comment by lingoer** [comment]
Missed comment, we do return ```true``` at this situation.

**Comment by lingoer** [comment]
https://github.com/SwiftyJSON/SwiftyJSON/commit/5f5d00dbdcd256600a250765d9f674964080ceee

**Comment by Katafalkas** [comment]
Hey, Its me again. Somehow I bumped again into this. What is the reasoning behind this behaviour ? If an object is a String or some other type - it can still be non empty. But now if an object is non-dict and non-array, it automatically counts as empty even tho it is not.

**Comment by Katafalkas** [comment]
I created a PR that fixes it. Hope it makes sense. It did fix my problem.
https://github.com/SwiftyJSON/SwiftyJSON/pull/464

**Comment by Katafalkas** [comment]
@lingoer By any chance someone could explain to me this behaviour ?

**Comment by zhigang1992** [comment]
It feel to me this method is really confusing to people, and also myself.
And it's not add enough value for us to clarify and document this method.

Also every team might have different definition of empty, so maybe this should not be part of the SwiftyJSON, but rather a simple extension on the actual product code.
