### ISSUE TITLE
Creating an archive causes bitcode error

### ISSUE THREAD

**Issue by adityatrivedi** [SwiftyJSON/SwiftyJSON#372]
I am using SwiftyJSON 2.3.0 obtained via Carthage.

Whenever I try to archive my iOS application on Xcode Version 7.1 (7B91b), I get the following linker error:

```
ld: bitcode bundle could not be generated because '/Users/adityatrivedi/src/Path/To/Project/Resources/SwiftyJSON.framework/SwiftyJSON' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is this a known issue or am I doing something wrong?

**Comment by zhigang1992** [comment]
Can you also provide Carthage version?

**Comment by adityatrivedi** [comment]
@zhigang1992, it was Carthage v0.8.

**Comment by zhigang1992** [comment]
<img width="986" alt="screen shot 2015-11-02 at 9 31 07 pm" src="https://cloud.githubusercontent.com/assets/1057756/10900748/3165005c-81a9-11e5-9599-cf05433ea6a3.png">

Try this new version

**Comment by zhigang1992** [comment]
Please let me know if this helped

**Comment by adityatrivedi** [comment]
Yep the latest version of carthage seems to mitigate the issue. Thanks @zhigang1992!
