### ISSUE TITLE
cannot deal with json data with chinese character?

### ISSUE THREAD

**Issue by cmnewfan** [SwiftyJSON/SwiftyJSON#373]
Hi. The code is below:

```swift
if let dataFromString = jsonString.dataUsingEncoding( CFStringConvertEncodingToNSStringEncoding(CFStringEncoding(CFStringEncodings.GB_18030_2000.rawValue)), allowLossyConversion: false) {
    let json = JSON(data: dataFromString)
} 
```

The problem is like this: the jsonString has some chinese character in its values, if i read the value of json, xcode throws a fatal error: unexpected found nil while unwrapping an optional value

but if i delete the chinese character, the code runs fine. 

jsonString is like this:
```json
{"A":"A","B":"B","C":{"D":"南"}}
```

Is SwiftyJSON not supported with chinese character or i do something wrong in my code?

**Comment by zhigang1992** [comment]
It's was actually because `NSJSONSerialization` doesn't accept this encoding. 

```swift
let string = "{\"A\":\"A\",\"C\":{\"D\":\"南\"}}"
if let dataFromString = string.dataUsingEncoding( CFStringConvertEncodingToNSStringEncoding(CFStringEncoding(CFStringEncodings.GB_18030_2000.rawValue)), allowLossyConversion: false) {
    try! NSJSONSerialization.JSONObjectWithData(dataFromString, options: [])
}
```
This code was crashing as well.

I'm not sure if you have a particular reason to use this encoding, but try use `NSUTF8StringEncoding`

```swift
let string = "{\"A\":\"A\",\"C\":{\"D\":\"南\"}}"
if let dataFromString = string.dataUsingEncoding(NSUTF8StringEncoding) {
    let json = JSON(data: dataFromString)
}
```
