### ISSUE TITLE
Subscript with String enum

### ISSUE THREAD

**Issue by manmal** [SwiftyJSON/SwiftyJSON#375]
Thanks for making and maintaining this library, I know how hard open source can be!

I have a this attribute name enum:

```
private enum J : String {
    case Id = "id"
    case ChannelId = "channel_id"
    case ChannelTitle = "channel_title"
    case Title = "title"
    case Template = "template"
    case Articles = "articles"
}
```

and use it like so:

```let idNumber = j[J.ChannelId].number ?? j[J.Id].number ?? NSNumber(int: 0)```

I then get a compile error:

```Cannot subscript a value of type 'JSON' with an index of type 'J'```

Is this supposed to work? 
Thanks a lot!

**Comment by zhigang1992** [comment]
I'm guessing you have to this
```
let idNumber = j[J.ChannelId].number ?? j[J.Id].number ?? NSNumber(int: 0)
```

**Comment by manmal** [comment]
Sure, but this is ugly :)

**Comment by zhigang1992** [comment]
This?
```
struct J {
    static let Id = "id"
    static let ChannelId = "channel_id"
}

let idNumber = j[J.ChannelId].number ?? j[J.Id].number ?? NSNumber(int: 0)
```

**Comment by manmal** [comment]
No my code is what I'd like to have, but it doesn't compile.

**Comment by zhigang1992** [comment]
Pull Request has been merged.
You can try it out now in master branch.
