### ISSUE TITLE
NSDictionary > JSON String

### ISSUE THREAD

**Issue by TeamVerre** [SwiftyJSON/SwiftyJSON#377]
This what I'm doing to convert it. The log return "nil"

            let keys = ["firstName", "lastName", "age","carNumber", "licenseNumber", "email","password", "msgType"]
            let objects = ["Pencil", "Eraser", "2332","534543", "543543", "Notebook","Pencil", "ADD_DRIVER"]
            self.dictionary = NSDictionary(objects: objects, forKeys: keys)
            
            var data = [Dictionary<String, String>]()
            data.append(self.dictionary as! Dictionary<String, String>);
            var jsonObj = JSON(data)
            
            print("JSON Object")
            print(jsonObj.stringValue)

**Comment by zhigang1992** [comment]
What do you wanna out of `jsonObj.stringValue`?

But I'm guessing you want this?

```swift
print(jsonObj[0]["lastName"].stringValue)
```

**Comment by TeamVerre** [comment]
I want to convert the Dictionary into a valid JSON string which I can post to the server.

**Comment by zhigang1992** [comment]
You're looking for `rawString`

```swift
let keys = ["firstName", "lastName", "age","carNumber", "licenseNumber", "email","password", "msgType"]
let objects = ["Pencil", "Eraser", "2332","534543", "543543", "Notebook","Pencil", "ADD_DRIVER"]
let dictionary = NSDictionary(objects: objects, forKeys: keys)

var data = [Dictionary<String, String>]()
data.append(dictionary as! Dictionary<String, String>);
var jsonObj = JSON(data)

print(jsonObj.rawString())
```
