### ISSUE TITLE
Error after updating to Xcode 7.1

### ISSUE THREAD

**Issue by rsdev-darshan** [SwiftyJSON/SwiftyJSON#378]
dyld: Symbol not found: __TMp10SwiftyJSON17JSONSubscriptType
  Referenced from: /var/mobile/Containers/Bundle/Application/1A23C46A-33BC-4582-93EF-3812344FAD8B/test.app/test
  Expected in: /private/var/mobile/Containers/Bundle/Application/1A23C46A-33BC-4582-93EF-3812344FAD8B/test.app/Frameworks/SwiftyJSON.framework/SwiftyJSON
 in /var/mobile/Containers/Bundle/Application/1A23C46A-33BC-4582-93EF-3812344FAD8B/test.app/test

i am getting this error. please help

**Comment by zhigang1992** [comment]
Have you try `clean build folder` and build again?

If so, it's also possible that you're not embedding the frameworks in your app. 

Are you using CocoaPods or Carthage?

**Comment by rsdev-darshan** [comment]
Its working now.. the problem occurred after updating to Xcode 7.1. I just deleted the "embed pods framework" in build phases.
