### ISSUE TITLE
transform \n error

### ISSUE THREAD

**Issue by seedotlee** [SwiftyJSON/SwiftyJSON#379]
I try to transform the json 

```
"[{\"uid\":\"a8dc9967-5abd-475a-96a7-ce77ee9b4480\",\"id\":\"edbba732-27da-4dba-96b0-e9478577eca7\",\"name\":\"hello\",\"mem_name\":\"\",\"touser\":\"\",\"content\":\"[asdsadf]\n[asdfasdf]\",\"min\":6}]"
```

than get the type is SwiftyJSON.Type.Null

can swiftyjson parsing  "\n"?

**Comment by zhigang1992** [comment]
If we don't escape `\n` then the string becomes

```json
[{
  "uid": "a8dc9967-5abd-475a-96a7-ce77ee9b4480",
  "id": "edbba732-27da-4dba-96b0-e9478577eca7",
  "name": "hello",
  "mem_name": "",
  "touser": "",
  "content": "[asdsadf]
  [asdfasdf]",
  "min": 6
}]
```

Which IMHO is corrupted...

JSON parsing in `SwiftyJSON` is actually delegated to iOS's `NSJSONSerialization` which is where this parse is failing.

Also you can escape it simply by wrapping it with another `\`. like `\\n`
