### ISSUE TITLE
Build errors with Xcode 7.0.1 and Swift 2

### ISSUE THREAD

**Issue by haitaoxin** [SwiftyJSON/SwiftyJSON#382]
Not sure if anybody else got the same error, but, building the latest code of Example project, my Xcode complained "'array' is unavailable: please construct an Array from your lazy sequence: Array(...)" on line 55 and 86 in ViewController.swift.

After changing them to:
         let key: AnyObject = Array(self.json.dictionaryValue.keys)[row]
the build passed. Any other thought?

**Comment by zhigang1992** [comment]
Just fixed in master.

Thx for pointing it out.

:beers:
