### ISSUE TITLE
[Xcode 7.1]Failed to build workspace SwiftyJSON with scheme SwiftyJSON iOS 

### ISSUE THREAD

**Issue by BikeBear** [SwiftyJSON/SwiftyJSON#386]
When i use `cartheage update` , get the following error:

*xcodebuild: error: Failed to build workspace SwiftyJSON with scheme SwiftyJSON iOS.
	Reason: The run destination iPad 2 is not valid for Running the scheme 'SwiftyJSON iOS'.
A shell task failed with exit code 70:*

This problem was happened before?

**Comment by zhigang1992** [comment]
Please upgrade to carthage version 0.9.2

**Comment by BikeBear** [comment]
Hao le, thanks!
