### ISSUE TITLE
"Alternatively method" like [1,"list",2,"name"] has error 

### ISSUE THREAD

**Issue by lyragosa** [SwiftyJSON/SwiftyJSON#389]
in example has 

> let path = [1,"list",2,"name"]
> let name = json[path].string

i try it and get a parse error 

> Cannot subscript a value of type 'JSON' with an index of type '[NSObject]'

**Comment by lyragosa** [comment]
another example

>//Array & Dictionary
var json: JSON =  ["name": "Jack", "age": 25, "list": ["a", "b", "c", ["what": "this"]]]
json["list"][3]["what"] = "that"
json["list",3,"what"] = "that"
let path = ["list",3,"what"]
json[path] = "that"

has the same problem in line -> json[path] = "that"

**Comment by zhigang1992** [comment]
Seems to be a type issue, can you try this 

```swift
let path:[JSONSubscriptType] = [1,"list",2,"name"]
let name = json[path].string
```

**Comment by lyragosa** [comment]
so how can i convert [AnyObject] to [JSONSubscriptType]?
