### ISSUE TITLE
Get error when submitting to app store

### ISSUE THREAD

**Issue by ztolley** [SwiftyJSON/SwiftyJSON#391]
If I include SwiftyJson in a TVOS and try and submit to the app store I get

ERROR ITMS-90502: "Invalid Bundle. Apps that only contain the arm64 slice must
also have 'arm64' in the list of UIRequiredDeviceCapabilities in Info.plist."

It seems this is a new thing that apple are doing, what would be the impact of adding this to the info.plist?

**Comment by zhigang1992** [comment]
Should've been fix [here](https://github.com/SwiftyJSON/SwiftyJSON/pull/396)
