### ISSUE TITLE
Add a better way to handle numbers represented as strings

### ISSUE THREAD

**Issue by dmytro-shchurov** [SwiftyJSON/SwiftyJSON#392]
When we get json like this `"query"="1"` we'd like to as check for this parameter as well as to get it as integer. Unfortunately, `.intValue` does not return optional, neither `.number?` accepts `.type == .String`

So, we are not able to use this simple sentence `guard let query = json["query"].int else {}` nor this one `guard let query = json["query"].intValue else {}`, because it's not optional, and because it returns 0 even if no `query` variable in JSON

**Comment by zhigang1992** [comment]
This should work
```swift
json["query"].string.flatMap({Int($0)})
```

**Comment by zhigang1992** [comment]
Feel free to reopen if needed

**Comment by dmytro-shchurov** [comment]
This will not work for `"query": 1` as 
``` 
switch self.type {
            case .String:
                return self.object as? String
            default:
                return nil
            }
```
In case `self.type == .Number` `json["query"].string` returns `nil`

**Comment by zhigang1992** [comment]
So the JSON scheme itself is not static?

**Comment by dmytro-shchurov** [comment]
I only can imagine which engine is used on a server to generate JSON data, and which generation schema might be used... Some "optimiser" might decide to reduce quote characters for numbers, or otherwise to wrap all values with quotes.

**Comment by zhigang1992** [comment]
Well, IMHO, I don't think it's a good idea, but none the less,

How about this?

```
guard json["query"].intValue != 0 else {
```
:)

**Comment by zhigang1992** [comment]
```swift
guard json["query"] else 
```

**Comment by dmytro-shchurov** [comment]
+1
Yep.. at the moment I check exactly for a key, and then get a `..Value` property (which is casted).
But, what about using Optional mark for not existing parameters? Now, optionality means failed casting and this is anti-pattern IMHO

**Comment by dmytro-shchurov** [comment]
Imho casting failure must be handled by user, because it means something unexpected/wrong data

**Comment by zhigang1992** [comment]
Can you give a bit more code on this?

I'm not quiet 100% sure about the situation here. lol

**Comment by zhigang1992** [comment]
would something like this help?

```swift
var a:JSON = [:]
//a["b"] = 1
let b = a["b"].int ?? a["b"].string.flatMap({Int($0)})
print(b)
```

**Comment by dmytro-shchurov** [comment]
+1
Seems acceptable as allows to guard and assign at once. This will make code clear. Thank you )
PS But still `.int | .string` result mixes missing parameter and unexpected casting in one method.
