### ISSUE TITLE
Scheme for watchOS is not needed but Carthage tries to build it and fails with `--platform iOS`

### ISSUE THREAD

**Issue by hiragram** [SwiftyJSON/SwiftyJSON#395]
I just want to build iOS scheme but fails on watchOS scheme.

Command I executed is as follows:

```
$ echo 'github "SwiftyJSON/SwiftyJSON" "2.2.1"' >! Cartfile ; carthage update --platform ios              ⏎
*** Cloning SwiftyJSON
*** Checking out SwiftyJSON at "2.2.1"
*** xcodebuild output can be found in /var/folders/ch/jcgf09f15hl391jn849d5yr80000gn/T/carthage-xcodebuild.YcmuFf.log
A shell task failed with exit code 66:
xcodebuild: error: Scheme SwiftyJSON watchOS is not currently configured for the build action.
```

What should I do?

**Comment by lingoer** [comment]
the latest SwiftyJSON version is ```2.3.1``` and it seems you were using the ```2.2.1``` ?

**Comment by hiragram** [comment]
@lingoer I am still using Swift 1.2 ...

**Comment by hiragram** [comment]
@lingoer This issue was solved by removing Carthage directory.
Maybe Carthage/Build/tvOS directory caused this issue I think.
Thanks for your quick reply.
