### ISSUE TITLE
AlamoFire integration on README is not updated

### ISSUE THREAD

**Issue by erez-rabih** [SwiftyJSON/SwiftyJSON#397]
Hi,

I just tried to use the example provided in the README for reading JSON via AlamoFire responses and it doesn't work: 
```swift
Alamofire.request(.GET, url, parameters: parameters)
  .responseJSON { (req, res, json, error) in
    if(error != nil) {
      NSLog("Error: \(error)")
      print(req)
      print(res)
    }
    else {
      NSLog("Success: \(url)")
      var json = JSON(json!)
    }
  }
```
It looks like Alamofire's responseJSON method does not take the 4 argument closure as an argument anymore, at least on the latest version which is 3.X.X

I am willing to supply a working example if needed.

Thanks.

**Comment by guidev** [comment]
@erez-rabih did you manage to get it working? I would be glad if you could post the correct way to use it.

**Comment by erez-rabih** [comment]
The commit works with current versions of Alamofire and SwiftyJSON:
  - Alamofire (3.1.2)
  - SwiftyJSON (2.3.1)

**Comment by guidev** [comment]
thank you
