### ISSUE TITLE
7 issues in SwiftyJSON.swift

### ISSUE THREAD

**Issue by timroesner** [SwiftyJSON/SwiftyJSON#404]
Hey, when I tried running the SwiftyJSON I got 5 warnings and 7 issues in the main file in the following lines:

```
 if let (key_: String, value_: AnyObject) = generate_.next() {
                    return (key_, JSON(value_))

return NSString(data: data, encoding: encoding)

return map(self.object as! [AnyObject]){ JSON($0) }

return self.number?.unsignedIntegerValue

return self.numberValue.unsignedIntegerValue

```

Opening SwiftyJSON.swift in Xcode 7.1.1 will show the same issues

**Comment by zhigang1992** [comment]
This seems to be pretty old code.

Can you try to update it to the newer version?

**Comment by ldiqual** [comment]
This issue has been inactive for a while so I'm gonna go ahead and consider it fixed. Please let us know if you want to reopen it.
