### ISSUE TITLE
Use NSDictionary and NSArray instead of Dictionary?

### ISSUE THREAD

**Issue by wxiaoguang** [SwiftyJSON/SwiftyJSON#408]
I think the the performance problems ( eg #241 ) are related to the type-casts of Swift Dictionary and NSDictionary.

The Instruments shows that SwiftyJSON keeps type-casting every NSDictionary to Dictionary and causes much memory allocating and copying.

In my experience, use objects as they are in Swift can be much faster, do not do any type-cast.

**Comment by Raymond26** [comment]
Any reaction from the developers regarding this?

**Comment by ldiqual** [comment]
@wxiaoguang @Raymond26 As of SwiftyJSON 3 and Swift 3, I don't believe there is any type cast to NS* values besides in the `Comparable` extension: https://github.com/SwiftyJSON/SwiftyJSON/blob/master/Source/SwiftyJSON.swift#L1266. Would you mind sharing some code that would cause performance issues so we can look into it deeper?

**Comment by wxiaoguang** [comment]
This issue is too old and only for old Swift. Modern Swift has changed so much, I think this issue can be closed  :)
