### ISSUE TITLE
analyze date type error 

### ISSUE THREAD

**Issue by smalldu** [SwiftyJSON/SwiftyJSON#409]
sometimes analyze empty string "" to be a Bool type . hope you can solve it .

**Comment by zhigang1992** [comment]
@smalldu Can you provided a bit of more example on this?

Maybe a code snippet?

**Comment by smalldu** [comment]
```
  for item in json["result"]["items"]{
        for (k,v) in item.1["room"].dictionary!{
                 print("\(v.type),\(v)")
                //I found v is a empty string  but type is Bool  yesterday, but i can't reproduce it now.
        }
  }
```
if i reproduce it someday , i will show you the json data and code snippet

**Comment by zhigang1992** [comment]
Cool, feel free to reopen this if needed.
