### ISSUE TITLE
Multiple Errors on Build Xcode 7.0.1, Apple Swift version 2.0 

### ISSUE THREAD

**Issue by gminky019** [SwiftyJSON/SwiftyJSON#414]
Hello, 

I took the latest source from the master branch. When adding it into my project im getting ~ 75 errors; ranging from...

AnyObject is not convertable... did you mean to use ! to force downcasting
Type JSON does not conform to protocol 'Sequence Type'
Availability has been named to available. 
Extra Arguements
# has been removed..

Im fairly new to swift, help would be greatly appreciated!

**Comment by gminky019** [comment]
I was using the wrong version!

**Comment by klampotang** [comment]
I'm having this issue too. What's the "right version"??

**Comment by gminky019** [comment]
You have to be careful on your version of xcode as well.

I still believe I took the latest version and it worked. I do not remember off the top of my head but it is on my public repository project; all i know is I had to get to a special project page for the correct version. Heres the link to the project feel free to grab the files there maybe it will work for you! https://github.com/gminky019/GDC_Protoype
