### ISSUE TITLE
Xcode 7.1 branch

### ISSUE THREAD

**Issue by JamieWhite** [SwiftyJSON/SwiftyJSON#415]
Any plans to merge this into master?

**Comment by Hardenn** [comment]
+1

**Comment by rbrown** [comment]
Hi! https://github.com/SwiftyJSON/SwiftyJSON/compare/xcode7.1 shows commits in xcode7.1 that aren't in master. There are none, it was merged here: 61c47231e06301bcd4e0c5d345d5a76cfa759b9a

**Comment by JamieWhite** [comment]
Ah I wasn't looking at it properly for some reason! It seems odd to keep this branch around though.
