### ISSUE TITLE
convert string to json

### ISSUE THREAD

**Issue by zhmiblog** [SwiftyJSON/SwiftyJSON#416]
I have a problem when I am converting a json like string to a json.The string is:
[{day:"2015-12-07 11:30:00",open:"12.110",high:"12.180",low:"12.110",close:"12.170",volume:"5913884"},{day:"2015-12-07 13:30:00",open:"12.170",high:"12.180",low:"12.160",close:"12.160",volume:"480608"}]
my code is:
let apijson = JSON(data:string.dataUsingEncoding(NSUTF8StringEncoding)!)
print (apijson)
print ("this is \(apijson[0].stringValue)")
but it is supposed to run out an error,So is there any proper way to parse this string to Json?

**Comment by regan-sarwas** [comment]
@zhmiblog, I haven't tried to verify this in a playground, but your string is not valid JSON.  Per http://www.json.org, you must quote the keys of your objects:  `[{"day":"2015-12-07 11:30:00","open":"12.110","high":"12.180"`....

**Comment by jorjuela33** [comment]
Yes like @regan-sarwas said is a invalid JSON

**Comment by zhmiblog** [comment]
@regan-sarwas,@jorjuela33. I already tried to standardize the string, added quotes to all keys. then it worked. thank you two.
