### ISSUE TITLE
Line wrapping for Json parsing

### ISSUE THREAD

**Issue by michaeltnguyen** [SwiftyJSON/SwiftyJSON#417]
Say I have `let jsonObject = json["AReallyLongName"]["AndASecondReallyLongName"]`.  Is it possible to line wrap this statement, like:

`let jsonObject = json["AReallyLongName"]`
`["AndASecondReallyLongName"]`

Currently, this is a compile error.  I can work around it by assigning multiple jsonObjects, but I'd rather line wrap.

`let jsonObject1 = json["AReallyLongName"]`
`let jsonObject2 = jsonObject1["AndASecondReallyLongName"]`

Thanks,
Michael

**Comment by neelamsharma12** [comment]
@michaeltnguyen , Yes it is possible . If your " json["AReallyLongName"]["AndASecondReallyLongName"] " is returning string object then you need to do  json["AReallyLongName"]["AndASecondReallyLongName"].string.

Additional info: 
If your json["AReallyLongName"] part returning array then you need access it by using index as json["AReallyLongName"] [index] .
And then you can use it like this , 
jsonObject = json["AReallyLongName"][index]["AndASecondReallyLongName"].string

**Comment by michaeltnguyen** [comment]
@neelamsharma12 
Thanks for your comment, but it doesn't really address my question.  I'd like to have a multi-line json statement (e.g., for one that is greater than 80 characters and won't fit on a single line).

I suppose it's more of a swift question than a SwiftyJSON question, though.

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.

On a side note, you can probably use something like

```
let path: [JSONSubscriptType] = [
    'AReallyLongName',
    'AndASecondReallyLongName'
]
let string = json[path].string
```
