### ISSUE TITLE
Swift object to JSON

### ISSUE THREAD

**Issue by fcbflying** [SwiftyJSON/SwiftyJSON#422]
I create a class Message with details as bellow:
import Foundation
import SwiftyJSON
class Message{
    var type:String
    var content:[UInt8]

```
init(type:String, content:[UInt8]){
    self.type = type
    self.content = content
}
var json: JSON {
    get {
        var dict = [String: AnyObject]()
        let mirror = Mirror(reflecting: self)
        for (_, attr) in mirror.children.enumerate() {
            if let property_name = attr.label as String! {
                dict[property_name] = attr.value as? AnyObject
            }
        }
        return JSON(dict)
    }
}
```

}

1, I create a message instance: 
let content:[UInt8] = [1,2,3,4,5]
let msg = Message("test",content)
2, And then I print(msg.json) , the content UInt8 array not convert successfully!
Can you help me?
Thanks a lot.

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
