### ISSUE TITLE
pods not working 

### ISSUE THREAD

**Issue by cloudjanak** [SwiftyJSON/SwiftyJSON#423]

**Comment by paradoxally** [comment]
You need to provide more information.

Project target?
CocoaPods version?
Xcode version?

I tested with Xcode 7.2 using the latest version of CocoaPods and it works with:

    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

**Comment by tirrorex** [comment]
I think he has the same thing i got aka no such module on import.
For me it's project target osx 10.9, pods 0.39, xcode 7.1.1
