### ISSUE TITLE
.string = nil but .stringValue not

### ISSUE THREAD

**Issue by YLKwan** [SwiftyJSON/SwiftyJSON#424]
```
    let nsData = "{\"data\":\"1\"}".dataUsingEncoding(NSUTF8StringEncoding)!
    let jsonObject = try! NSJSONSerialization.JSONObjectWithData(nsData, options: [])
    let json = JSON(jsonObject)
    print(json["data"].string) //Optional("1")
    print(json["data"].stringValue) //1

    let nsData2 = "{\"data\":1}".dataUsingEncoding(NSUTF8StringEncoding)!
    let jsonObject2 = try! NSJSONSerialization.JSONObjectWithData(nsData2, options: [])
    let json2 = JSON(jsonObject2)
    print(json2["data"].string) //nil
    print(json2["data"].stringValue) //1
```

**Comment by jorjuela33** [comment]
@YLKwan in the second JSON the data value is a NSNumber type, since string property is a optional value its able to return a nil but stringValue is not an optional, so when you try to get the value via stringValue this property is able to use the stringValue type from the NSNumber object.

 check the code for the string property

``` 
public var string: String? {
        get {
            switch self.type {
            case .String:
                return self.object as? String
            default:
                return nil
            }
        }
        set {
            if let newValue = newValue {
                self.object = NSString(string:newValue)
            } else {
                self.object = NSNull()
            }
        }
    }
```

also for the stringValue

```
//Non-optional string
    public var stringValue: String {
        get {
            switch self.type {
            case .String:
                return self.object as? String ?? ""
            case .Number:
                return self.object.stringValue
            case .Bool:
                return (self.object as? Bool).map { String($0) } ?? ""
            default:
                return ""
            }
        }
        set {
            self.object = NSString(string:newValue)
        }
    }
```

observe the case when the type is a number 

```
 case .Number:
                return self.object.stringValue
```

object is another property that returns the self.rawNumber and rawNumber a NSNumber type

**Comment by neelamsharma12** [comment]
@YLKwan , In Swift, for AnyObject type stringValue is used to type cast Int to String . In your case when you are doing ".string"  is incorrect as you have integer value in your data so to type cast it to string you need to do ".stringValue"

**Comment by neelamsharma12** [comment]
@YLKwan , In Swift, for AnyObject type stringValue is used to type cast Int to String . In your case when you are doing ".string" is incorrect as you have integer value in your data so to type cast it to string you need to do ".stringValue"

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
