### ISSUE TITLE
Use of unresolved identifier 'ULONG_MAX'

### ISSUE THREAD

**Issue by lptr2** [SwiftyJSON/SwiftyJSON#425]
XCTAssertEqual(JSON(NSNumber(unsignedLong: ULONG_MAX)).description,"(ULONG_MAX)")

Xcode Version 7.2 (7C68)

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
