### ISSUE TITLE
json["sex"].int got nil

### ISSUE THREAD

**Issue by bjzhou** [SwiftyJSON/SwiftyJSON#426]
below is my test case

``` swift
func testSwiftyJSONInt() {
    let jsonStr = "{\"sex\": \"1\"}".dataUsingEncoding(NSUTF8StringEncoding)
    let json = JSON(data: jsonStr!)
    XCTAssertEqual(json["sex"].intValue, 1)
    XCTAssertEqual(json["sex"].int, .Some(1))
}
```

 XCTAssertEqual failed: ("nil") is not equal to ("Optional(1)")

Maybe it's not a issue, but I still feel strange.

**Comment by hilen** [comment]
your sex response is string ,not int.

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
