### ISSUE TITLE
carthage build fail

### ISSUE THREAD

**Issue by aotian16** [SwiftyJSON/SwiftyJSON#428]
build failed when use `carthage update` command.
### log

<pre>
*** Cloning SwiftyJSON
*** Checking out SwiftyJSON at "2.3.1"
*** xcodebuild output can be found in /var/folders/xl/z7j5r29d0cs6t5jg7_bqkk5w0000gn/T/carthage-xcodebuild.UXfY4s.log
*** Building scheme "SwiftyJSON OSX" in SwiftyJSON.xcworkspace
*** Building scheme "SwiftyJSON watchOS" in SwiftyJSON.xcworkspace
** BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
</pre>

**Comment by candostdagdeviren** [comment]
It is the same as tvOS platform.

In the log it says:
`Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvsimulator9.1

=== BUILD TARGET SwiftyJSON tvOS OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===

Check dependencies
target 'SwiftyJSON tvOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'appletvos' platform`

**Comment by iONsky** [comment]
I just had the same problem but since I only need the framework for iOS I ran `carthage update --platform iOS` and it worked.

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
