### ISSUE TITLE
master merged?

### ISSUE THREAD

**Issue by gaming-hacker** [SwiftyJSON/SwiftyJSON#430]
has the master and 7.1 branch been merged?

**Comment by lucho-yankov** [comment]
Seems so - 
[https://github.com/SwiftyJSON/SwiftyJSON/commit/61c47231e06301bcd4e0c5d345d5a76cfa759b9a](https://github.com/SwiftyJSON/SwiftyJSON/commit/61c47231e06301bcd4e0c5d345d5a76cfa759b9a)

**Comment by gaming-hacker** [comment]
cool
