### ISSUE TITLE
Not as type safe as I would expect

### ISSUE THREAD

**Issue by zorn** [SwiftyJSON/SwiftyJSON#433]
Consider the following:

``` swift
let json = JSON(["name" : 42])
if let name = json["name"].string {
    // will not execute, the if let will fail
} else {
    print(json["name"])       // "42"
    print(json["name"].error) // nil
}
```

I like that the optional `let name` fails -- but and not really satisfied with the lack or inconsistency of the errors.

Forgiveness if I'm missing something dumb -- I'm just getting started with SwiftyJSON.

**Comment by DominicFrei** [comment]
@zorn Is there even an init for that?

**Comment by wanganjun** [comment]
The type of ```json["name"]``` is Int, it will work if you try 
```
if let name = json["name"].int
```

**Comment by voidref** [comment]
I suspect there's no error as the error would just tell you 'could not convert to <type>', which is implicitly obvious from the fact that you are in the `else` clause.

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
