### ISSUE TITLE
Catching JSON Data

### ISSUE THREAD

**Issue by karnakar** [SwiftyJSON/SwiftyJSON#434]
Hi,

what is the best way to catch the json data which of type JSON in user defaults or coredata

**Comment by zhigang1992** [comment]
Do you mean cache?

**Comment by rockylive** [comment]
Is there a way we can use the same model classes for core data?

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
