### ISSUE TITLE
optionally allow \n 

### ISSUE THREAD

**Issue by djdance** [SwiftyJSON/SwiftyJSON#436]
I found here that _\n_ is wrong char for string parsed by JSON.parse()
But some servers send it. 
To avoid this I have to do

```
var  s=NSString(data: data!, encoding: NSUTF8StringEncoding)!
s=s.stringByReplacingOccurrencesOfString("\n",withString: "")
let json2 = JSON.parse(s as String)
```

instead of short (data: data)

So is it possible to optionally turn on possibility to allow \n in parsed string/data?

**Comment by ldiqual** [comment]
@djdance Sorry for the delay on this. It seems that the latest version of SwiftyJSON parses new lines correctly:

```
let json = JSON.parse("{\n    \"a\":\"b\"}")
print(json["a"].stringValue) // Prints "b"
```

Do you have an example of code that fails to parse correctly? Thank you

**Comment by rlxone** [comment]
@ldiqual I have the same issue. I'm using 3.1.4 of SwiftyJSON. Here is my JSON from server
`"{ \"code\":0,  \"info\":\"OK\",  \"result\":{\"tariffs\":[{\"tariff_id\":106, \"tariff_name\":\"dsa\",\"tariff_info\":\"here\r\nerror\" },{\"tariff_id\":108, \"tariff_name\":\"asd\",\"tariff_info\":\"dsa\" }]}}\r\n"`
when i remove **\r\n** characters from **"tariff_info\":\"here\r\nerror\"** is works fine.
I checked this JSON on [http://www.freeformatter.com/json-validator.html](url) and result is
> The JSON input is valid according to RFC 4627 (JSON specfication).
