### ISSUE TITLE
How to remove a JSON (array) element?

### ISSUE THREAD

**Issue by joe528** [SwiftyJSON/SwiftyJSON#439]
I have a JSON array (say, dataObj) generated by SwiftyJSON and I try to remove its element like this:

```
dataObj[m] = nil  // there is no removeAtIndex()
print(dataObj)
```

After execution, dataObj becomes

[..., null, ..., ... ]

What's the way to really remove an element for a JSON array created by SwiftyJSON?

**Comment by syedsanahassan** [comment]
@joe528 

Try
```
dataObj.dictionaryObject?.removeValueForKey(m)
```

**Comment by AnthonyMDev** [comment]
@syedsanahassan Thanks. That works for me. I feel like we should be able to use the `nil` syntax

`dataObj[m] = nil`

Hoping that this is coming soon?

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
