### ISSUE TITLE
Combining with Moya

### ISSUE THREAD

**Issue by AvdLee** [SwiftyJSON/SwiftyJSON#442]
I've created an extension to implement [Moya](https://github.com/Moya/Moya) together with SwiftyJSON called [Moya-SwiftyJSONMapper](https://github.com/AvdLee/Moya-SwiftyJSONMapper).

It's also mentioned on the Moya page:
[Community Extensions](https://github.com/Moya/Moya#community-extensions)

Maybe it's possible to add a reference in the readme here aswel, to make it easier to adapt SwiftyJSON in combination with Moya?

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
