### ISSUE TITLE
Zeros interpreted as nil when casting to int

### ISSUE THREAD

**Issue by oscb** [SwiftyJSON/SwiftyJSON#445]
I have this JSON API returning an int Id which can be zero:

```
{
"id": 0,
"name": "something"
}
```

When parsing the json in Swift I try to cast it to an int:
`self.id = json["id"].int!`

However when loading data **it detetects the 0 as a nil value** so it breaks. I know that the value is being received in the original Json (I checked the Raw Dictionary), so I guess it's actually the value of zero being treated as a nil.

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
