### ISSUE TITLE
best way to merge two jsonarrays?

### ISSUE THREAD

**Issue by djdance** [SwiftyJSON/SwiftyJSON#450]
i have jsonarrays **mySet** and **mySetNew** with the same structure.
how to add new items to mySet?
of course I can 

```
for (_,subJson):(String, JSON) in mySetNew{
                            self.mySet["\(self.mySet.count)"]=subJson
                        }
```

...but in first, it does not work, in second - how to do it simpler?

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
