### ISSUE TITLE
Add try/catch error support to initializer

### ISSUE THREAD

**Issue by hamin** [SwiftyJSON/SwiftyJSON#456]
Ideally it would be nice if when initializing an object you could use the try/catch model to pass along the json parsing error. This is particularly useful for other libraries using SwiftyJSON. ideal usage would be something like this:

``` swift
do {
  let json = try JSON(data: dataFromNetworking)
  print(json)
} catch JSONError.FooError {
  print("foo error")
} catch JSONError.BarError {
  print("bar error")
} catch {
  print("some uncaught error in parsing json")
}
```

I'm not quite sure how to implement this though. Here's an extension that I came across that might provide some help perhaps: https://gist.github.com/akisute/f38a34985ee4aca1e5ad . As far as I can tell that extension doesn't quite add support for try/catch handling in the initializer.

Thanks again for all the work. Been using SwiftyJSON happily since Swift was released. Especially in my lib https://github.com/hamin/FayeSwift

:)

**Comment by ldiqual** [comment]
I'm strongly in support of this. @zhigang1992 thoughts?

**Comment by zhigang1992** [comment]
Agreed, I think we need to rethink our error handling model.
Because most of the code for this library was written back in Swift1, it's definitely need a rewrite and take advantage of the new Swift features.

**Comment by danat8x8** [comment]
I desperately need this, since I  have to deal with malformed json from a legacy system.
ideally the malformed data would be provided in context, so I could a func to fix it while parsing

**Comment by ldiqual** [comment]
PR in review https://github.com/SwiftyJSON/SwiftyJSON/pull/731

**Comment by wongzigii** [comment]
This issue has been addressed. Closing now.
