### ISSUE TITLE
Uint instead of uInt?

### ISSUE THREAD

**Issue by GRIM2D** [SwiftyJSON/SwiftyJSON#461]
Why not to use `Uint` or `uint`?

Currently:

``` swift
json["id"].uInt
json["id"].uInt8
json["id"].uInt16
...
```

Better

``` swift
json["id"].uint
json["id"].uint8
json["id"].uint16
```

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
