### ISSUE TITLE
'inout JSON' is not convertible to 'JSON'

### ISSUE THREAD

**Issue by miwanski** [SwiftyJSON/SwiftyJSON#462]
Hi,

I'm facing a JSON parsing issue I've no idea how to fix.

Part of the JSON data received from the backend are key-value pairs:

`"columns": {
    "created_at": "DESC",
    "id": "DESC"
  }
`

I need them to be stored in a `[String: String]?` optional dictionary. So, this is the code I'm using:

`self.columns = json["columns"].dictionary?.map { 
(key, value) -> (String, String) in
            return (key, value.stringValue)
}`

This however produces a compiler error:

> 'inout JSON' is not convertible to 'JSON'

I should also mention that this is part of a larger JSON response, and it handles sorting data. All other data is parsing fine.

Any clues would be most appreciated, I'm kind of stuck on this one.

**Comment by miwanski** [comment]
I've updated the original post with actual JSON data I'm having issues with.

**Comment by RobinChao** [comment]
i don't kown why you use `map` function in dictionary, you can try this:

`    func testConvertible() {
        var json: JSON = ["columns" : ["created_at" : "DESC", "id" : "DESC"]]
        
        let jsonDic = json["columns"].dictionary
        
        var result: [String : String] = [:]
        if let jsonDic = jsonDic {
            for (key, value) in jsonDic {
                result[key] = value.stringValue
            }
        }
        
        print("\(result)") //["created_at": "DESC", "id": "DESC"]
    }`

wish this help.

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
