### ISSUE TITLE
«Linking against dylib not safe for use in application extension»

### ISSUE THREAD

**Issue by dreymonde** [SwiftyJSON/SwiftyJSON#466]
I’m trying to develop a framework which uses SwiftyJSON. But when I enable «Allow app extensions API only» in «Deployment Info» in «General», I see next warning from SwiftyJSON:
``
ld: warning: linking against dylib not safe for use in application extensions: /Users/oleg/Development/NKit/Carthage/Build/Mac/SwiftyJSON.framework/SwiftyJSON
``

**Comment by RobinChao** [comment]
maybe this warning is Apple's.  you can see [App Extension Programming Guide](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW1).

**Comment by funkenstrahlen** [comment]
I also got this error like @dreymonde. As Apple's documentation suggests I did set the framework's Require Only App-Extension-Safe API” build setting to Yes.

> To configure an app extension target to use an embedded framework, set the target’s “Require Only App-Extension-Safe API” build setting to Yes.

Now I see this warning when I compile

```
(null): Linking against a dylib which is not safe for use in application extensions: /Users/funkenstrahlen/Library/Developer/Xcode/DerivedData/Xenim-gcfvztovwnwiihdwuxgrugxvxquc/Build/Products/Debug-iphonesimulator/SwiftyJSON/SwiftyJSON.framework/SwiftyJSON
```

**Comment by dreymonde** [comment]
Yes, that's actually because SwiftyJSON author hasn't set that setting to Yes. 

Отправлено с iPhone
