### ISSUE TITLE
Add extra floating points after parsing NSData to JSON

### ISSUE THREAD

**Issue by amjad-Alhusseini** [SwiftyJSON/SwiftyJSON#471]
I have an issue when parsing NSData object to JSON using swiftyJSON
the raw JSON is as follows:
`{
  "totalCollectCharge": 16.22,
  "totalCustomsCharge": 0,
  "totalCashOnDeliveryCharge": 0,
  "discountOnCollectCharge": -8.11,
  "totalPayableCharges": 8.11,
  "shipments": [
    {
      "shipmentId": 378992502,
      "totalCharges": 8.11,
      "currency": "USD",
      "shipmentCharges": [
        {
          "type": "CC",
          "originalAmount": 16.22,
          "newAmount": 8.11,
          "discount": -8.11,
          "currency": "USD",
          "payableOnline": true,
          "validPromoCode": true,
          "promoCode": "CONSAPP001",
          "promoCodeDescription": "Consumer App 50% discount"
        }
      ]
    }
  ]
}`

Whenever i pass this NSData to JSON(data: data) it returns the following JSON, take a look at discountOnCollectCharge node how it adds floating points :
`{
  "discountOnCollectCharge" : -0.8100000000000001,
  "totalCollectCharge" : 16.22,
  "shipments" : [
    {
      "totalCharges" : 15.41,
      "currency" : "USD",
      "shipmentCharges" : [
        {
          "promoCode" : "XXX",
          "newAmount" : 15.41,
          "promoCodeDescription" : "Auto Pay Test",
          "originalAmount" : 16.22,
          "discount" : -0.8100000000000001,
          "type" : "CC",
          "currency" : "USD",
          "payableOnline" : true,
          "validPromoCode" : true
        }
      ],
      "shipmentId" : 378992502
    }
  ],
  "totalPayableCharges" : 15.41,
  "totalCustomsCharge" : 0,
  "totalCashOnDeliveryCharge" : 0
}`

**Comment by elnaqah** [comment]
i think those are different  json data Try parse the data with NSJSONSerialization and print the data to check if it is from swiftyJSON or not 
```let serialized: AnyObject?=try? NSJSONSerialization.JSONObjectWithData(confirmedData, options: NSJSONReadingOptions());
    print(serialized);
```

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
