### ISSUE TITLE
7 Issues Swift 2 - Xcode 7.2.1

### ISSUE THREAD

**Issue by joaomirandas** [SwiftyJSON/SwiftyJSON#473]
Hey folks, 

I have a problem here, when i go test my app, using **SwiftJSON** master version, my xcode show **7 Issues**, how are version they has use? anyone can give me a feedback?? Thanks. Erros :

 return anyGenerator {
                if let (key_: String, value_: AnyObject) = generate_.next() {
                    return (key_, JSON(value_))
                } else {
                    return nil
                }
            }

--> OTHER

  let data = try self.rawData(options: opt)
                return NSString(data: data, encoding: encoding)

--> OTHER

return map(self.object as! [AnyObject]){ JSON($0) }

--> OTHER

  return self.number?.unsignedIntegerValue

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
