### ISSUE TITLE
Is there any way to directly convert from JSON to Swift class?

### ISSUE THREAD

**Issue by shinise** [SwiftyJSON/SwiftyJSON#479]
For example,

```
import SwiftyJSON

class ConvertSample {
   func test() {
      JSON(jsonString, ResultObject)      // I hope this is the end of parsing JSON
   }
}

class ResultObject {
   var code: Int
   var message: String
   var error: ErrorType
}
```

Is there is something like that code above?

Writing init method bother me like below :(

```
class ResultObject {
   var code: Int
   var message: String
   var error: ErrorType

   init(json: JSON) {
      code = json["code"].intValue
      message = json["message"].stringValue
      error = ErrorType(rawValue: json["error"].stringvalue)
   }
}
```

I use not only one CLASS to parse JSON.
So I have to write init code of every variables in every classes.

Does anyone have an idea?

**Comment by ejohnsonw** [comment]
In the past used something like this:

//pseudo code
func hydrate (dictionary,objectInstance){
   for key in dictionary.keys  {
        let value = dictionary[key];
        //ask for value's type if its another dictionary, recurse
        if( type ....){
          var childObjectInstance
           hydrate(value,childObjectInstance)
           etc.
        }
        //retrieve property
        let property = objectInstance. get property
     
   }
}

Check this
http://derpturkey.com/get-property-names-of-object-in-swift/. Might want to use a recursive solution that accounts for nested objects.

**Comment by shinise** [comment]
@ejohnsonw Thanks a lot!!!! That is exactly what I wanted.
