### ISSUE TITLE
No error when calling JSON.parse with invalid JSON string.

### ISSUE THREAD

**Issue by waynebloss** [SwiftyJSON/SwiftyJSON#480]
I expected the `jdata` structure to contain an error with the code below, but it does not.

How do I know if there was an error parsing?

``` swift
let jdata = JSON.parse("some invalid JSON")
if jdata.error != nil {
    print(jdata.error!)
}
```

**Comment by ldiqual** [comment]
@waynebloss As of SwiftyJSON v3 I cannot reproduce the issue with your code, so I'm assuming this is fixed. Let me know if I need to reopen. Thanks!
