### ISSUE TITLE
Swift 3 Compatibility

### ISSUE THREAD

**Issue by ejohnsonw** [SwiftyJSON/SwiftyJSON#482]
Compiling with Swift 3 breaks SwiftyJSON

**Comment by stowy** [comment]
I'm seeing the following crash when compiling in Xcode 7.3 

`dyld: Symbol not found: __TMPdSa
  Referenced from: /.../Frameworks/SwiftyJSON.framework/SwiftyJSON
  Expected in: /.../Frameworks/libswiftCore.dylib
 in /.../Frameworks/SwiftyJSON.framework/SwiftyJSON`

**Comment by racer1988** [comment]
SwiftyJSON/Source/SwiftyJSON.swift:399:47: warning: '++' is deprecated: it will be removed in Swift 3

**Comment by ldiqual** [comment]
SwiftyJSON is now swift3 compatible. Closing this
