### ISSUE TITLE
data[0]["title"] = JSON("hahahaha")  data[0]["title"] = "hahahaha"   赋值不起作用呢

### ISSUE THREAD

**Issue by carly1987** [SwiftyJSON/SwiftyJSON#483]
如题

**Comment by carly1987** [comment]
我发现不同点了
不成功的代码：
var data: JSON!
        data =  [
            [
                "title":"groupA",
                "list":
                    [
                        ["word":"A", "desc":"aa"],
                        ["word":"Aa", "desc":"aa"]
                ]
            ],
            [
                "title":"groupB",
                "list":
                    [
                        ["word":"B", "desc":"bb"],
                        ["word":"Ba", "desc":"bb"]
                ]
            ]
        ]
        
        print(data[0]["title"])
        data[0]["title"] = "7777"
        print(data[0]["title"])


成功的代码如下：
var data: JSON =  [
            [
                "title":"groupA",
                "list":
                    [
                        ["word":"A", "desc":"aa"],
                        ["word":"Aa", "desc":"aa"]
                ]
            ],
            [
                "title":"groupB",
                "list":
                    [
                        ["word":"B", "desc":"bb"],
                        ["word":"Ba", "desc":"bb"]
                ]
            ]
        ]
        
        print(data[0]["title"])
        data[0]["title"] = "7777"
        print(data[0]["title"])

这是为什么呢   很多时候  都会需要先var  之后赋值的

**Comment by czboosj** [comment]
我也遇到相同问题这个问题有解决吗

**Comment by czboosj** [comment]
解决了 var 的时候 var homeJson:JSON = []  这样定义, 就可以set了,

**Comment by yikuo123** [comment]
#412 the same problem

**Comment by madsonic** [comment]
bump

**Comment by madsonic** [comment]
a possible workaround is to convert the JSON to native structures e.g. `var native = myJson.arrayObject`, set the value then construct the native structure back to JSON

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Please let us know it you'd like to reopen it.
