### ISSUE TITLE
Getting json value out

### ISSUE THREAD

**Issue by thetof91** [SwiftyJSON/SwiftyJSON#490]
Im making a api call, and Im getting json back and all that.
But Im having trouble getting the one value out that I want.

This is what I can print out when print(json["result"])

SUCCESS
[
  {
    "post_password" : "",
    "to_ping" : "",
    "category" : [
      {
        "description" : "",
        "id" : "28",
        "name" : "Bilka",
        "custom_fields" : "ACF plugin needs to be enabled, Back to documentation for further information",
        "slug" : "bilka",
        "parent" : "0",
        "image" : "Plugin Categories Images must be enabled",
        "count" : "3"
      }
    ],
    "ID" : "6232",
    "post_date_gmt" : "April 7, 2016",
    "post_status" : "publish",
    "post_excerpt" : "",
    "pinged" : "",
    "post_type" : "post",
    "post_mime_type" : "",
    "author" : [
      {
        "jabber" : "",
        "avatar" : "http:\/\/1.gravatar.com\/avatar\/a43e252a067007ad9fc85c77d9f72bdd?s=96&#038;d=mm&#038;r=g",
        "custom_fields" : "ACF plugin needs to be enabled, Back to documentation for further information",
        "ID" : "2",
        "user_nicename" : "bilka",
        "user_url" : "",
        "user_registered" : "April 7, 2016",
        "description" : "",
        "aim" : "",
        "last_name" : "",
        "role" : {
          "author" : true
        },
        "user_login" : "Bilka",
        "user_email" : "test@test.dk",
        "nickname" : "Bilka",
        "yim" : "",
        "session_id" : "0u762ek2at5n1hfrss75cl56c4",
        "first_name" : "Bilka",
        "display_name" : "Bilka"
      }
    ],
    "post_name" : "uge-55",
    "post_author" : "2",
    "post_content" : "http:\/\/ibeacon.ideadev.dk\/wp-content\/uploads\/2016\/04\/5328a5298d7ea-300x169.jpg",
    "post_title" : "Uge 55",
    "post_date" : "April 7, 2016"
  }
]

I then want these 2 values 
"post_content" : "http:\/\/ibeacon.ideadev.dk\/wp-content\/uploads\/2016\/04\/5328a5298d7ea-300x169.jpg",
"name" : "Bilka",

But Im having trouble trying to get that.
Pretty much all I try I just get null.

json["result"]["post_content"] dont work. Also tried other things, but nothing seems to work for me. Just get null back.

**Comment by alexdd55** [comment]
did you try `json["result"][0]["post_content"] ` ?

**Comment by thetof91** [comment]
I thought I had tried that before. Because i tried `json["result"][0]` but that just gave me null before too.

Now after taking break from it and tried run again it gave me the result back.
