### ISSUE TITLE
dictionary key is NSNumer init fail 

### ISSUE THREAD

**Issue by fanpyi** [SwiftyJSON/SwiftyJSON#493]
```
    let dic = ["id":20,NSNumber(int: 1000):"fly","name":"Alice"]
    let json = JSON(dic)
```

(lldb) po json
▿ unknown
- rawArray : 0 elements
- rawDictionary : 0 elements
- rawString : ""
- _type : SwiftyJSON.Type.Unknown
  ▿ _error : Optional(Error Domain=SwiftyJSONErrorDomain Code=999 "It is a unsupported type" UserInfo={NSLocalizedDescription=It is a unsupported type})

**Comment by ldiqual** [comment]
@fanpyi JSON keys can only be strings, which is why you're getting this errors. Closing this
