### ISSUE TITLE
++ Deprecated in Swift 3

### ISSUE THREAD

**Issue by JipV** [SwiftyJSON/SwiftyJSON#496]
When i try to validate my .podspec with SwiftyJSON 2.3.2 as a dependency I get a warning
saying SwiftyJSON has a line with '++' in it. And that '++' will be deprecated in Swift 3!

Now i have to do --allow-warnings to get SwiftyJSON through validation which is not optimal. Please consider changing this '++' line to += 1!

Kind regards,
Erik

**Comment by bre7** [comment]
Dupe #455

**Comment by vrutberg** [comment]
I believe this has been fixed on master, but there hasn't been a new release since it was fixed. Any plans on releasing a new version?

**Comment by ldiqual** [comment]
SwiftyJSON is now swift3 compatible. Closing this
