### ISSUE TITLE
Unable to install library via cocoapods

### ISSUE THREAD

**Issue by iDevelopper** [SwiftyJSON/SwiftyJSON#502]
Hi,

In my Podfile:

pod 'SwiftyJSON', '~> 2.3'

Run pod install:

[!] Unable to find a specification for 'SwiftyJSON'.

[!] Unable to load a podspec from `SwiftyJSON.podspec`, skipping:

Pod::DSLError

Thanks for help!

**Comment by adrianbrink** [comment]
Include the path to the github repo with ":git", like in the example in the readme

**Comment by iDevelopper** [comment]
Same error:

Pre-downloading: `SwiftyJSON` from `https://github.com/SwiftyJSON/SwiftyJSON.git`
[!] Unable to find a specification for 'SwiftyJSON'.

[!] Unable to load a podspec from `SwiftyJSON.podspec`, skipping:

Pod::DSLError

**Comment by skydivedan** [comment]
Sorry, I don't mean to go off-topic here. But why is this? I mean, why doesn't SwiftyJSON use the cocoapods versioning stuff? All this ":git" line does is get the latest revision from master, which makes it equivalent to just using a git-submodule. I mean, if that's the case, I don't understand why it's a pod at all.

**Comment by stevenjemm** [comment]
Hey,

Has anyone found a solution to this issue yet?

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.

**Comment by iDevelopper** [comment]
Okay but you never answered!
