### ISSUE TITLE
Convert SiwftyArray to NSArray

### ISSUE THREAD

**Issue by Piyush08** [SwiftyJSON/SwiftyJSON#504]
Hello,

I implemented SwiftyJSON with Alamofire SDK. 
It works fine for me. 
But How can I convert my SwiftyJSON array to NSArray?
also I want to convert SwiftyDictionary to NSDictionary

Because we can able to save SwiftyArray in UserDefaults.

Thank you,

**Comment by bre7** [comment]
There's no need to convert.

```swift
let defaults = NSUserDefaults.standardUserDefaults()
let key = "aKey"

defaults.setObject([1,2,3], forKey: key)
defaults.synchronize()

print(defaults.arrayForKey(key))) // Optional([1, 2, 3])
```

**Comment by Piyush08** [comment]
yes, but "JSON" object is not valid for NSUserDefaults.
I passed SwiftyJSON array from one class to another.
Now, I want to set SwiftJSON array in UserDefaults but it shows me error.

**Comment by bre7** [comment]
Use `aSwiftyJson["aKey"].array` ?

**Comment by Piyush08** [comment]
`NSUserDefaults.standardUserDefaults().setInteger(json["result"].array[0], forKey: "UserID")`

@bre7  check this code.
I need to get &set property in another instance variable for save into NSUSerDefaults.

How to do this?

**Comment by umeshjavastar** [comment]
After getting response from alamofire store response as `let finalJson = JSON(value)` iterate over all dictionary as
 `let mutableArray = NSMutableArray()`

   `for arr in finalson.array!{`
                        `mutableArray.addObject(arr.dictionaryObject!)`
                 `   }`
`let array = NSArray()`
`array = mutableArray.mutableCopy()`
Here is you NSArray contain all object and use it when ever you want

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
