### ISSUE TITLE
get crash in xcode when pass parameter on callback function

### ISSUE THREAD

**Issue by moonrailgun** [SwiftyJSON/SwiftyJSON#506]
my code:
a.swift:

``` swift
class A{
    class func getUserInfo(completionHandler:(AnyObject?) -> Void) {
        let json = JSON(data: data)
        completionHandler(json)
    }
}
```

b.swift:

``` swift
Github.getUserInfo { (userinfo) -> Void in
        println(userinfo)
}
```

and get crash with ide.just like this:

> 0  swift                    0x000000010e6cfa68 llvm::sys::PrintStackTrace(__sFILE_) + 40
> 1  swift                    0x000000010e6cff54 SignalHandler(int) + 452
> 2  libsystem_platform.dylib 0x00007fff910605aa _sigtramp + 26
> 3  libsystem_platform.dylib 0x00007fff521ee2f8 _sigtramp + 3239632232
> 4  swift                    0x000000010db73fac swift::Lowering::SILGenFunction::emitIgnoredExpr(swift::Expr_) + 108
> 5  swift                    0x000000010db93849 swift::Lowering::SILGenFunction::visitBraceStmt(swift::BraceStmt_) + 297
> 6  swift                    0x000000010db96908 swift::ASTVisitor<swift::Lowering::SILGenFunction, void, void, void, void, void, void>::visit(swift::Stmt_) + 152
> 7  swift                    0x000000010db62dc1 swift::Lowering::SILGenFunction::emitValueConstructor(swift::ConstructorDecl_) + 5617
> 8  swift                    0x000000010db3e06a swift::Lowering::SILGenModule::emitConstructor(swift::ConstructorDecl_) + 666
> 9  swift                    0x000000010db3f8db swift::SILModule::constructSIL(swift::Module_, swift::SourceFile_, swift::Optional<unsigned int>) + 475
> 10 swift                    0x000000010db3f988 swift::performSILGeneration(swift::SourceFile&, swift::Optional<unsigned int>) + 72
> 11 swift                    0x000000010da15e18 frontend_main(llvm::ArrayRef<char const*>, char const_, void_) + 3432
> 12 swift                    0x000000010da1396d main + 1677
> 13 libdyld.dylib            0x00007fff921c75fd start + 1

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
