### ISSUE TITLE
SwiftyJSON in Swift 2.2?

### ISSUE THREAD

**Issue by quanguyen** [SwiftyJSON/SwiftyJSON#511]
Hi,

Thanks for the lib. However, after cloning the project, I cannot get it work in my XCode (XCode 7.3.1, Swift 2.2). Do you have this project updated in Swift 2.2?

Thanks

**Comment by edasque** [comment]
What isn't working for you?

**Comment by quanguyen** [comment]
Hi adasque,

I just cloned a new version around 15 mins ago and it compiles just fine! I recognized that this clone is 79KB while the previous clone (that I reported XCode could not compile) is 64KB. Is there something that you just supported or modified to work in Swift 2.2?

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
