### ISSUE TITLE
SwiftyJSON classes can be auto generated

### ISSUE THREAD

**Issue by Ahmed-Ali** [SwiftyJSON/SwiftyJSON#512]
To save you some time when you decide to use SwiftyJSON
[JSONExport](https://github.com/Ahmed-Ali/JSONExport) now supports exporting model classes that uses SwiftyJSON to save you the time you spend writing it by hand :)

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
