### ISSUE TITLE
code have bug

### ISSUE THREAD

**Issue by danwey** [SwiftyJSON/SwiftyJSON#513]
in code:  
 public subscript (position: JSON.Index) -> JSON.Generator.Element {
        switch self.type {
        case .Array:
            return (String(position.arrayIndex), JSON(self.rawArray[position.arrayIndex!]))
        case .Dictionary:
            let (key, value) = self.rawDictionary[position.dictionaryIndex!]
            return (key, JSON(value))
        default:
            return ("", JSON.null)
        }
    }
String(position.arrayIndex)  "Optional(0)" not change : let index = Int(index)//nil
 String(position.arrayIndex!) Optional(0) can change : let index = Int(index)// 0

please edit String(position.arrayIndex)  ->  String(position.arrayIndex!)

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
