### ISSUE TITLE
Optional getter for int only returning nil

### ISSUE THREAD

**Issue by willchen** [SwiftyJSON/SwiftyJSON#516]
I'm parsing the below JSON: 

{
    "_name": "HELENA",
    "description": "his wife, twenty-seven years old",
    "voice": "4"
}

The above JSON segment is then => jsonRole

In the debugger I'm getting the following output:

(lldb) exp jsonRole["voice"].int
(Int?) $R3 = nil
(lldb) exp jsonRole["voice"].intValue
(Int) $R4 = 4

So .intValue is returning correctly, but .int is returning nil regardless of value.

**Comment by lmoreton** [comment]
I seems to be the correct behaviour. Since "4" is a string, .intValue gets the value and it is able to typecast to int, therefore you get the result you want. In the other hand, .int tries to get an int value, which will return nil since it's actually a string "4" and not 4.

**Comment by willchen** [comment]
Gotcha.

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
