### ISSUE TITLE
How to access a key in a json object?

### ISSUE THREAD

**Issue by Dershowitz011** [SwiftyJSON/SwiftyJSON#517]
For example:
```swift
{
    response =     {
        docs =         (
                        {
                "_version_" = 15352wqwd18967678812160;
                active =                 (
                    1
                );
                email =                 (
                    "me@me.com"
                );
                firstName =                 (
                    Nehlo
                );
                id = NehloTestUser1464098899306;
                lastName =                 (
                    Test
                );
                mode =                 (
                    User
                );
                password =                 (
                    wear21zero
                );
            }
        );
        numFound = 1;
        start = 0;
    };
    responseHeader =     {
        QTime = 1;
        params =         {
            indent = true;
            q = "mode:* AND active:true AND email:(me@me.com) AND password:(wear21zero)";
            rows = 10;
            wt = json;
        };
        status = 0;
    };
}
```

is a json I am receiving from the server. How do I check for the "numFound" value? Like if it is 1, i should push the user to the main screen else ask him to input correct username/password. Help please?? I am using Alamofire.

**Comment by namanhams** [comment]
It's documented very clearly here [https://github.com/SwiftyJSON/SwiftyJSON](url)

**Comment by Dershowitz011** [comment]
@namanhams I didn't get that.

**Comment by namanhams** [comment]
I updated the link. It's just the github link of this library.

**Comment by Dershowitz011** [comment]
I'm unable to use it. Help me with this please? Total newbie here. :(

**Comment by namanhams** [comment]
What's the error you got ? The documentation says very clearly on how you can retrieve the value of a key in the json response.

**Comment by Dershowitz011** [comment]
No I am not getting any error. It is not showing me anything in the console at all.

**Comment by alexdd55** [comment]
1. You are trying to access a INT with .string
2. json32[0] mighty bei wrong.
3. pls post the real json object, not the print from xcode

**Comment by Dershowitz011** [comment]
Hey @alexdd55 , how do i do that? How to get the real json object?

**Comment by alexdd55** [comment]
From the URL you call.
This should be some json response. This response shows the real structure of the response object and will be easier to read then the print().
I guess that the Array you try to access is an object...?

**Comment by Dershowitz011** [comment]
I didnt understand @alexdd55 . Could you please tell me with the code I should write? :(

**Comment by alexdd55** [comment]
you are doing a GET on that URL. so you can easily replace you email and password with the actual data and call this URL in your browser. The browser should show you the JSON response.
take you response, copy&paste it into jsonlint.com to get a proper format and post it here.

**Comment by Dershowitz011** [comment]
Please wait. I'll do it.

**Comment by alexdd55** [comment]
ok. there you go.

you should be able to access data with:
`json32["response"]["numFound"].int`

**Comment by Dershowitz011** [comment]
I'll check! Please wait. Thank you so muchh!! :)

**Comment by Dershowitz011** [comment]
It worked!! Thanks a bunch!! Thank you so so so so much @alexdd55 !!!! :) :) :)
