### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by rutgeur** [SwiftyJSON/SwiftyJSON#518]
The documentation talks about using the function .isExists() for checking if the value is there. I however found that .exists() is the function that does this.

**Comment by ldiqual** [comment]
@rutgeur Great catch, thanks a lot for opening an issue, we'll fix it asap.

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
