### ISSUE TITLE
Nested JSON

### ISSUE THREAD

**Issue by ddimitrov90** [SwiftyJSON/SwiftyJSON#519]
I'm struggling with the following thing and still couldn't make it work. I want to have the following JSON structure:

```
{
  "UserId": {
    "ReturnAs": "UserProfile",
    "Expand": {
      "Picture": {
        "ReturnAs": "ProfilePicture"
      }
    }
  },
  "Picture": {
    "ReturnAs": "ActivityPic"
  }
}
```

which will be turned to a string by using the JSON.rawString function. 

I have tried to create the following:

```
let structure = [ String : [ String: JSON] ] 
```

and then JSON(structure) but this is not allowed.

I tried 

```
let innerStructure = JSON( [ String: JSON])
let structure = JSON([String: innerStructure])
```

but then i received an error that a bridge cannot be created between swift class and ObjC class

Any ideas are much appreciated

**Comment by simonnarang** [comment]
@ddimitrov90 Just do this:
```swift

let myJson = JSON(yourJSONObject)

if let userID = myJson["UserId"] {
   if let expand = userID["Expand"] {
      if let picture = expand["Picture"] {
         print(picture["ReturnAs"]) //ProfilePicture
      }
   }
}

```

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
