### ISSUE TITLE
Bad Converting to NSData or something else

### ISSUE THREAD

**Issue by andertsk** [SwiftyJSON/SwiftyJSON#522]
Hello, i have the following code:
![2016-06-01 14 01 32](https://cloud.githubusercontent.com/assets/705208/15700954/0d424756-27f9-11e6-8357-fd762f10bb73.png)

But i get the following output `new json = unknown` instead of normal json output.

**Comment by marconemagnus** [comment]
Hi @andertsk, try to use:

```swift
let newJson = JSON(data: jsonData)
```
instead of:
```swift
let newJson = JSON(jsonData)
```

Cheers.

**Comment by s1ddok** [comment]
This works, thanks!

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
