### ISSUE TITLE
How to remove a JSON element at specific index? 

### ISSUE THREAD

**Issue by rcobelli** [SwiftyJSON/SwiftyJSON#523]
I have a JSON array (say, foo) generated by SwiftyJSON and I try to remove its element like this:

`foo[1] = nil`
After execution, foo becomes

`[alpha, NULL, bravo, charlie]`

How do I actually remove the element from the JSON object at a specific index?

**Comment by marconemagnus** [comment]
Try to use "removeAtIndex(1)".

You can find a similar question at: http://stackoverflow.com/questions/34836400/how-to-remove-a-swiftyjson-element

Before open a issue here you can check at stackoverflow, you will find a lots of questions there. Maybe it is a more appropriate place to  ask questions like this.

Cheers.
