### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by dhf0820** [SwiftyJSON/SwiftyJSON#525]
I added the SwiftyJSON following your instructions for CocoaPod and I get this error:
ld: warning: directory not found for option '-F/Users/dhf/Library/Developer/Xcode/DerivedData/RestJson-ejsakfpnasoeeheluuyzoqkzscrp/Build/Products/Debug-iphonesimulator/SwiftyJSON'
ld: framework not found SwiftyJSON

So I started over and used to manual way which I have used before and get the same error when building.

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
