### ISSUE TITLE
Protocol for Initialization

### ISSUE THREAD

**Issue by gkaimakas** [SwiftyJSON/SwiftyJSON#527]
Would it be out of the scope of the project to add a protocol to init an object with a JSON?

In my projects I use something like the following to have my classes of structs conform to it

````
public protocol JSONSerializable {
    init?(json: JSON)
}
````

A possible use of the protocol would be when dealing with complex responses from the server e.g

````
{
    code: 200,
    error: nil,
    result: {
        title: "SomeTitle"
        }
}
````

Instead of creating a `TitleResponse` struct with the following implementation
````
struct TitleResponse {
    let code: Int
    let title: String?
    
    init(code: Int, title: String?) {
        self.title = title
        self.code = code
    }

    init?(json: JSON) {
        //Implementation here
    }
}
```` 

we could create two completely separate structs
- `Response<T>`
- `Title`

that conform to the `JSONSerializable` protocol. The implementation would be something like the following the:

````
struct Response<T: JSONSerializable>: JSONSerializable {
    let code: Int
    let result: T?

    init(code: Int, result: T?) { // Implementation }

    init? (json: JSON) {
        let code = json["code"].intValue
        let result = T(json: json["result"].json
        self.init(code: code, result: result)
    }
} 
````

````
struct Title: JSONSerializable {
    let title: String
    
    init(title: String) {
        self.title = title
    }

    init? (json: JSON) {
        guard let title = json["title"].string else {
            return nil
        }
        self.init(title: title)
    }
}
````

and when needed one could simply create a complex Response object simply by calling the initializer, e.g:

````
    let response = Response<Title>(json: json)
````

P.S: This isn't a big deal, but I think it would be convenient to all developers who use the library

**Comment by zhigang1992** [comment]
Nice example,

Thanks for proposing this.

So from my understanding,

The problem here, is `TitleResponse` and maybe `OtherResponse` not reusing code from each other, right?

The solution is to have a generate `Response<T>`, and T in this particular case means something that can be converted from JSON.

IMHO, from the aspect of abstracting. You this abstraction is perfect. Having a `JSONSerializable` and constrained type `T`.

But if we were abstracting it all the way to the library level.

1. It might cause mental overhead for other people that doesn't know what its for.
2. In order to move it to the library, we have to make it very generic. like why is the init failable, if it's failable then should we do error reporting, or at least being able to. In the end, it might be to generic to be used in this particular use case.


Anyway, let me know what do you think. 😄

**Comment by gkaimakas** [comment]
1. I agree that it might cause some mental overhead for other people. A small explanation would work I think.
2. Consider this case:

You expect from the server a JSON response that must absolutely contain a field called `id` that is an integer, and the response might have another field, `title`, that is optional.

Your object would be the following then
````
struct SomeObject: SwiftyJSONSerializable {
   let id: Int
   let title: String?
 
   init(id: Int, title: String) {
       self.id = id
       self.title = title
   }

   init? (json: JSON) {
       guard let id = json["id"].int else { return nil }
       self.init(id: id, title: json["title"].string)
   }
}
````

If for some reason the server does not send the `id` field your code will continue to work and you can probably deduce that there was a mandatory field that was missing from the response to begin with. 

Someone could argue that having the init `throw` would be better suited and more generic but I think that it would complicate the code a lot. For my use cases it was sufficient for the init to be failable

**Comment by zhigang1992** [comment]
hah hah,

That's exactly my point.
Which is for something to be in the library, it will have a lot more to consider.
Like `failable` init or `throw`, `failable` works in your case, but `throw` can do error reporting and tell you exactly what went wrong. Or even something like [Argo](https://github.com/thoughtbot/Argo).

Maybe I wasn't being clear enough. 😄 

What I'm trying to say is, `JSONSerializable` is a perfect abstraction on `response<T>` level which close to the final concrete product: `response<Title>` or `response<Other>`.
But if we move it into the repo, then the level might be too high. For the two reason I listed.

Apologize if I sound really picky or unreasonable.

Let me know what you think. 😄

**Comment by gkaimakas** [comment]
I see your point. I will take a look at it.

If I have anything new I will post a new PR
