### ISSUE TITLE
Migrate to Swift 3.0

### ISSUE THREAD

**Issue by hoke-t** [SwiftyJSON/SwiftyJSON#530]
The default migration tool to Swift 3.0 in Xcode 8 beta leaves a few errors in SwiftyJSON, most notably the use of `DictionaryIndex`. It'd be nice to have an updated SwiftyJSON source available for Swift 3.0.

Thanks!

**Comment by lingoer** [comment]
See the code in swift3 branch

**Comment by simplealina** [comment]
Thanks for that, @lingoer. Just wanted to give you a heads up for that branch's code: In "SwiftyJson.swift", for lines no. 739 and 740, there is a syntax error. Make sure you change that. Many thanks!
