### ISSUE TITLE
Playground error of "No such module SwiftyJSON"

### ISSUE THREAD

**Issue by cihadturhan** [SwiftyJSON/SwiftyJSON#531]
#347 is somewhat related to this issue but it seems like it was closed without conclusion. My issue is the following:
I have a macbook pro at home and imac at the office both has El Captain and XCode 7.3.1 installed.

Playground works as usual at home computer but I'm getting "No such module SwiftyJSON" error on office computer.

Screenshot from at home mac: http://d.pr/i/17zJ2/4Asi62da (working as expected)

I know this is a general issue not specific to SwiftyJSON but I'm wondering if any of you guys had the same issue.

Thanks

**Comment by animeshp** [comment]
@cihadturhan may be you are looking for [this](http://stackoverflow.com/a/35818746/1107063).

**Comment by cihadturhan** [comment]
@animeshp that's cool. I'll definitely try this. 
However, I want to know the real source of the problem 😊

**Comment by animeshp** [comment]
@cihadturhan I tried it yesterday and it worked for me what stage did it fail for you?

**Comment by cihadturhan** [comment]
I found the solution. It's because of pod version. Thanks
