### ISSUE TITLE
IOS10 Beta XCode8

### ISSUE THREAD

**Issue by justdan0227** [SwiftyJSON/SwiftyJSON#540]
Any workaround when trying out XCode8, Swift3.0 and iOS10 Beta?  When you open up a file it says that the pod must be signed?

Signing for SwiftyJSON requires a development team. Select a development team in the Target Editor.
Code signing is required for product type 'Framework' in SDK 'iOS 10.0'

**Comment by Tulleb** [comment]
Just sign with your own Team @justdan0227.

It's up to CocoaPods to fix this issue.

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
