### ISSUE TITLE
Check if there is a json object?

### ISSUE THREAD

**Issue by vineethvijayan** [SwiftyJSON/SwiftyJSON#543]
hi SwiftyJson Team,

I don't know will it be possible or not, I would like to do some kind of extension so that I get a error is the JSON is not parsed correctly, for eg:

// Inside Alamofire Response 
let json = JSON(response.result.value!)
let commonEntity = json["CommonEntity"] //just want an alert or some kind of response if CommonEntity is not present.
//

Rather than doing a if else, it would be great If we can do something automatically in debug mode.

Thanks a lot

**Comment by vineethvijayan** [comment]
I did a simple extension like below and it works

extension JSON{
    public subscript(path: JSONSubscriptType...) -> JSON {
        get {
            if self[path] == nil{
                print("Error JSON " + path.description)
            }
            return self[path]
        }
        set {
            self[path] = newValue
        }
    }
}

Please do comment if its the right way to do it?

**Comment by jarrydfillmore** [comment]
+1!

**Comment by ldiqual** [comment]
@vineethvijayan You can use `json["key"].exists()` to check whether a key exists, but if your goal is to print something every time you encounter an invalid key, I don't think it's the responsibility of SwiftyJSON as a library to print anything. The extension above seems like the most appropriate solution for your case and it seems to be work for your case so I'm going to close this. Let me know if you'd like me to reopen it.

**Comment by vinbhai4u** [comment]
Thanks @ldiqual I created a extension for my on purpose

```
extension JSON {
    public subscript(path: JSONSubscriptType ...) -> JSON {
        get {
            #if DEBUG
                if self[path] == nil {
                    print("Error JSON " + path.description)
                }
            #endif
            return self[path]
        }
        set {
            self[path] = newValue
        }
    }
}
```
