### ISSUE TITLE
How to parse the complex string? thanks in advance

### ISSUE THREAD

**Issue by VictorWang** [SwiftyJSON/SwiftyJSON#557]
Hello

I got the return value from websocket, however I found it is not standard JSON format string, could you tell me how to parse this string below:

["[{\"chrome_content\":\"Jae H. Kim1233 sent you a new session message.\",\"chrome_icon\":\"http://14e9c4e69ca35cfb6c4c-aaf3b05f5033b13883b8f6e21438352c.r88.cf1.rackcdn.com/T010671456_Avatar_3.jpg\",\"chrome_link\":\"https://xwww.italki.com/lesson/session/2734345666\",\"type\":\"1998\",\"v\":\"10\"}]"]

**Comment by knothed** [comment]
This is no issue that belongs here on GitHub. Try asking a question on StackOverflow.

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
