### ISSUE TITLE
Swift 3.0 - Xcode beta 2: Cannot call value of non-function type 'NSDecimalNumber'

### ISSUE THREAD

**Issue by pvroosendaal** [SwiftyJSON/SwiftyJSON#558]
Using the swift3 branch and Xcode beta 2 I get two buildtime errors (see screenshot).

<img width="956" alt="screen shot 2016-07-11 at 13 56 24" src="https://cloud.githubusercontent.com/assets/16560001/16729883/a9978cf2-476f-11e6-89d4-a95a675fffbc.png">

**Comment by slammer8** [comment]
Try `NSDecimalNumber.notA` and `NSDecimalNumber.zero`

**Comment by pvroosendaal** [comment]
@slammer8 Thanks, but I know the alternative. It needs to be fixed in the swiftyjson pod. I now also see a couple of pull requests with these fixes, so I'll just wait for it.

**Comment by ldiqual** [comment]
Fixed in the final swift3 release, thanks for reporting!
