### ISSUE TITLE
Regular Expressions in "Key"

### ISSUE THREAD

**Issue by ish3lan** [SwiftyJSON/SwiftyJSON#559]
Is there a possible way to use Regular Expressions in the Key ? E.g. (result["key*"]) will return all the values in the json that has a key starts with keyXXX like key1, key2 and key3,.

Thank you for you work

**Comment by HT154** [comment]
Not directly, but you could potentially use  and filter that collection of keys to

`let resultsMatching = result.dictionaryObject!.keys.filter(<filter keys by regex>).map { result[$0] }`

**Comment by ldiqual** [comment]
Seems that @HT154 's solution is a viable one and it's probably not the responsibility of SwiftyJSON as a library to provide this kind a advanced key filtering, so I'm gonna go ahead and close this. Let me know if you'd like to reopen it.
