### ISSUE TITLE
Issue while migrating to swift 3.0 and ios 10

### ISSUE THREAD

**Issue by manovagyanik1** [SwiftyJSON/SwiftyJSON#561]
Hello,
I am not able to build the SwiftyJSON framework using cocapods with Xcode 8 b2 / Swift 3.
I use the "swift3" branch. The error that is coming up is "**Module file's minimum deployment target is ios 10.0**".
I don't have any clue how to move forward. Can someone help?

**Comment by ryangittings** [comment]
+1

**Comment by Alexander-Attar** [comment]
+1

**Comment by mlorenz92** [comment]
+1

**Comment by ahayder** [comment]
+1

**Comment by valheru7** [comment]
+ 1

**Comment by eggswift** [comment]
Carthage use this fork https://github.com/eggswift/SwiftyJSON

**Comment by shivajitanpure** [comment]
Go to project settings ->go to the General Tab -> Select Deployment option -> Select Deplyoment Target 10.0.

this will resolved your issue.

**Comment by Sajjon** [comment]
@manovagyanik1 did you solve this? I am having the same issues for my custom libs...

**Comment by ldiqual** [comment]
SwiftyJSON is now swift3 compatible, closing this.

**Comment by pazarbas** [comment]
+1
