### ISSUE TITLE
Swift 2.3 support - branch missing?

### ISSUE THREAD

**Issue by alpennec** [SwiftyJSON/SwiftyJSON#570]
Hello,
I can't find any branch for iOS Swift 2.3.
Is is possible to have one so we can start migrating SwiftyJSON to Swift 2.3 (+ use it in our projects with Carthage and CocoaPods).
Thanks,
Axel

**Comment by yansally** [comment]
We have a big App and decide to go with Swift 2.3 first. Can we have Swift 2.3 branch soon?

**Comment by nikolaeu** [comment]
+1

**Comment by eggswift** [comment]
+1

**Comment by mickyzinho** [comment]
+1

**Comment by abarnes** [comment]
I forked this repo and fiddled with it until it worked with Swift 2.3 on the master branch (working with Carthage):
https://github.com/abarnes/SwiftyJSON

**Comment by charlag** [comment]
There's a pull request waiting. I think it's odd that such a popular library does not support Swift 2.3. If I can be of any use, I am ready to help.
 https://github.com/SwiftyJSON/SwiftyJSON/pull/611

**Comment by yoxisem544** [comment]
＋1

**Comment by tsfischer** [comment]
Came here looking for this support as well.

**Comment by nicopuri** [comment]
+1 support Swift 2.3

**Comment by mitchellporter** [comment]
There are multiple PR's waiting right now that support Swift 2.3. I'm currently using this one and builds fine: https://github.com/SwiftyJSON/SwiftyJSON/pull/611

**Comment by zhigang1992** [comment]
[Swift3 and Swift2.3 support is here](https://github.com/SwiftyJSON/SwiftyJSON/issues/647)

Closing this one to cleanup the issue list, feel free to reopen this if needed.

Cheers

**Comment by manuelgaytan** [comment]
Thanks, it compiles!
