### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by menhui222** [SwiftyJSON/SwiftyJSON#571]
extension Observable where Element : Result<JSON>{
我这样写有问题吗  
0: error: type 'Element' constrained to non-protocol type 'Result<JSON>'

**Comment by menhui222** [comment]
extension Observable where Element : Result<JSON>{

     func parsingToObject<M:ObjectJSONConvertType>(type:M.Type) -> Observable<Result<M>>{
        return self.flatMap({ (result) -> Result<M> in
            switch self{
            case Success(let json) :
                let obj =  try type.getSelf(json) as! M
                return IaskuResult.Success(obj)
                break
            case  Failure(let errorType):
                return IaskuResult.Failure(errorType)
                break
                
            }
           
            
            })
    }
}

**Comment by menhui222** [comment]
![](https://github.com/menhui222/BLOG_Image/blob/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-07-22%20%E4%B8%8A%E5%8D%8810.26.24.png?raw=true)
![](https://github.com/menhui222/BLOG_Image/blob/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-07-22%20%E4%B8%8A%E5%8D%8810.26.35.png?raw=true)

**Comment by menhui222** [comment]
![](https://github.com/menhui222/BLOG_Image/blob/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-07-22%20%E4%B8%8A%E5%8D%8810.40.48.png?raw=true)
![](https://github.com/menhui222/BLOG_Image/blob/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-07-22%20%E4%B8%8A%E5%8D%8810.41.12.png?raw=true)

**Comment by ldiqual** [comment]
There hasn't been much activity on this issue for a while so I'm gonna go ahead and consider it fixed. Let me know if you'd like to reopen it.
