### ISSUE TITLE
tvOS 10 beta 3, works in debug not in release, build errors:

### ISSUE THREAD

**Issue by renanyoy** [SwiftyJSON/SwiftyJSON#572]
Undefined symbols for architecture arm64:
  "Swift.UnsafeMutableBufferPointer.(subscript.materializeForSet : (Swift.Int) -> A).(closure #1)", referenced from:
      function signature specialization <Arg[3] = Exploded> of generic specialization <Alib.JSON> of Swift.UnsafeMutableBufferPointer.subscript.materializeForSet : (Swift.Int) -> A in main.o
      function signature specialization <Arg[2] = Exploded> of generic specialization <Swift.UnsafeMutableBufferPointer<Alib.JSON> with Swift.UnsafeMutableBufferPointer<Alib.JSON> : Swift.MutableCollection in Swift and Swift.UnsafeMutableBufferPointer<Alib.JSON> : Swift.RandomAccessCollection in Swift> of Swift._siftDown <A where A: Swift.MutableCollection, A: Swift.RandomAccessCollection> (inout A, index : A.Index, subRange : Swift.Range<A.Index>, isOrderedBefore : inout (A.Iterator.Element, A.Iterator.Element) -> Swift.Bool) -> () in main.o
      function signature specialization <Arg[1] = Exploded> of generic specialization <Swift.UnsafeMutableBufferPointer<Alib.JSON> with Swift.UnsafeMutableBufferPointer<Alib.JSON> : Swift.MutableCollection in Swift and Swift.UnsafeMutableBufferPointer<Alib.JSON> : Swift.RandomAccessCollection in Swift> of Swift._heapSort <A where A: Swift.MutableCollection, A: Swift.RandomAccessCollection> (inout A, subRange : Swift.Range<A.Index>, isOrderedBefore : inout (A.Iterator.Element, A.Iterator.Element) -> Swift.Bool) -> () in main.o
      function signature specialization <Arg[1] = Exploded> of generic specialization <Swift.UnsafeMutableBufferPointer<Alib.JSON> with Swift.UnsafeMutableBufferPointer<Alib.JSON> : Swift.MutableCollection in Swift and Swift.UnsafeMutableBufferPointer<Alib.JSON> : Swift.RandomAccessCollection in Swift> of Swift._partition <A where A: Swift.MutableCollection, A: Swift.RandomAccessCollection> (inout A, subRange : Swift.Range<A.Index>, isOrderedBefore : inout (A.Iterator.Element, A.Iterator.Element) -> Swift.Bool) -> A.Index in main.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ldiqual** [comment]
@renanyoy Sorry for the delay on this. SwiftyJSON v3 was released with full support for Xcode 8 + iOS/tvOS 10. Can you give it a shot and let me know if we need to reopen this? Thanks!
