### ISSUE TITLE
Package.swift missing

### ISSUE THREAD

**Issue by SahandTheGreat** [SwiftyJSON/SwiftyJSON#575]
When trying to build SwiftJSON, package manager throws the following error:
`error: The package at /Users/SahandTheGreat/Desktop/kitura/Kitura-Sample/Packages/SwiftyJSON.git has no Package.swift for the specific version: 10.0.1`

Please help me!

**Comment by simonnarang** [comment]
SwiftyJSON isn't SPM compatible

**Comment by simonnarang** [comment]
That will likely come in the fall when Swift 3 is officially released

**Comment by andig** [comment]
I can see it has `Package.swift` file now, yet I'm still receiving this message:

	➜  volkszaehler swift package fetch
	warning: refname '2.4.0' is ambiguous.
	warning: refname '2.4.0' is ambiguous.
	HEAD is now at 49a9cc9 Set APPLICATION_EXTENSION_API_ONLY to yes for macOS target
	Resolved version: 2.4.0
	Empty manifest file is not supported anymore. Use `swift package init` to autogenerate.
	error: The package at `/Users/andig/Desktop/volkszaehler/Packages/SwiftyJSON.git' has no Package.swift for the specific version: 2.4.0
	➜  volkszaehler

**Comment by kandelvijaya** [comment]
I am still getting the same error.

**Comment by cwkatzmann** [comment]
In your dependencies use the latest version.

like this:

`import PackageDescription

let package = Package(
    name: "swiftyJSONtester",
    dependencies: [
      .Package(url: "https://github.com/SwiftyJSON/SwiftyJSON.git", versions: Version(1,0,0)..<Version(3, .max, .max)),
    ]
  )
`

or like this:

`let package = Package(
    name: "swiftyJSONtester",
    dependencies: [
      .Package(url: "https://github.com/SwiftyJSON/SwiftyJSON.git", majorVersion: 3, minor: 1)
    ]
  )`

**Comment by ldiqual** [comment]
@SahandTheGreat The readme just got updated with instructions on adding the latest package version for SPM. I'll consider this fixed, let me know if we need to reopen. Thanks! https://github.com/SwiftyJSON/SwiftyJSON/pull/728

**Comment by allancanare** [comment]
It seems 5.0.2 that contains this fix is not yet released in cocoapods. Any update on when can we have it released in cocoapods as well?
