### ISSUE TITLE
Swift 3 Branch Errors

### ISSUE THREAD

**Issue by simonnarang** [SwiftyJSON/SwiftyJSON#580]
I get the following error in the swift 3 branch:
![screen shot 2016-08-02 at 2 18 02 pm](https://cloud.githubusercontent.com/assets/9156815/17339942/2c0b6f0c-58bc-11e6-834b-3c39efeb9492.png)

**Comment by farice** [comment]
I am having the same issue and have not found a resolution thus far.

**Comment by AnYuan** [comment]
@farice you can try this branch: https://github.com/BaiduHiDeviOS/SwiftyJSON/tree/swift3

**Comment by jasonhocker** [comment]
I deleted ": Swift.Boolean" and it seems to be ok.  Not quite sure why that extension was different than the others
@farice this is the swift 3 branch, but a new breaking change with xcode 8 beta 4.

**Comment by jasonhocker** [comment]
See pull request https://github.com/SwiftyJSON/SwiftyJSON/pull/579

**Comment by simonnarang** [comment]
### Solved
--
Just go to @AnYuan's fork <a href="https://github.com/BaiduHiDeviOS/SwiftyJSON/tree/swift3">here</a>
