### ISSUE TITLE
Now the Boolean protocol has been removed in swift 3.0.so,there is something wrong.

### ISSUE THREAD

**Issue by mg459046365** [SwiftyJSON/SwiftyJSON#585]

**Comment by MarcSteven** [comment]
Possible the author stopped to update the library  .....

**Comment by piyushwadhwani** [comment]
any one knows how to resolve this, Xcode 8 Beta 4 says 
The Boolean protocol has been removed. (SE-0109)

**Comment by piyushwadhwani** [comment]
i was able to compile and run by removing Swift.Boolean in the code, i havent tried getting a boolean value though

**Comment by Fritiof** [comment]
+1

**Comment by gaming-hacker** [comment]
swift3 blows.

**Comment by mediatainment** [comment]
(y)

**Comment by gorzny** [comment]
+1

**Comment by zhigang1992** [comment]
[Swift3 and Swift2.3 support is here](https://github.com/SwiftyJSON/SwiftyJSON/issues/647)

Closing this one to cleanup the issue list, feel free to reopen this if needed.

Cheers
