### ISSUE TITLE
Swift 3.0 & Xcode 8.0 beta 4: No such module 'SwiftyJSON'

### ISSUE THREAD

**Issue by K1tson** [SwiftyJSON/SwiftyJSON#588]
Hi All,

I have manually copied the swift3 branch folder (after unzipping) into the root of my project folder, dragged the .xcodeproj file into Xcode and registered SwiftyJSON as a target dependency and embedded library (the exact same procedure I did with Alamofire) but it's still showing 'No such module 'SwiftyJSON' when attempting to import. 

Any ideas?

**Comment by gaming-hacker** [comment]
just drag the swiftfile to the project and add in xcode

**Comment by K1tson** [comment]
Sorry!
All sorted and working now with updated changes. 
Thank You!
