### ISSUE TITLE
How do I create new JSON objects ?!

### ISSUE THREAD

**Issue by ElSifi** [SwiftyJSON/SwiftyJSON#596]
Hello

I'm trying to create a JSON object like this

`[
  null,
  {
    "name": "nameExample",
    "age": 45
  },
  {
    "name": "anotherName",
    "age": 55
  }
]`

And eventually get that JSON object as a string.
How can do so ?!

**Comment by JeffGuKang** [comment]
I am making some playground docs as #613 .
And I write the part of source that I used to make JSON.


```
var jsonArray: JSON = [
    "array": [12.34, 56.78],
    "users": [
        [
            "id": 987654,
            "info": [
                "name": "jack",
                "email": "jack@gmail.com"
            ],
            "feeds": [98833, 23443, 213239, 23232]
        ],
        [
            "id": 654321,
            "info": [
                "name": "jeffgukang",
                "email": "jeffgukang@gmail.com"
            ],
            "feeds": [12345, 56789, 12423, 12412]
        ]
    ]
]
```

**Comment by ldiqual** [comment]
There hasn't much activity on this issue for a while so I'll go ahead and consider it fixed. Let me know if you'd like me to reopen it. Thanks!
