### ISSUE TITLE
afte unwrap, a string become Array Type

### ISSUE THREAD

**Issue by AlasKuNull** [SwiftyJSON/SwiftyJSON#599]
`     
        let json = JSON(detailArray)

        let string = json.rawString(NSUTF8StringEncoding, options: .PrettyPrinted)

        print(string)

        print(string!)
`
log shows:

Optional("[\n  {\n    \"ProductId\" : 5629,\n    \"SelectedQty\" : 2\n  },\n  {\n    \"ProductId\" : 6700,\n    \"SelectedQty\" : 1\n  }\n]")

[
  {
    "ProductId" : 5629,
    "SelectedQty" : 2
  },
  {
    "ProductId" : 6700,
    "SelectedQty" : 1
  }
]

What happen?

I need the stingValue  NOT array!

**Comment by zhigang1992** [comment]
it's not a array, it's just that `print` method treat string type differently and printing out `\n` as actual line breaks.
