### ISSUE TITLE
Swift3 branch with Xcode 8 Beta 6 not compiling

### ISSUE THREAD

**Issue by valheru7** [SwiftyJSON/SwiftyJSON#602]
Installed with cocoapods like so:

```
pod 'SwiftyJSON',
        :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git',
        :branch => 'swift3'
```

also adding this at the bottom:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end
```

Numerous (~67) errors result in SwiftyJSON. Some are:

> SwiftyJSON.swift:772:35: Expected ',' joining parts of a multi-clause condition
> SwiftyJSON.swift:635:23: No type named 'Boolean' in module 'Swift'
> SwiftyJSON.swift:70:59: Value of type 'Any' does not conform to specified type 'AnyObject'
> SwiftyJSON.swift:110:14: Cannot invoke 'JSON.init' with an argument list of type '([AnyObject])'
> SwiftyJSON.swift:125:14: Cannot invoke 'JSON.init' with an argument list of type '([String : AnyObject])'
> SwiftyJSON.swift:347:22: 'rawDictionary' is inaccessible due to 'private' protection level
> SwiftyJSON.swift:144:29: Return expression of type '[AnyObject]' does not conform to 'AnyObject'
etc etc etc

**Comment by AnYuan** [comment]
[this pull request](https://github.com/SwiftyJSON/SwiftyJSON/pull/582) may help.

**Comment by greyhoundticket** [comment]
I had the issue since unproblematik. I speak later in background klon people human and childs with offhubs. Isearched about many years and I had the commandotec is an klon my mind problem its since double thinked and hoch 33mal ungefähr. Later i will End kloning peoples are in off when you  switched. Danger please

**Comment by zhigang1992** [comment]
[Swift3 and Swift2.3 support is here](https://github.com/SwiftyJSON/SwiftyJSON/issues/647)

Closing this one to cleanup the issue list, feel free to reopen this if needed.

Cheers
