### ISSUE TITLE
Updating example easier to use. 

### ISSUE THREAD

**Issue by JeffGuKang** [SwiftyJSON/SwiftyJSON#603]
Example is hard to use now without navigation way recommended by Apple HIG(Human Interface Guideline). 
- [ ] Push animation horizontally when go detail. (Not calling modal animation.)
- [ ] Navigation item for Back.

**Comment by zhigang1992** [comment]
We should properly go with push animation. 👍

**Comment by JeffGuKang** [comment]
I will start this issue. :)
