### ISSUE TITLE
Represent dictionary with nil as a string

### ISSUE THREAD

**Issue by gsabran** [SwiftyJSON/SwiftyJSON#606]
It seems that `rawString` will simply call `NSJSONSerialization.dataWithJSONObject` on a dictionary: https://github.com/SwiftyJSON/SwiftyJSON/blob/master/Source/SwiftyJSON.swift#L640-L644

This fails if the dictionary has nil values since swift is not smart enough to cast them to json as `null`. What's the best way to get things to work? For instance if I have the dictionary

``` swift
let user = [
  "name": "me",
  "username": nil,
] as [String: Any?]
```

How can I end up with `{"name": "me", "username": null}` ?

**Comment by ldiqual** [comment]
@gsabran You can use something like this:

```
let user = [
  "name": "me",
  "username": NSNull(),
]
```

**Comment by gsabran** [comment]
Yes, but this doesn't play well with dictionaries that have optional values, which can't be represented with `NSNull`. I've addressed it in my PR https://github.com/SwiftyJSON/SwiftyJSON/pull/610 and there's now an option to do that:

```swift
let user = [
  "name": "me",
  "username": nil,
] as [String: Any?]
let representation = JSON(user).rawString(options: [.castNilToNSNull: true])
// representation is {"name": "me", "username": null}
```
