### ISSUE TITLE
Literal conversion doesn't behave like explicit conversion

### ISSUE THREAD

**Issue by gsabran** [SwiftyJSON/SwiftyJSON#609]
```swift
let subJson = JSON(["foo": 1])
let json = JSON(["bar": subJson])
let description = json.debugDescription // this is `{"bar":{"foo":1}}` as excepted

let litJson: JSON = ["bar": subJson]
let litDescription = litJson.debugDescription // this is `unknown`
```

shows that literal conversion might not behave like explicit conversion, which I've found to be quite hard to debug.

**Comment by leo150** [comment]
I'm agree with it. My case is:

let s1: String! = "aaa"
let s2: String! = "124"
let x = JSON(["answer": s1, "score": s2])
print(x.object) //["answer": Optional("aaa"), "score": Optional("124")]
print(x) //unknown

let y = JSON(["answer": s1!, "score": s2])
print(y.object) //["answer": Optional("aaa"), "score": Optional("124")]
print(y) //unknown

let z = JSON(["answer": s1!, "score": s2!])
print(z.object) //["answer": "aaa", "score": "124"]
print(z) //{\n  "answer" : "aaa",\n  "score" : "124"\n}\n

**Comment by zhigang1992** [comment]
So for literal conversion, we assume that the object on the right is a plain object.

This one would work:

```swift
let subJson = JSON(["foo": 1])

let json = JSON(["bar": subJson])
let description = json.debugDescription // this is `{"bar":{"foo":1}}` as excepted

let litJson: JSON = ["bar": ["foo": 1]]
let litDescription = litJson.debugDescription // this is `unknown`
```

Still You're right, we should address this inconsistency.

**Comment by gsabran** [comment]
Thanks. I was not good enough to find exactly where this difference is happening so I could not do a PR

**Comment by zhigang1992** [comment]
I think this PR address this issue.

Feel free to open this if needed.

🍻
