### ISSUE TITLE
Xcode GM Swift3.0 Support

### ISSUE THREAD

**Issue by zxcv740** [SwiftyJSON/SwiftyJSON#623]
Now it's out could you help update? Thanks!

**Comment by KelvinJin** [comment]
I'd recommend https://github.com/IBM-Swift/SwiftyJSON for now.

**Comment by zxcv740** [comment]
Thanks

**Comment by hopye** [comment]
cant get to compile swiftyjson branch swift3 or git IBM-Swift/swiftyjson  :/ Xcode 8 GM

**Comment by victoraugustolls** [comment]
What about using IBM-Swift fork with Carthage, anyone?

**Comment by zaubara** [comment]
I created a pull request in the IBM-Swift fork for Carthage compatibility - you can use my fork in the meantime:
github "zaubara/SwiftyJSON"

**Comment by zhigang1992** [comment]
[Swift3 support is here](https://github.com/SwiftyJSON/SwiftyJSON/issues/647)

Closing this one to cleanup the issue list, feel free to reopen this if needed.

Cheers
