### ISSUE TITLE
Swift 2.3 support

### ISSUE THREAD

**Issue by danielphillips** [SwiftyJSON/SwiftyJSON#624]
I have forked the repo to simply check to use the legacy swift compiler, it's a little inconvenient, I'm wondering if you wouldn't mind having your own swift 2.3 branch tagged from the latest version.

What do you think?

**Comment by waseefakhtar** [comment]
#620 helped me with Swift 2.3 support.

**Comment by dneykov** [comment]
I download master branch vie cocoapods and convert to Swift 2.3. But now Xcode 8 gives me this error:
Module file was created by an older version of the compiler; rebuild 'SwiftyJSON' and try again:
anyone can help me out? Thanks

**Comment by dneykov** [comment]
I delete all data in ~/Library/Developer/Xcode/DerivedData about my app and rebuild and everything works.

**Comment by zhigang1992** [comment]
[Swift3 and Swift2.3 support is here](https://github.com/SwiftyJSON/SwiftyJSON/issues/647)

Closing this one to cleanup the issue list, feel free to reopen this if needed.

Cheers
