### ISSUE TITLE
Errors while trying to integrate swift3 compatible SwiftyJson

### ISSUE THREAD

**Issue by debayanb** [SwiftyJSON/SwiftyJSON#626]
![screen shot 2016-09-14 at 7 10 33 pm](https://cloud.githubusercontent.com/assets/16576079/18514557/a6f699de-7aaf-11e6-9345-6e63203e6b0b.png)

Currently using xCode 8. Is there any fix for this? Integrated it by drag dropping the SwiftyJson.swift file in project root

**Comment by debayanb** [comment]
![screen shot 2016-09-14 at 7 17 39 pm](https://cloud.githubusercontent.com/assets/16576079/18514634/fa51dcd8-7aaf-11e6-9a8a-9b1715c5285c.png)
More errors

**Comment by fortmarek** [comment]
SwiftyJSON is not Swift 3 ready. Last update is from 3 months ago and for example back then Swift 3 defined private keyword differently. It is yet to be seen if the creators return (bummer, I know)

**Comment by debayanb** [comment]
Damn!  :(

**Comment by fortmarek** [comment]
For now you can use this fork, it seems to be working well: https://github.com/acegreen/SwiftyJSON/tree/swift3

**Comment by kylebrowning** [comment]
@fortmarek Cant use that fork if your project is a cocoapod itself because cocoapods does not let you define forks/other repos in a pod spec file, only a single published version.

**Comment by fortmarek** [comment]
So this does not work as well: http://stackoverflow.com/questions/20936885/cocoapods-and-github-forks ?

I usually use Carthage, so bear with me.

**Comment by kylebrowning** [comment]
No, that is referring to a podfile, not a podspec, which is different.

**Comment by fortmarek** [comment]
Oh right, OK, so maybe you could implement it manually...?

**Comment by ttuygun** [comment]
@kylebrowning I encountered some libraries which supports both of Swift 2.x and Swift 3 version in different branches while it labels different versions in pod packages. It can solve in cocoapods if the repo handle this.

**Comment by kylebrowning** [comment]
@ttuygun IM not sure I follow.

In PODSPEC files (not PodFiles) you cannot define a git branch or a specific Repository. You can only define what is pushed to the specs repo with `pod spec push trunk` 

If you own your own library and depend on this one, there is no way to link to a fork unless the owner of that fork publishes the podspec to trunk.

I dont know how else to explain it. 

Read more here, http://stackoverflow.com/questions/22447062/how-do-i-create-a-cocoapods-podspec-that-has-a-dependency-that-exists-outside-of

**Comment by kylebrowning** [comment]
@fortmarek I am down to implement it manually, but that wont work if people are downloading my library. I cant ask users of my library to implement swiftyJSON themselves, so until the owners of SwiftyJson publish the swift-3 branch to podspec, I have remove the use of SwiftyJSON which is unfortunate.

**Comment by zhigang1992** [comment]
[Swift3 support is here](https://github.com/SwiftyJSON/SwiftyJSON/issues/647)

Closing this one to cleanup the issue list, feel free to reopen this if needed.

Cheers
