### ISSUE TITLE
Swift 3 Please!

### ISSUE THREAD

**Issue by mdabrarniyazi** [SwiftyJSON/SwiftyJSON#634]

**Comment by MMasterson** [comment]
https://github.com/IBM-Swift/SwiftyJSON/blob/master/Source/SwiftyJSON.swift

**Comment by bm842** [comment]
https://github.com/appsailor/SwiftyJSON/tree/swift3 works fine too

**Comment by terflogag** [comment]
pod 'SwiftyJSON', :git => 'https://github.com/acegreen/SwiftyJSON.git', :branch => 'swift3'

Works fin too :-)

**Comment by zhigang1992** [comment]
We have landing swift3 support in master branch. 

Feel free to give it a go.

🍻
