### ISSUE TITLE
Swift3 branch is also not working

### ISSUE THREAD

**Issue by Sudhi55** [SwiftyJSON/SwiftyJSON#635]
Carthage cart file with github "SwiftyJSON/SwiftyJSON" "swift3" is also not working?

**Comment by MMasterson** [comment]
Folks over at IBM converted it 
https://github.com/IBM-Swift/SwiftyJSON/blob/master/Source/SwiftyJSON.swift

**Comment by UncleRic** [comment]
Apparently the IBM-Swift version is not compatible (or built for) the iOS platform.

**Comment by triwav** [comment]
@UncleRic Care to explain further? Like it won't work at all or do you mean it just won't work with Carthage?

**Comment by zhigang1992** [comment]
We have landed swift3 support in master branch, feel free to try it out. 😄

**Comment by dowhilenet** [comment]
@zhigang1992 Very Nice . Thinks

**Comment by Adarkas2302** [comment]
xcode still wanted to convert the code when i installed it via cocoa pod.

**Comment by MaximGorin** [comment]
I have the same problem

**Comment by zhigang1992** [comment]
@Adarkas2302 @MaximGorin 
Odd, can you paste in the corresponding section in podfile.lock?
Also your cocoapods version as well.
Thx

**Comment by MaximGorin** [comment]
@zhigang1992 
`PODS:
  - SwiftyJSON (2.3.2)

DEPENDENCIES:
  - SwiftyJSON (from `https://github.com/SwiftyJSON/SwiftyJSON.git`, branch `swift3`)

EXTERNAL SOURCES:
  SwiftyJSON:
    :branch: swift3
    :git: https://github.com/SwiftyJSON/SwiftyJSON.git

CHECKOUT OPTIONS:
  SwiftyJSON:
    :commit: 494f9bf12763d634216ce5b10a88bb5240f59074
    :git: https://github.com/SwiftyJSON/SwiftyJSON.git

SPEC CHECKSUMS:
  SwiftyJSON: 04ccea08915aa0109039157c7974cf0298da292a

PODFILE CHECKSUM: d646f0dd20b277efbdfbbc3803cb9204c296ab67

COCOAPODS: 1.0.0
`

**Comment by zhigang1992** [comment]
@MaximGorin you have to update to version 3.0.0 for swift 3 support.
And 2.4.0 for swift 2.3 or lower.

Let me know if you're still having issue with it.

Cheers

**Comment by MaximGorin** [comment]
@zhigang1992 the error persists

PODS:
  - SwiftyJSON (3.0.0)

DEPENDENCIES:
  - SwiftyJSON (~> 3.0.0)

SPEC CHECKSUMS:
  SwiftyJSON: f57b2b44bc166617372d1c70773591fe9f0f5fd4

PODFILE CHECKSUM: 3c7432f9e522dd9230a200cf2f7646c325981751

COCOAPODS: 1.0.0

**Comment by zhigang1992** [comment]
Can you try this from the RxSwift repo

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
```

Or you can update to cocoapods rc version by

```
gem install cocoapods -v 1.1.0.rc.2
```

Let me know if it works.

**Comment by MaximGorin** [comment]
@zhigang1992 it works. Thx

**Comment by RemyDCF** [comment]
Also, the master branch was updated to Swift 3 and I don't have any errors with Carthage and Xcode 8

**Comment by zhigang1992** [comment]
Closing now, feel free to reopen this if you are running into more issues.

🍻
