### ISSUE TITLE
swiftjson of ibm version in swift3 cant loop?

### ISSUE THREAD

**Issue by rudian** [SwiftyJSON/SwiftyJSON#636]
for (_, k): (String, JSON) in json["main"]{
            self.alldata.addObject([k["p"].stringValue,k["t"].stringValue,k["v"].stringValue,k["c"].stringValue,k["u"].stringValue]);

 }

type 'JSON?' does not conform to protocol 'Sequence'

**Comment by zhigang1992** [comment]
Can you try the 3.0.0 version in cocoapods?

**Comment by rudian** [comment]
i using 3.0 version still have this problem

Using SwiftyJSON (3.0.0)

**Comment by zhigang1992** [comment]
<img width="1512" alt="screen shot 2016-09-23 at 5 33 33 pm" src="https://cloud.githubusercontent.com/assets/1057756/18781341/e13f9e46-81b3-11e6-90a2-a2dd0c0454ce.png">

```swift
//: Playground - noun: a place where people can play

import SwiftyJSON

var json: JSON = [:]
json["main"] = ["hello": "World"]

for (_, k): (String, JSON) in json["main"] {
    print(k)
}
```

Seems working here,
can you post bit more code?

**Comment by rudian** [comment]
@zhigang1992  

i use alamofire4 to get the value

    let json = JSON(response.result.value as! NSDictionary)

for (_, k): (String, JSON) in json["main"]{
self.alldata.addObject([k["p"].stringValue,k["t"].stringValue,k["v"].stringValue,k["c"].stringValue,k["u"].stringValue]);

}

**Comment by zhigang1992** [comment]
hm, can you post `Podfile.lock` here?

**Comment by rudian** [comment]
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

use_frameworks!
target 'x' do
    pod 'SwiftyJSON', '3.0.0'
    pod 'Alamofire', '~> 4.0'
    pod 'SlideMenuControllerSwift', '~> 3.0'
end


pod 'GoogleAnalytics-iOS-SDK'


pod 'KVNProgress'

**Comment by zhigang1992** [comment]
Can you show Podfile.lock as well?

**Comment by rudian** [comment]
PODS:
  - Alamofire (4.0.0)
  - GoogleAnalytics-iOS-SDK (3.12):
    - GoogleAnalytics-iOS-SDK/Core (= 3.12)
  - GoogleAnalytics-iOS-SDK/Core (3.12)
  - KVNProgress (2.3)
  - SlideMenuControllerSwift (3.0.0)
  - SwiftyJSON (3.0.0)

DEPENDENCIES:
  - Alamofire (~> 4.0)
  - GoogleAnalytics-iOS-SDK
  - KVNProgress
  - SlideMenuControllerSwift (~> 3.0)
  - SwiftyJSON (= 3.0.0)

SPEC CHECKSUMS:
  Alamofire: fef59f00388f267e52d9b432aa5d93dc97190f14
  GoogleAnalytics-iOS-SDK: 13241762fa4aea845eb75bef6c0da3427a26e7b3
  KVNProgress: d0459bfa4dca0379cdba5c038326ea34e9fc2df9
  SlideMenuControllerSwift: 9c0a84f9a3fba51681debd7be77617094562ebcc
  SwiftyJSON: f57b2b44bc166617372d1c70773591fe9f0f5fd4

PODFILE CHECKSUM: 3d6d6a92a0d9c4b5c57fee59896ac8559fdc1266

COCOAPODS: 1.0.1

**Comment by zhigang1992** [comment]
Can you try for looping on json["main"].dictionaryValue Instead?

**Comment by rudian** [comment]
@zhigang1992  xcode shown error
value of type 'JSON?' has no member 'dictionaryValue'

**Comment by zhigang1992** [comment]
hm, I've no clue how to reproduce this.

Can you maybe create a quick demo project that domes this?

**Comment by rudian** [comment]
hi , i already solve it

i just change version from 3.0.0 to 3.0 and pod below alamofire , then just fixed

```
target 'x' do
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON', '~> 3.0'
    pod 'SlideMenuControllerSwift', '~> 3.0'
end
```

**Comment by zhigang1992** [comment]
This has been addressed in https://github.com/SwiftyJSON/SwiftyJSON/pull/653
Please update to version `3.1.0`
