### ISSUE TITLE
Swift 3 Alamofire JSON conversion problem

### ISSUE THREAD

**Issue by sree127** [SwiftyJSON/SwiftyJSON#637]
I'm not able to convert the `response` to `JSON`

let jsonResponse = JSON(response.result.value)

And I'm getting this : 

```
JSON(rawString: "", rawNumber: 0, rawNull: <null>, rawArray: [], rawDictionary: ["status": success, "data": {
  }], rawBool: false, _type: SwiftyJSON.Type.dictionary, _error: nil)
```
This used to work perfect with older version. Any idea?

**Comment by zhigang1992** [comment]
Can you provide what exactly is in `response.result.value`?

Is it
```
["status": success, "data": {}]
```

**Comment by sree127** [comment]
No. It has proper values : 

```
[
  "status": "success",
  "data": [
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQxLCJpc3MiOiJodHRwOlwvXC9zdGjoxNDc"
  ]
]
```
This happens with the all the response that I'm parsing. 

Also, this started happening once I switched to Swift 3. The older version is working fine.

**Comment by zhigang1992** [comment]
How did you switched to swift3?

**Comment by zhigang1992** [comment]
Because I just published it like one hour ago. 😄

**Comment by sree127** [comment]
Lol. Damn. I've been using [this](https://github.com/IBM-Swift/SwiftyJSON/blob/master/Source/SwiftyJSON.swift)
😄 😄
Do you think this might be the issue?

**Comment by zhigang1992** [comment]
I've actually not look at their branch yet. :(
But can you give the new one a go and let me know?

if you're using cocoapods, the version should be `3.0.0`

**Comment by sree127** [comment]
Hey @zhigang1992, its working with `3.0.0.` Thanks a lot :) 👍
