### ISSUE TITLE
Swifty JSON Not Working 

### ISSUE THREAD

**Issue by uday-mshr** [SwiftyJSON/SwiftyJSON#638]
my JSON Respose is 
{
    code = 1;
    document =     (
                {
            Address1 = "<null>";
            Address2 = "<null>";
            City = "<null>";
            CompanyID = 1;
            CompanyName = Innohabit;
            ContactNumber = "<null>";
            Designation = "<null>";
            DesignationID = 36;
            DesignationName = dev;
            Email = "uday.mishra@Gmail.com";
            FCMRegistrationToken = "";
            GCMRegistrationToken = "";
            Gender = Male;
            ID = 9;
            IsActive = 1;
            IsFirstLogin = 1;
            LastLogin = "2016-09-21 05:45:33";
            Name = "Uday Mishra";
            Password = "";
            ProfilePic = "";
            RegisterationDate = "2016-03-04 07:42:42";
            UserTwitter = "<null>";
            Username = "uday.mishra@Gmail.com";
        }
    );
    message = "Record found";
    status = success;
}

And Trying to Convert the respose using Swifty Json Like this 

```
            case .success:
            print(response)

            let jsonResponse = JSON(response.data)
            print("JSON")
            let jsonData = jsonResponse["document"]
            print(jsonResponse)
            print(jsonData[0])
```

But I am Not getting the desired result, the Output is 
`{
    code = 1;
    document =     (
                {
            Address1 = "<null>";
            Address2 = "<null>";
            City = "<null>";
            CompanyID = 1;
            CompanyName = Innohabit;
            ContactNumber = "<null>";
            Designation = "<null>";
            DesignationID = 36;
            DesignationName = dev;
            Email = "uday.mishra@Gmail.com";
            FCMRegistrationToken = "";
            GCMRegistrationToken = "";
            Gender = Male;
            ID = 9;
            IsActive = 1;
            IsFirstLogin = 1;
            LastLogin = "2016-09-21 05:45:33";
            Name = "Uday Mishra";
            Password = "";
            ProfilePic = "";
            RegisterationDate = "2016-03-04 07:42:42";
            UserTwitter = "<null>";
            Username = "uday.mishra@Gmail.com";
        }
    );
    message = "Record found";
    status = success;
}
JSON
unknown
null`

As u can see the response is getting printed ,but the **print(jsonResponse)** and  **print(jsonData[0])**
is printing  **Unknown** and **null** can anyone help me how i can serialise the data properly into JSON format from DataRespose<any>

**Comment by zhigang1992** [comment]
Can you try printing `response.data`, and see if it's nil by any chance?
Also, can you try printing 
```
print(try! NSJSONSerialization.JSONObjectWithData(response.data, options: .AllowFragments))
```

**Comment by Vkt0r** [comment]
Are you using Alamofire? Because if it's the case and you're calling for example another response handler distinct of `responseJSON` then you cannot call the initializer `JSON(response.data)` of SwiftyJSON as you did in your code, you need to call:

    JSON(data: dataFromNetworking) 

as @zhigang1992 proposed above or 

    if let dataFromString = jsonString.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false) {
         let json = JSON(data: dataFromString)
    }

In case your JSON come as a `String` object in case you use `responseString` from Alamofire
