### ISSUE TITLE
Current state and future of SwiftyJSON

### ISSUE THREAD

**Issue by ldiqual** [SwiftyJSON/SwiftyJSON#639]
@tangplin @lingoer Pinging you both since you seem to be the two only members of the SwiftyJSON organization.

I see a bunch of issues and pull requests related to Swift 3/Xcode 8 support. The `swift3` branch has remained untouched for 3 months now, and it is *not* compatible with the latest Swift build. The latest commit on `master` is now 3 months old as well. Most of the open issues could be closed by merging one single of those PRs (most of them actually have a viable source code that is swift 3 compatible). I believe that production apps that use SwiftyJSON and swift3 at the moment need to rely on an external, untrusted code which can be a security and stability risk.

SwiftyJSON is a *very* popular library in the Swift OSS world: 11k stars on github, 89k app installs (10k just for last week) according to cocoapods. A bunch of apps rely heavily on SwiftyJSON in production. There is an urgent need for a swift 3 compatible version of the library.

I'm opening this issue as an opportunity for you to jump in and describe how you envision the future of the library/project. Are you still maintaining the library? Should you add more contributors to the team? Should the ownership be transferred to an organization with more resources?

In terms of immediate actionable items, can one of you take a couple hours to review, merge, and release a new version of the library for swift 3 so we can stop relying on external – untrusted – PRs? It would be fantastic.

**Comment by MrAlek** [comment]
Couldn't agree more. This NEEDs to be addressed. If you can't keep up with the maintenance, please let more contributors into the team or look to transfer the ownership.

**Comment by MKGitHub** [comment]
This is why I try to avoid using open source ;-)

**Comment by zhigang1992** [comment]
Just merged. :(

Anyway, sincerely sorry about not being active enough in maintaining this repo.
We should have done it earlier.

**Comment by ldiqual** [comment]
@zhigang1992 Fantastic news! Thank you so much for taking time to review and merge those changes.

As a side note, if you guys need more contributors, I'm offering my help. My company (@takescoop) is actively involved in the OSS world and I'd be happy to help manage issues/PRs and work on new features, taking a couple hours on my weekly schedule. Let me know if you're interested.

Closing this issue, now that the swift 3 concern has been addressed.
