### ISSUE TITLE
Convert to Current Swift Syntax

### ISSUE THREAD

**Issue by tgb20** [SwiftyJSON/SwiftyJSON#643]
Whenever I try and install the newest SwiftyJSON through cocoapods and then open the project I am prompted with convert to current swift syntax even though SwityJSON 3 supports Swift 3.

If I say later it says Module Compiled with Swift 3 cannot be imported in Swift 2.3

**Comment by DavidLari** [comment]
What version of Cocoapods you using? You should have 1.1 RC 2 if you want it to work.

**Comment by tgb20** [comment]
I am using 1.1.0.rc.2. I reinstalled cocoapods and I no longer get the prompt to switch but it tells me "No Such Module 'SwiftyJSON'"

**Comment by tgb20** [comment]
Fixed it by wiping the pod information inside Xcode then deleting all files associated with SwiftyJSON and starting the install from scratch. I must not have completely removed the old version
