### ISSUE TITLE
try rawData() throws and rawString() returns nil

### ISSUE THREAD

**Issue by arrrggghhh** [SwiftyJSON/SwiftyJSON#645]
Hi,

I'm trying to get raw data or string representation of json object to convert to Data object, but getting error and nil.

The type of json object data:
![image](https://cloud.githubusercontent.com/assets/19325420/18776116/f64e189c-81a1-11e6-9bb4-d30e665e7886.png)

How I set data to json object:
![image](https://cloud.githubusercontent.com/assets/19325420/18776122/00c51bfe-81a2-11e6-98c2-698a2a090f45.png)

Trying to get Data object:
![image](https://cloud.githubusercontent.com/assets/19325420/18776127/0bc6025c-81a2-11e6-8974-a540eddef46f.png)
(also tried with specific writing option)

Trying to get raw data in other forms:
![image](https://cloud.githubusercontent.com/assets/19325420/18776143/330d6940-81a2-11e6-8ba7-3969ff64c77a.png)

Results:
```swift
try json.rawData() // Moved to catch clause.
json.rawValue // bunch of data I set in normal Dictionary representation?
json.rawString() // nil
```

json.rawValue
![image](https://cloud.githubusercontent.com/assets/19325420/18776195/8f6b7d80-81a2-11e6-90d1-1bf50aaa11e0.png)

Any idea would be very nice.
Thanks.

**Comment by KashanDanish** [comment]
Also facing same issue, for me it appeared after using swift3 branch

**Comment by zhigang1992** [comment]
<img width="1512" alt="screen shot 2016-09-23 at 4 18 06 pm" src="https://cloud.githubusercontent.com/assets/1057756/18778907/58224eba-81a9-11e6-830c-1f758ea8eea0.png">

Seems working fine here.
Can you try the latest master branch?

**Comment by arrrggghhh** [comment]
Hi,

Thanks for your responses.

I changed Podfile:
```
# from
pod 'SwiftyJSON'
#to
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'master'
```

Result is the same.

But when I run

```swift
var json: JSON = [:]

json["hello"].arrayObject = [String]()
json["world"].dictionaryObject = [String:Any]()
json["Test"].arrayObject = [[String:Any]()]

print(json.rawString())
```
rawString() indeed made a string result.

![image](https://cloud.githubusercontent.com/assets/19325420/18779854/b56bee80-81b5-11e6-89a0-d54676f19745.png)

So I tried this to see if one of value arrays or dictionaries is causing this:

![image](https://cloud.githubusercontent.com/assets/19325420/18780160/30cae292-81b7-11e6-89e2-5299472f8fd8.png)

Results were:
```swift
JSON1: nil
```

JSON2 to JSON5 have non-nil results.

I look at the types of data for JSON1 and I found out that during Swift 3 conversion, I made a mistake where using `base64EncodedData` instead of `base64EncodedString` for a variable that should be a string.

So, it was my mistake :)

The particular functionality I need now works!

**Comment by zhigang1992** [comment]
sweet, good to know

🍻 

feel free to reopen this if needed.
