### ISSUE TITLE
Swift 3 upgrade - 18 errors

### ISSUE THREAD

**Issue by LiLmakr** [SwiftyJSON/SwiftyJSON#646]
I just upgraded to xCode 8 and now I am getting this errors

![image](https://cloud.githubusercontent.com/assets/22390398/18779352/f1c9d21c-8178-11e6-9f46-b9e736de06d3.png)
![image](https://cloud.githubusercontent.com/assets/22390398/18779355/fb2798ee-8178-11e6-90ac-1d1d140d106a.png)

**Comment by zhigang1992** [comment]
You've to upgrade to version 3.0.0 in CocoaPods,

Also you have to use cocoapods rc for it to work with Xcode8.

```
sudo gem install cocoapods -v 1.1.0.rc.2
```

Feel free to reopen this if still running into issues.

**Comment by LiLmakr** [comment]
Still getting the errors...

**Comment by LiLmakr** [comment]
Still getting the errors

**Comment by zhigang1992** [comment]
Can you paste in `Podfile.lock` & `Podfile`?

**Comment by LiLmakr** [comment]
Oh it didn't upgrade to SwiftyJSON 3.0.0 by itself... Fixed it now :)
