### ISSUE TITLE
Swift 3: NSURL to URL

### ISSUE THREAD

**Issue by wvteijlingen** [SwiftyJSON/SwiftyJSON#649]
Swift 3 drops the `NS` prefix for a lot of classes, including `NSURL`. I think that the URL extension in the the 3.0.0 release has not yet been updated to use `URL` instead of `NSURL`.

**Comment by zhigang1992** [comment]
Just merged https://github.com/SwiftyJSON/SwiftyJSON/pull/652

Will be part of 3.1 release.
