### ISSUE TITLE
Swift 3 loop nil will infinite loop

### ISSUE THREAD

**Issue by gewill** [SwiftyJSON/SwiftyJSON#651]

**Comment by gewill** [comment]
`swift
    func testNUllArray() {
        var count = 0
        for (_, _): (String, JSON) in JSON.null {
            count += 1
            print(count)
        }
        XCTAssertEqual(count, 0)

    }
`

**Comment by zhigang1992** [comment]
Can you try out https://github.com/SwiftyJSON/SwiftyJSON/pull/653 and see if it fixes the issue?

**Comment by gewill** [comment]
#653 fixed the bug, and pass the test, thanks.
