### ISSUE TITLE
Build Issue while first installation

### ISSUE THREAD

**Issue by gsujathap** [SwiftyJSON/SwiftyJSON#654]
![screen shot 2016-09-26 at 3 33 05 pm](https://cloud.githubusercontent.com/assets/16931145/18860901/e5f5fc26-849e-11e6-9ded-3c0a5ccac262.png)

I have done swiftyjson installation using cocoapods after that build failed error occurs. How to resolve this issue?

**Comment by zhigang1992** [comment]
Seems like the screenshot hadnt finish uploading yet.
Can you try it again?

**Comment by gsujathap** [comment]
Please resolve this issue ASAP. Thank you in advance.

**Comment by gsujathap** [comment]
I have resolved this issue by updating SWIFT with latest version from 2.0 to 3.0

**Comment by zhigang1992** [comment]
If you are using swift 2.3 please use swift2 branch, or 2.4.0 on cocoapods.

https://github.com/SwiftyJSON/SwiftyJSON/issues/647

**Comment by gsujathap** [comment]
Now, I am using Swift 3.0. How to resolve this issue?

**Comment by zhigang1992** [comment]
Can you try https://github.com/SwiftyJSON/SwiftyJSON/issues/647

**Comment by TPetterson** [comment]
Had the same issue. I had Xcode 8.0 and there wasn't any updates in appstore. Solved by downloading Xcode 8.1 from https://developer.apple.com/download/.

**Comment by justdan0227** [comment]
For the time being you can just attempt to save after Xcode 8.0 has attempted to update the file to Swift3.  You will get a lock message and if you then click on cancel, then clean the project and build it should clean up (it may also ask you to update your build file which you can go ahead and let it do).

**Comment by zhigang1992** [comment]
Right, that's because of the cocoapods issue

see https://github.com/SwiftyJSON/SwiftyJSON/issues/647 for more detail

**Comment by justdan0227** [comment]
thanks @zhigang1992 !  Didn't know that.  What version of cocoapods does not have that issue?

**Comment by zhigang1992** [comment]
`1.1.0.rc.2` or higher

**Comment by justdan0227** [comment]
Ahhh thanks.. I have a Ruby on Rails project that has to use 0.32.0 so will have to use this work around for now.

**Comment by zhigang1992** [comment]
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
```

**Comment by justdan0227** [comment]
Awesome!  Thanks!
