### ISSUE TITLE
Problems with converting to swift 3 syntax

### ISSUE THREAD

**Issue by andrewjmeier** [SwiftyJSON/SwiftyJSON#656]
I'm trying to update to swift 3 and I have SwiftyJSON 3.1.0 installed. There's one line that xcode is trying to convert before it will allow me to switch over. (ignore all the errors on the right side)
![screen shot 2016-09-26 at 10 39 58 am](https://cloud.githubusercontent.com/assets/3655258/18845244/c7e5dd4c-83d5-11e6-86d0-c16ebbd985c9.png)

**Comment by andrewjmeier** [comment]
Turns out if you change it to what the syntax updater wants and then change it right back immediately it works fine.

**Comment by zhigang1992** [comment]
You have to upgrade to cocoapods to pre release version or add a extra script.

Refer to swift 3 issue.

**Comment by zhigang1992** [comment]
https://github.com/SwiftyJSON/SwiftyJSON/issues/647
