### ISSUE TITLE
Readme not uptaded for 2.4.0

### ISSUE THREAD

**Issue by tirrorex** [SwiftyJSON/SwiftyJSON#658]
Hello, still on the swift 2 branch.
Trying to compile the project after and update and it seems that isExists isn't there anymore and has been replace by exists.
Could you guys update the readme for other users please?

**Comment by zhigang1992** [comment]
Nice catch.

**Comment by zhigang1992** [comment]
Addressed in https://github.com/SwiftyJSON/SwiftyJSON/commit/54017d514a87b2b855b407131292c510cdeb65f8
