### ISSUE TITLE
Enum case 'Success' not found in type 'Result<Any>'

### ISSUE THREAD

**Issue by donadley** [SwiftyJSON/SwiftyJSON#659]
I am working with this code snippet below from the SwiftyJson docs and I am receiving the errors **Enum case 'Success' not found in type 'Result<Any>** and **Enum case 'Failure' not found in type 'Result<Any>.** Please help me fix this issue. I am using Swift 3.0 and SwiftyJson 3.1.0.

```
Alamofire.request(.GET,` url).validate().responseJSON { response in
    switch response.result {
    case .Success(let value):
        let json = JSON(value)
        print("JSON: \(json)")
    case .Failure(let error):
        print(error)
    }
}

```

**Comment by zhigang1992** [comment]
What version of Alamofire are you using?

**Comment by jeneumeier** [comment]
Enums are lower case, so change to .success and .failure in Swift 3

**Comment by donadley** [comment]
Awesome @jeneumeier. Making success and failure lowercase did the trick. Thank you.

**Comment by zhigang1992** [comment]
@jeneumeier nice catch, let me update README as well. 

🍻
