### ISSUE TITLE
To many errors on Xcode 7.3.1

### ISSUE THREAD

**Issue by zhakonai** [SwiftyJSON/SwiftyJSON#661]
To many errors on Xcode 7.3.1
Over 123 errors

<img width="360" alt="2016-09-28 9 35 46" src="https://cloud.githubusercontent.com/assets/16617536/18899996/34cadbee-855f-11e6-9751-27c3623e2b49.png">

**Comment by nicholas-lonsinger** [comment]
Are you using the master branch? Perhaps trying using an older release as the master is now set for swift 3 and you are still on the older Xcode.

**Comment by zhakonai** [comment]
Thank you. Already find

**Comment by zhigang1992** [comment]
closing, feel free to reopen this if needed
