### ISSUE TITLE
Could you attach prebuilt framework for Carthage?

### ISSUE THREAD

**Issue by kazuhiro4949** [SwiftyJSON/SwiftyJSON#662]
I'm making use of SwiftyJSON via Carthage. 
Carthage enables us to provide prebuilt frameworks.  We can download them directly without any local build time required.
Please attach the prebuilt Carthage libraries to the Github release.

https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

example:
https://github.com/realm/realm-cocoa/releases/tag/v2.0.0

**Comment by zhigang1992** [comment]
This is a really good idea, I'll look into this this week. 

Thanks for proposing this.

**Comment by kazuhiro4949** [comment]
Thanks for your response😄! I'm looking forward to attaching the prebuilt fremework.

My projects is built on swift2.3 environment. I'd appreciated that you could attach both 2.3 and 3.0 versions.

**Comment by zhigang1992** [comment]
Just attached

Feel free to reopen this if you run into any issues.

🍻

**Comment by kazuhiro4949** [comment]
Thanks a lot! 👏  I'll try to use it!
