### ISSUE TITLE
Source code comments

### ISSUE THREAD

**Issue by kengruven** [SwiftyJSON/SwiftyJSON#663]
In SwiftyJSON.swift, for Swift 3, all of the `AnyObject`s have been converted to `Any`, except for 2 in the comments:

```
//Optional [String : AnyObject]
public var dictionaryObject: [String : Any]? {
```

and:

```
//Optional [AnyObject]
public var arrayObject: [Any]? {
```

**Comment by zhigang1992** [comment]
hm, thanks for the headup. will fix

**Comment by zhigang1992** [comment]
Seems like there are a few places in `README.md` as well.

Can you help make a PR for these fixes?

Or I can fix it a bit later. 😄
