### ISSUE TITLE
Swift 3: Cannot convert return expression of type 'Int32?' to return type 'Int?'

### ISSUE THREAD

**Issue by marcusleon** [SwiftyJSON/SwiftyJSON#665]
We are upgrading to SwiftyJSON Swift 3 with CocoaPods config `pod 'SwiftyJSON', '3.1.0'`.   

We are getting this error: 

> /Users/xxx/Documents/iOS/xxx/Pods/SwiftyJSON/Source/SwiftyJSON.swift:866:33:
> Cannot convert return expression of type 'Int32?' to return type
> 'Int?'

Error is on the return statement in SwiftyJSON.swift:

    public var int: Int? {
        get {
            return self.number?.int32Value
        }
        set {
            if let newValue = newValue {
                self.object = NSNumber(value: newValue)
            } else {
                self.object = NSNull()
            }
        }
    }

Anyone know what the issue is?  Is this an issue with our CocoaPods config or with SwiftyJSON?

**Comment by zhigang1992** [comment]
Are you on Xcode8?

**Comment by marcusleon** [comment]
I am.  Realized that the supported version is 3.0.0 not 3.1.0.   Used that version and I was good.

https://github.com/SwiftyJSON/SwiftyJSON/issues/647

**Comment by zhigang1992** [comment]
`3.1.0` should also work, I'll look into it.

**Comment by mostafamaan** [comment]
same thing for me but with both version on 3.0.0 and 3.1.0 in both i get "Cannot convert return expression of type 'Int32?' to return type 'Int?'"
xcode 8A218a

**Comment by ryl** [comment]
I'm having the same problem with SwiftyJSON 3.1.0 and Xcode 8A218a.

**Comment by prikshitgupta** [comment]
I am having same issue

**Comment by casamia918** [comment]
I changed the int32Value to intValue. And the build succeeded

**Comment by wuyazi** [comment]
I am having same issue

**Comment by jqzhao** [comment]
I'm having the same issue with SwiftyJSON 3.0.0. Any solution to this?

**Comment by masuhara** [comment]
I have same issue.
Xcode8.1, Swift3.0.1, SwiftyJSON3.1.1

**Comment by salvonos** [comment]
same issue.. changed to intValue
