### ISSUE TITLE
Cant find swift 3 branch

### ISSUE THREAD

**Issue by talhaqamar** [SwiftyJSON/SwiftyJSON#666]
Cant find the branch for swift 3 .Thanks

**Comment by talhaqamar** [comment]
Even thought swift 3 branch is not present now.Earlier it was present

But i try adding the framework manually after downloading from below link.
[link](https://github.com/SwiftyJSON/SwiftyJSON/releases/tag/3.1.0)

**Comment by mitchellporter** [comment]
@talhaqamar Pretty sure the Swift 3 branch doesn't exist anymore because `master` now supports Swift 3.

**Comment by talhaqamar** [comment]
I tried using master branch but it was integrating well.So i used the framework available on above link.
