### ISSUE TITLE
Older versions?

### ISSUE THREAD

**Issue by oktayayr** [SwiftyJSON/SwiftyJSON#668]
Hi,

I want to user version 2.3.3 but it is unavailable. However, only 2.4.0 is available, how can i use versions older than 2.4.0?

Thanks

**Comment by jeroenleenarts** [comment]
I'd say use the direct GIT support offered through CocoaPods.

This document contains info on that. Tags/versions of SwiftyJson are listed here: https://github.com/SwiftyJSON/SwiftyJSON/releases

**Comment by zhigang1992** [comment]
@jeroenleenarts thanks you pointing it out, can I ask why would you prefer to stay on a old version?

**Comment by zhigang1992** [comment]
I've just published the missing `2.3.3` to cocoapods.

🍻
