### ISSUE TITLE
Adoption to Swift.NilLiteralConvertible creates unpredictable cases

### ISSUE THREAD

**Issue by Igor-Palaguta** [SwiftyJSON/SwiftyJSON#670]
Hello,

Spent some time to understand, why code below does not work. And as a result nil is implicitly converted to JSON.

```
let json = JSON([:])
let childJSON = json["child"].isExists() ? json : nil
```

```childJSON``` is instance of ```JSON```, and never ```nil```

Is this NilLiteralConvertible adoption really so important? Probably better to create convenience constructor without adoption to NilLiteralConvertible?

Thanks

**Comment by zhigang1992** [comment]
I think it's a good point, I believe it was adopted at a early stage of SwiftyJSON.

I'm not exactly sure if it's used widely.

Let's get rid of it in the next release and see what happens.

Cheers.

**Comment by zhigang1992** [comment]
Seems like it's used this way in a lot of the places.

`json == nil`

which is rely on `JSON` being `NilLiteralConvertible`.

We might need to think further on how to approach this.

**Comment by Igor-Palaguta** [comment]
It is more like comparison with nil, not with json that contains null. For this purpose more clear to use json == JSON.null. Is this comparison really used a lot? As a solution to deprecate this for now, and remove this in next versions

```
extension JSON: Swift.NilLiteralConvertible {

    @available(*, deprecated, message="use JSON.null instead. Will be removed in future versions")
    public init(nilLiteral: ()) {
        self.init(NSNull())
    }
}
```

**Comment by Igor-Palaguta** [comment]
Another solution, remove NilLiteralConvertible conformance, and add:

```
public func ==(lhs: JSON, rhs: JSON?) -> Bool {
    guard let rhs = rhs else {
        return lhs.type == .Null
    }

    return lhs == rhs
}
```

Probably it covers your case, but I think better disallow comparison with nil. And to have explicit comparison with null json

**Comment by zhigang1992** [comment]
I actually tried

```
extension JSON: Swift.NilLiteralConvertible {

    @available(*, deprecated, message="use JSON.null instead. Will be removed in future versions")
    public init(nilLiteral: ()) {
        self.init(NSNull())
    }
}
```
Doesn't seems to be quiet working.

**Comment by Igor-Palaguta** [comment]
I have this warning
```
'init(nilLiteral:)' is deprecated: use JSON.null instead. Will be removed in future versions
```
I have swift2.3, probably if you are using swift3 you should use ":" instead of "="

**Comment by zhigang1992** [comment]
If that's the case, I think we should just go a head a do it. :)

**Comment by Igor-Palaguta** [comment]
to create really optional variable this workaround works:
Swift2 version
```
let childJSON = json["child"].isExists() ? json : Optional.None
```

Swift3 version:
```
let childJSON = json["child"].exists() ? json : Optional.none
```

**Comment by zhigang1992** [comment]
🍻

**Comment by RaziPour1993** [comment]
Swift 3 :

Use from "exists()"

```
if item["examples"].exists() {
    print("Nil")
}else{
    print("Full")
}

```
