### ISSUE TITLE
My podspec is not passing validation due to SwiftyJSON

### ISSUE THREAD

**Issue by clrung** [SwiftyJSON/SwiftyJSON#672]
Hello,

My [WMATAFetcher](https://github.com/clrung/WMATAFetcher) pod cannot be published due to errors in SwiftyJSON.  I ran `pod spec lint --verbose` and copied its [output to Pastebin here](http://pastebin.com/xTYN1XTd).

Things I have tried:
* Updated to the prerelease version of Cocoapods (1.1.0.rc.2)
* `pod repo update`
* [Cleared the Cocoapods cache](https://gist.github.com/mbinna/4202236)

`pod spec lint` shows that I'm using SwiftyJSON 3.1.0, so I think I have things configured properly.  Here is the [podspec](https://github.com/clrung/WMATAFetcher/blob/master/WMATAFetcher.podspec) and [Podfile](https://github.com/clrung/WMATAFetcher/blob/master/Podfile) that I am using.  That repo is up to date with my local project.

There are no errors or warnings in any of the targets (cross platform) in my project in Xcode 8.0 (8A218a).

Thank you in advance for the help!

**Comment by brennick** [comment]
Same error for [SwiftyConcur](https://github.com/concurlabs/SwiftyConcur), hoping we can get this fixed soon!

**Comment by zhigang1992** [comment]
@brennick @clrung you have to add `.swift-version` to you project root.
Otherwise, cocoapods will think you're using swift2.3 instead

**Comment by clrung** [comment]
Thank you, @zhigang1992!!
