### ISSUE TITLE
Iterating through JSON

### ISSUE THREAD

**Issue by travisday** [SwiftyJSON/SwiftyJSON#674]
I made a little JSON file to test
`var json: JSON =  ["name": "Jack", "name": "Travis"]`

and I want to append each name to my Array that feeds into a table view.

this works to load one key to the table

```

if let name = json["name"].string {
            self.shows.append(Show(name: name))

        } else {
            print(json["name"].error)
        }
```

but eventually I want to be able to add large json files with lots of names so I attempted to loop.

```
if let name = json["name"].string {
            for name in json {
                self.shows.append(Show(name: name))
            }
        }else {
                print(json["name"].error)
}
```

However I get an error on the `self.shows.append(Show(name: name))` line 
`Cannot Conver value of type '(String,JSON)' to expected arguement type 'String'`

**Comment by zhigang1992** [comment]
Not exactly sure if it helps

```swift
if let *name* = json["name"].string {
            for name in json {
                self.shows.append(Show(name: name))
            }
        }else {
                print(json["name"].error)
}
```
Change that `if let name` to something else?

**Comment by zhigang1992** [comment]
feel free to reopen this if needed

**Comment by travisday** [comment]
@zhigang1992 that didn't help I get the same error, I changed it to `title` but no difference. Also I am not sure how to open it back up hahah

**Comment by zhigang1992** [comment]
so what exactly is `json`, is it a dictionary or a arry?

If it's a dictionary, then there should only be one key named `name`.

If you're trying to loop through key and values, it should be

            for (name, value) in json {
                self.shows.append(Show(name: name))
            }

**Comment by travisday** [comment]
@zhigang1992 well it needs to be an array hahaha, but your solution used with `["name": "Jack"]` just prints out `name` not the value of name `Jack`

**Comment by travisday** [comment]
`if let JSON = response.result.value {
                for title in JSON as! [AnyObject]{
                    self.shows.append(Show(name: title as! String, description: "Is the best"))
                }
`

this worked for me

**Comment by wongzigii** [comment]
Closing. Feel free to reopen if need.
