### ISSUE TITLE
JSON object including Int64 not working

### ISSUE THREAD

**Issue by alynmuntean** [SwiftyJSON/SwiftyJSON#677]
Hello, 

I'm trying to create a JSON object that has a key-value pair of "String": Int64 type. I want to use it for unit testing for some objects that have a timestamp in milliseconds (e.g. 1476101294000). I do get the following error "Optional(Error Domain=SwiftyJSONErrorDomain Code=999 "It is a unsupported type" UserInfo={NSLocalizedDescription=It is a unsupported type})" when I'm trying to retrieve the json["timestamp"].int64. Bellow is the code:

```
let json = JSON(["timestamp": 1476101302000 as Int64])
        if let timestamp = json["timestamp"].int64 {
            print(timestamp)
        } else {
            print(json["timestamp"].error) // Enters here...
        }
```

Thank you in advance,
Alin

**Comment by wongzigii** [comment]
Hey @alynmuntean I tried you code and confirmed that works. Would you like to share some progress on this ?

<img width="825" alt="qq20161107-1 2x" src="https://cloud.githubusercontent.com/assets/7384288/20059949/c1b0eda2-a533-11e6-83c7-10404f32ded8.png">

**Comment by alynmuntean** [comment]
Hello @wongzigii, sorry for my late response. I just updated the framework but still getting the same error: "Error Domain=SwiftyJSONErrorDomain Code=999 "It is a unsupported type" UserInfo={NSLocalizedDescription=It is a unsupported type}".

![screen shot 2016-11-18 at 17 13 12](https://cloud.githubusercontent.com/assets/22174478/20434854/763f9314-adb2-11e6-9b46-64a37306369c.png)

Thank you for your time,
Alin

**Comment by wongzigii** [comment]
@alynmuntean Would you mind upload a sample project to reproduce this ?

**Comment by alynmuntean** [comment]
Here it is: [SwiftyJSONSample.zip](https://github.com/SwiftyJSON/SwiftyJSON/files/600254/SwiftyJSONSample.zip)

Xcode Version 8.0 (8A218a), iPhone 5 (9.3) simulator. Check ViewControllers' "viewDidLoad()".

**Comment by wongzigii** [comment]
Everything works fine on my laptop. Have you changed the build settings? Are you running on a 32bit machine?

**Comment by alynmuntean** [comment]
I didn't change anything, what I sent to you is what I tested. I have a Macbook Pro (Late 2013), macOS Sierra 10.12.1 (64bit).

**Comment by ldiqual** [comment]
@alynmuntean What are you running this code on? A simulator? If yes, which one? If no, which device then?

**Comment by alynmuntean** [comment]
Hi @ldiqual, tested on: iPhone 5 (iOS 10.0.1) - real device, iPhone 6S (iOS 9.3) - simulator, iPhone 7 - simulator, same result on all devices.

**Comment by ldiqual** [comment]
@alynmuntean Awesome! Glad it works with the new Xcode. Closing now.
