### ISSUE TITLE
ios 10 not installing pod file

### ISSUE THREAD

**Issue by shivam5x** [SwiftyJSON/SwiftyJSON#680]
Hi,
 I am getting this issue : -

FiveExceptions1s-Mac-mini:JSONGET fiveexceptions$ pod install
Analyzing dependencies
[!] Unable to find a specification for `SwiftyJSON`

How can i sort out this issue.Please let me know.

Thanks

**Comment by wongzigii** [comment]
rm -rf ~/.cocoapods/repos/master
    // this could take a long time to go,  please wait.
    pod install

**Comment by ldiqual** [comment]
@shivam5x This is now a month old and @wongzigii 's solution seems reasonable. I'm gonna go ahead and consider the issue fixed, let me know if you need to reopen!
