### ISSUE TITLE
Working in simulator but not on device

### ISSUE THREAD

**Issue by travisday** [SwiftyJSON/SwiftyJSON#683]
I am having trouble finding where this problem lies. I am using Alamofire to get a JSON array and then I iterate through each item and append it to my swift array which then displays it on a UITable.

`Alamofire.request("http://104.131.134.48:8090/all", method: .get).responseJSON { response in
            if let JSON = response.result.value {
                for title in JSON as! [AnyObject]{
                    self.shows.append(Show(name: title as! String, description: "Is the best", image: #imageLiteral(resourceName: "blowgun")))
                }
                print("JSON: \(JSON)")
                print("Shows: \(self.shows)")
            }
`
It works fine and populates the Table on the simulator but it does not when I test on a real device. My server still says it sent the JSON but I cannot find out why it will not work on the real device.

**Comment by mitchellporter** [comment]
>My server still says it sent the JSON but I cannot find out why it will not work on the real device.

Have you set a breakpoint in Almofire's completion handler? Is it hitting on simulator and on device? Have you tried logging these:

```
print("Request: \(response.request)")
print("Response: \(response.response)")
print("Error: \(response.error)")
```

**Comment by wongzigii** [comment]
Closing.
