### ISSUE TITLE
XCode 8.1 + Carthage = compiled module mismatch

### ISSUE THREAD

**Issue by Xorcist77** [SwiftyJSON/SwiftyJSON#690]
I just updated to XCode 8.1. to test my application's functionality on iOS 10.1, and ran into an issue.

The error I get is: "Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1."

And it points to the SwiftyJSON binary installed via Carthage.

**Comment by hdoria** [comment]
+1

**Comment by zhigang1992** [comment]
Can you try skip prebuilt binary?
I believe it's --skip-prebuilt-binary

**Comment by hdoria** [comment]
Worked with --no-use-binaries. Thanks.

**Comment by ldiqual** [comment]
Closing as duplicate of https://github.com/SwiftyJSON/SwiftyJSON/issues/716 which has a more extensive comment thread. Let's track the issue there. Thanks!
