### ISSUE TITLE
Realm

### ISSUE THREAD

**Issue by SeongBrave** [SwiftyJSON/SwiftyJSON#691]
Hi , swiftyjson 实例化的model 不支持Realm 数据库吗？有什么办法可以实现解析实例化的model 用于Realm缓存

**Comment by ldiqual** [comment]
@SeongBrave I believe that you didn't get an answer because your question wasn't in English. I think most contributors here don't understand Chinese and I'd suggest to edit your question in English so we can respond appropriately. Ping me when it's good to go, thanks!

**Comment by wongzigii** [comment]
@SeongBrave I believe your issue is related to a approach to mapping realm-friendly model. I would suggest you to use https://github.com/Hearst-DD/ObjectMapper to handle that chore job.
