### ISSUE TITLE
int8 values of 0 and 1 are output as bool

### ISSUE THREAD

**Issue by mbj2011** [SwiftyJSON/SwiftyJSON#692]
Hi

This was really unexpected behaviour for me:

```
var result : JSON = [:]
result["what"].int8 = 1

print(result.rawString()!)
```

The output is:

```
{
  "what" : true
}
```

0 becomes false and any other number is output correctly.

**Comment by SumoSimo** [comment]
Created [PR](https://github.com/SwiftyJSON/SwiftyJSON/pull/717) for this issue
