### ISSUE TITLE
Performance diff in enumerations across JSON vs JSON.dictionaryValue in 3.1.1

### ISSUE THREAD

**Issue by adriansoghoian** [SwiftyJSON/SwiftyJSON#697]
Hello, 

I noticed in 3.1.1 there is a huge performance hit in enumerating over a JSON object vs. JSON.dictionaryValue in Swift 3. 

For example, iterating over a dictionary with ~400 keys like so: 

```
var testOneKeys: [String] = []
var testOneValues: [JSON] = []    

let testOneStart = DispatchTime.now()
for (key, value) in json {
    testOneKeys.append(key)
    testOneValues.append(value)
}

let testOneEnd = DispatchTime.now()        
let testOneDiff = testOneEnd.uptimeNanoseconds - testOneStart.uptimeNanoseconds
var milliseconds = testOneDiff / 1000000
print("time: \(milliseconds)") // 8846 milliseconds
```

This took over **8 seconds**.      

```
var testTwoKeys: [String] = []
var testTwoValues: [JSON] = []

let testTwoStart = DispatchTime.now()
for (key, value) in json.dictionaryValue {
    testTwoKeys.append(key)
    testTwoValues.append(value)
}

let testTwoEnd = DispatchTime.now()
let testTwoDiff = testTwoEnd.uptimeNanoseconds - testTwoStart.uptimeNanoseconds
milliseconds = testTwoDiff / 1000000
print("time: \(milliseconds)") // 18 milliseconds
```

This took **18 milliseconds**. I'm not sure what changed in 3.1.1 but the performance delta used to be indiscernible (though I never profiled it) in version 2.3.2, which I was previously using. 

Just wanted to flag - if there's an issue I'd be happy to work on a PR if someone points me in the right direction!

**Comment by ryl** [comment]
I'm also experiencing the same problem. Seems a few other are as well.
https://stackoverflow.com/questions/39900941/swifty-json-performance-degradation-with-swift3-xcode8-ios10

**Comment by cikpis** [comment]
Hi @zhigang1992! Is it possible to know when this fix will be released?

**Comment by wongzigii** [comment]
@cikpis FYI: https://github.com/SwiftyJSON/SwiftyJSON/releases/tag/3.1.3
