### ISSUE TITLE
Two 3.1.1 versions

### ISSUE THREAD

**Issue by zwang** [SwiftyJSON/SwiftyJSON#701]
As shown in https://github.com/SwiftyJSON/SwiftyJSON/releases 
Is this a mistake? Thanks.

**Comment by zettlunic** [comment]
I think the first 3.1.1 release has the wrong tag (`v3.1.1` instead of `3.1.1`)

**Comment by zwang** [comment]
Got it. Thanks pointing out. I missed that `v` :)
