### ISSUE TITLE
3.1.1 with Xcode 8.1 & swift 3.0.1 

### ISSUE THREAD

**Issue by Shunzi007** [SwiftyJSON/SwiftyJSON#702]
It tells: " Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1: .../SwiftyJSON.swiftmodule/arm64.swiftmodule"

Maybe the framework should be compiled with swift 3.0.1.
Waiting for new release.

**Comment by wongzigii** [comment]
carthage update --platform iOS --no-use-binaries

**Comment by racer1988** [comment]
+1 for this.

Other Frameworks do not show the binary issue.

**Comment by zwang** [comment]
Based on this issue https://github.com/SwiftyJSON/SwiftyJSON/issues/690, there is some working workaround.

**Comment by Shunzi007** [comment]
With `--no-use-binaries`, Carthage works. Thanks!
