### ISSUE TITLE
expression implicitly coerced from 'String?' to Any

### ISSUE THREAD

**Issue by racer1988** [SwiftyJSON/SwiftyJSON#703]
Swift 3.0.1

Building with Carthage:

    Carthage/Checkouts/SwiftyJSON/Source/SwiftyJSON.swift:856:27: warning: expression implicitly coerced from 'String?' to Any

**Comment by DanBurkhardt** [comment]
This is an issue with the syntax change in swift 3.0.1 and it is breaking my build in a very serious way. I imagine that I'm not the only one. This is a pretty critical fix because it keeps Carthage from working at all.

**Comment by racer1988** [comment]
@DanBurkhardt Being a Warning it should still work. I have same issue with AlamoFire (https://github.com/Alamofire/Alamofire/issues/1745) but they should both work
