### ISSUE TITLE
get and extract values from a json server

### ISSUE THREAD

**Issue by athzuma** [SwiftyJSON/SwiftyJSON#706]
I have the following json on the server, lower it but can not extract values.

`{"ServicoCliente":[{"id":"195","cliente":"247","enderecoFavoritos":"48","servicoProfissional":"194","ind_estado_cliente":"A","ind_estado_profissional":"","profissional_id":"240","profissional_nome":"PetMax","servicotipo_nome":"Petshop","servicosubtipo_nome":"Tosa ","dta_inc_alt":"2016-11-05 22:56:19.333","ind_finalizado":"N"}]}`

How could I get for example the value of "id"?

**Comment by wongzigii** [comment]
@athzuma Any chance to try this?

````swift
let json = JSON(data: data as Data)
print(json["ServicoCliente"][0]["id"])
````

**Comment by athzuma** [comment]
this is returns null.
Just to confirm the Data is NSData?

**Comment by wongzigii** [comment]
No, I just export your data into a single json file, and the output is 195.

**Comment by athzuma** [comment]
I tested here like this json from a string and ran. But when I get it from the server does not work. I believe I have relationship with the "character encoding" server, could this be? and there is some form of deal with it?

**Comment by wongzigii** [comment]
What do *does not work* mean ? Are you using Alamofire ? What is the result of response ?

**Comment by athzuma** [comment]
I did several tests here, and also tried to Alamofire. It seems that the problem is with unescaped control character.

> Unescaped character control character around 263

Is there a way for me to remove unescaped control characters?

**Comment by wongzigii** [comment]
So hard to say what exactly your problem is ? Would you mind including some codes here so we could dig more?

**Comment by athzuma** [comment]
Thank you for attention. But I managed to solve.
I'll leave the solution here if useful for somebody else.
Some characters were preventing the transformation of the json, so I removed them so:

    var dataToString = String(data: data!, encoding: NSUTF8StringEncoding)
    dataToString = stringByRemovingControlCharacters2(dataToString!)
    data = dataToString!.dataUsingEncoding(NSUTF8StringEncoding)

    func stringByRemovingControlCharacters2(string: String) -> String {
    let controlChars = NSCharacterSet.controlCharacterSet()
    var range = string.rangeOfCharacterFromSet(controlChars)
    var mutable = string
    while let removeRange = range {
    mutable.removeRange(removeRange)
    range = mutable.rangeOfCharacterFromSet(controlChars)
    }
    return mutable
    }
