### ISSUE TITLE
`swift test`: no tests found to execute, create a module in your `Tests' directory

### ISSUE THREAD

**Issue by wongzigii** [SwiftyJSON/SwiftyJSON#710]
➜  swift test
    error: no tests found to execute, create a module in your `Tests' directory

This error shows up while running `swift test` while testcases are not included properly using SPM.

**Comment by ldiqual** [comment]
PR in https://github.com/SwiftyJSON/SwiftyJSON/pull/708

**Comment by wongzigii** [comment]
Closing in favor of #943
