### ISSUE TITLE
How do I analysis this 

### ISSUE THREAD

**Issue by ftgithub** [SwiftyJSON/SwiftyJSON#721]
{
    Data = "{\"Photo\":\"http://192.168.1.101/Users/Protraits/201611/9a704ca4bb064886a5a97cd8ad516c4e.JPG\",\"Verify\":\"0-0-0\",\"VipState\":\"0\",\"NickName\":\"\U706b\U67f4\",\"Scroe\":\"0\",\"AccountMoney\":\"0\",\"Collection\":\"89\"}";
    DataCount = "<null>";
    IsSuccess = 1;
    Message = "<null>";
}

I can get data from this string,but I can`t get data from the "Data". Any ideas?

**Comment by ldiqual** [comment]
@ftgithub Would you mind clarifying what you're trying to extract? Also, please post the json string that you're trying to parse, this seems like a dictionary that was printed in the console, not a valid json.

**Comment by ldiqual** [comment]
@ftgithub Bump.

**Comment by BryanSema** [comment]
It appears you're trying to pull user/profile images of users from an unspecified source/array. Could you elaborate what it is exactly you're trying to do?

**Comment by ldiqual** [comment]
@ftgithub In order to keep our issue backlog clean, and given the absence of followup, I'm gonna go ahead and close this. Please feel free to ping us if you'd like to reopen. Thank you!
