### ISSUE TITLE
Swift 2.2 Xcode 7.3.1

### ISSUE THREAD

**Issue by zoufishanmehdi** [SwiftyJSON/SwiftyJSON#722]
When I try to run my project, I'm getting this error: `no such module SwiftyJSON` Is SwiftyJSON still compatible with Swift 2.2 & Xcode 7.3.1? I'm using iOS 9.x fyi

**Comment by DavidLari** [comment]
There's a separate branch with the old Swift 2 code.

Include this in your pod file if you are using Cocoapods:

pod 'SwiftyJSON', '2.4.0'

**Comment by ldiqual** [comment]
@zoufishanmehdi I believe your issue was addressed so I'm gonna go ahead and close this. Let me know if you need to reopen. Thanks!
