### ISSUE TITLE
Parse json array in swift 3

### ISSUE THREAD

**Issue by MrLoveQD** [SwiftyJSON/SwiftyJSON#724]
Hi.
I have a json:

```
{
"code":1,
"message":"success",
"data":[
{
"fullName":"John",
"gender":"male",
"age":20
},
{
"fullName":"Kane",
"gender":"male",
"age":22
},
{
"fullName":"Kane",
"gender":"male",
"age":22
}
]
}
```

To get data json, in swift 2.3, i used:

```
if let dataJson: JSON = json["data"] {
            for (_, subJson) : (String, JSON) in dataJson {
                let fullName = subJson["fullName"].string
                let gender = subJson["gender"].string
                let age = subJson["age"].int
                // do something
            }
        }
```

But in swift 3, i get an error at: json["data"]
![image](https://cloud.githubusercontent.com/assets/4046835/20375880/925e4634-acb4-11e6-974b-e0e1faf57ee5.png)

Please help me.
Thank you!

**Comment by ldiqual** [comment]
`json["data"]` returns a value of type `JSON` which is a non optional, you can't use it in an `if let` unwrapping pattern. I would remove the `if` check altogether.

**Comment by MrLoveQD** [comment]
should i do ?
Please.
P/s: Those code worked fine on swift 2.3

**Comment by olejorgensen** [comment]
let json = JSON(data: data!)
let dataJson = json["data"]

      for object in dataJson.arrayValue {
                let fullName = subJson["fullName"].string
                let gender = subJson["gender"].string
                let age = subJson["age"].int
                // do something
            }

**Comment by MrLoveQD** [comment]
Thanks you very much 👍

**Comment by ldiqual** [comment]
Looks like your issue is addressed, closing now. Thanks!
