### ISSUE TITLE
.url instead of .URL

### ISSUE THREAD

**Issue by takasek** [SwiftyJSON/SwiftyJSON#740]
Swift3 API design guidelines says:

https://swift.org/documentation/api-design-guidelines/

>Acronyms and initialisms that commonly appear as all upper case in American English should be uniformly up- or down-cased according to case conventions:

```swift
var utf8Bytes: [UTF8.CodeUnit]
var isRepresentableAsASCII = true
var userSMTPServer: SecureSMTPServer
```

Therefore, how about to use `.url` instead of `.URL` ?

https://github.com/SwiftyJSON/SwiftyJSON/blob/30e3e67c981793e2f783982c7bf4c9501bf2d9a0/Source/SwiftyJSON.swift#L968

**Comment by wongzigii** [comment]
Agree! Feel free to submit a PR. :)

**Comment by takasek** [comment]
Sure, I will do it later!
