### ISSUE TITLE
NSNumber caused a problem in Linux

### ISSUE THREAD

**Issue by trmbhs** [SwiftyJSON/SwiftyJSON#745]
In Linux:

let value: Int = 1
print(value as? NSNumber) // It will print nil

but:

let value: Int = 1
print(NSNumber.init(value)) //It will print 1

In SwiftyJSON, the setter of var "object" use "object as? NSNumber" whitch will return nil even the "object" is "Int" caused some problems.

**Comment by kengruven** [comment]
Apple's [documentation](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/WorkingWithCocoaDataTypes.html) says:

> Swift bridges between the `NSNumber` class and Swift numeric types, including `Int`, `Double`, and `Bool`.
>
> You can create an `NSNumber` object by casting a Swift number value using the `as` operator. 

Assuming this is still true (the NSNumber should be `NSNumber(value: value)` in Swift 3, no?), this looks like a bug in Foundation on Linux.

**Comment by wongzigii** [comment]
I am going to close this now. FYI, Swift 4.0 has brought the NSNumber casting, you can checkout the in-process #943 to figure out the test cases about NSNumber.

See https://github.com/apple/swift-evolution/blob/master/proposals/0170-nsnumber_bridge.md

Note:

> Considerations for Linux platforms
> We do not have bridging on Linux so the as? cast is less important; but if it were to have bridging this would be the desired functionality.
