### ISSUE TITLE
JSON(data) vs. JSON(data: data) - The former fails on Swift 3 but works fine with Swift 2.3

### ISSUE THREAD

**Issue by mitchellporter** [SwiftyJSON/SwiftyJSON#747]
I have been using the following code to successfully initialize a `JSON` object in `swift 2.3`:

`let json = JSON(data)`

I can then access the various fields  for example:

`json["success"].boolValue // prints true`

I started a new project using `Swift 3` and `JSON(data)` no longer works. If I print the returned `json` object it logs as `unknown` and all of the fields that should be there log as `null`. 

I am able to parse json from the data just fine though by using `JSON(data: data)` instead of `JSON(data)`. Like I mentioned earlier though, this problem didn't exist when using `swift 2.3`.

I also wanted to mention that I can use the `NSJSONSerialization` class just fine. The issue seems to be with the old initializer failing when using `swift 3`.

**Comment by ldiqual** [comment]
@mitchellporter Thanks for opening an issue! The proper constructor to create a JSON instance with `Data` is `JSON(data: Data)`. `JSON(_ object: Any)` is to create a JSON value, so it needs to be a JSON-compatible type (Data isn't a compatible type). There is a pull request open to avoid the confusion here: https://github.com/SwiftyJSON/SwiftyJSON/pull/664. I'll close this when the PR gets merged. Thanks again!

**Comment by wongzigii** [comment]
Closing this for #664
