### ISSUE TITLE
Create JSON object directly from string

### ISSUE THREAD

**Issue by Phacometer** [SwiftyJSON/SwiftyJSON#751]
Can there be an initializer in the `JSON` class that accepts a string containing the JSON code, and initializes the object with it? It would be very convenient.

**Comment by rmck89** [comment]
I believe this is only possible using the Mirror reflection libraries. (Not tested in Swift3 but have done it in Swift2).

**Comment by wongzigii** [comment]
> Can there be an initializer in the JSON class that accepts a string containing the JSON code, and initializes the object with it? 

Hi @Phacometer If you mean initializing a model object from JSON mapping, I recommend you to use a mapping framework: etc. Unbox, ObjectMapper. 

Closing for now. If you have any issue, feel free to reopen it. :)
