### ISSUE TITLE
Xcode 8.1 so many errors

### ISSUE THREAD

**Issue by 111jaam** [SwiftyJSON/SwiftyJSON#754]
i manually imported SwiftyJSON.swift but got so many compiling errors in SwiftyJSON.swift.

![screen shot 2016-12-10 at 5 35 09 pm](https://cloud.githubusercontent.com/assets/3232787/21073247/0799e6cc-beff-11e6-9a1b-9123904eda5f.png)

**Comment by wongzigii** [comment]
Hi @111jaam 

- Are you using CocoaPods or Carthage?
- What's your CocoaPods or Carthage version?
- Which version of SwiftyJSON are you using?

**Comment by jaceklapinski** [comment]
Hi,

I have the same problem

1. CocoaPods
2. CocoaPods 1.1.1
3. SwiftyJSON 3.1.1

**Comment by zhigang1992** [comment]
@jaceklapinski can you post the `Podfile.lock` ?

**Comment by jaceklapinski** [comment]
`PODS:
  - Alamofire (3.5.1)
  - SwiftyJSON (3.1.1)

DEPENDENCIES:
  - Alamofire (~> 3.5)
  - SwiftyJSON

SPEC CHECKSUMS:
  Alamofire: 0dfba1184a543e2aa160f4e39cac4e8aba48d223
  SwiftyJSON: f0be2e604f83e8405a624e9f891898bf6ed4e019

PODFILE CHECKSUM: afc53677a2032fd75842210d6c54037528a01333

COCOAPODS: 1.1.1`

**Comment by wongzigii** [comment]
@111jaam @jaceklapinski 

- Update podspec to latest
- Delete `Podfile.lock`( ⚠️ Backup your lock file before doing this)
- Point SwiftyJSON's version to 3.1.1 or newer exactly

      pod 'SwiftyJSON', '= 3.1.1'
-  Pod install 
- Delete drived data before building

Good luck!

**Comment by jaceklapinski** [comment]
still same erros list

**Comment by MattNewberry** [comment]
I ran the Xcode wizard for converting to current swift syntax and that took care of the issues.

**Comment by NoaKadmi** [comment]
same here when installing SwiftyJson pod many errors appears like the picture above

**Comment by wongzigii** [comment]
Is this still an issue with the current release?

**Comment by pareekkhushboo77** [comment]
@MattNewberry Hi , did converting to current swift syntax solved all of these issues?

**Comment by wongzigii** [comment]
Hello, I just pushed 3.1.4 to CocoaPods and it should work. Feel free to open another issue if need.
