### ISSUE TITLE
setter does not work

### ISSUE THREAD

**Issue by ahmedsafadii** [SwiftyJSON/SwiftyJSON#757]
var CopyMedic:JSON = [[:]]

      CopyMedic[0]["title"].stringValue = "test"
      CopyMedic[1]["title"].stringValue = "test"
      print(CopyMedic)

the output is

[
  {
    "title" : "test"
  }
]

:(

**Comment by wongzigii** [comment]
Hi, @ahmedsafadii `CopyMedic` is an array only contains a dictionary.

````swift
func testEditDictionary() {
    var CopyMedic:JSON = [[:], [:]]
    CopyMedic[0]["title"].stringValue = "test"
    XCTAssertEqual(CopyMedic[0]["title"], "test")
    CopyMedic[1]["title"].stringValue = "test"
    XCTAssertEqual(CopyMedic[1]["title"], "test")
}

````
