### ISSUE TITLE
Can we store and read UIImage object in Swifty json

### ISSUE THREAD

**Issue by sandipdhagdi** [SwiftyJSON/SwiftyJSON#762]
Great framework!!

I am working on app which requires to store and retrieve images for Tableview cell.

As a data source for table I am using Swiftyjson object, But not getting way to store and retrieve images in Swiftyjson.

I tried solution from Stackoverflow  which encode/decode image with base64Encoded, it works.
but with **base64Encoded** table lags as it takes time to encode/decode image stored in json object.

Please suggest me solution.

**Comment by wongzigii** [comment]
Hi @sandipdhagdi You should use a asynchronous image framework likes:[SDWebImage](https://github.com/rs/SDWebImage) (Objective-C) or [Kingfisher](https://github.com/onevcat/Kingfisher) (Swift) , to prevent blocking your main thread while downloading image.
