### ISSUE TITLE
Can't change Bool Value of JSON

### ISSUE THREAD

**Issue by OuSS-90** [SwiftyJSON/SwiftyJSON#763]
```
var json: JSON!

override func viewDidLoad() {
    super.viewDidLoad()
    
    if let dataFromString = value?.data(using: .utf8, allowLossyConversion: false) {
        json = JSON(data: dataFromString)
    }
}

@IBAction func valueChanged(_ sender: UISwitch) {
    json["xxx"].bool = sender.isOn
}
  
```
 
Hi, this is my code to parse json, json["xxx"].bool stay always false
I tried to do json["xxx"].bool = true and json["xxx"].boolValue = true but same result

How to fix that ?

**Comment by wongzigii** [comment]
Hello @OuSS-90  Sorry for the late response. Can you take a look at #215 ?

**Comment by OuSS-90** [comment]
Thanks, it's working
