### ISSUE TITLE
After the latest pull .arrayObject stopped working

### ISSUE THREAD

**Issue by zeeshanz** [SwiftyJSON/SwiftyJSON#767]
I have an array of Strings which I was successfully converting to JSON, but it stopped working yesterday when I pulled the latest SwiftyJSON. For now, I have reverted back to my old version of SwiftyJSON which I believe is version 1.

```
var arr: [String]! = ["fish", "beef", "lamb"]
JSON(arr.data(using: .utf8)!).arrayObject as! [String]!

```

**Comment by wongzigii** [comment]
You can use:
````swift
let arr: [String]! = ["fish", "beef", "lamb"]
let json = JSON(arr).arrayObject
````
