### ISSUE TITLE
Option to change NSNull() return value to a real zero value

### ISSUE THREAD

**Issue by dhoerl** [SwiftyJSON/SwiftyJSON#77]
This is a hugely valuable project you created!

One huge issue I had in my last job was JSON nulls being returned by the web service. For instance, if someone had forgotten to set inventory, I'd get a null instead of zero. So I hacked up a category on NSNull so that I didn't have to test every single value before referencing it. The idea was that in most code, a zero would be just as useful as a null.

You can see others agree by the number of upvotes this answer got on SO: http://stackoverflow.com/a/16610117/1633251

What I am requesting is that you support an option that would result in no nulls being returned, with empty dictionaries, empty arrays, zero length strings, etc being returned instead.

If you want, I'll do the code and submit a pull request, but just tell me exactly how you want the option to work (and the actual string name if you care).

**Comment by antoinerabanes** [comment]
Ideally if the value is null, the key should be removed.
in turn when you query the collection for this key it will return nil

**Comment by dhoerl** [comment]
I completely disagree on deleting the key. A 'null' JSON value is a valid return, and has meaning. I've experience with actual e-commerce JSON returns containing such:

inventory : null // means it hasn't been entered yet
inventory: 50 // in stock at that level
inventory: -3 // yeah, got this - the stupid e-commerce site sold 3 items before it realized it didn't have them in stock, so someone is on the phone now trying to calm a client down (yeah, this happened and crashed my app!)

**Comment by antoinerabanes** [comment]
Thats interesting insight and a good example of the complexity of integrating an API that returns null/NSNull. 
However I would expect an integer back from the API and zero is a valid value to represent the stock when null is not because it is a different type and does not represent a number..

**Comment by dhoerl** [comment]
All I can say is my comment reflects Apple's current thinking. Swift Optionals either have a value or don't. The value can be 0 or not (if its say an Int). Each of these three states (as stated in my earlier example) means something different. A framework like this one cannot afford (IMHO) to gloss over this and assume all users want "no value" to be mapped into "0" (or similar).

That said, after fussing with nil for weeks, I threw in the towel and created the NSNull category above, which gives you exactly what you want - two cases. Even so, I prefer this framework to do the proper thing, and let the user decide to map 3 states to 2 if desired.

**Comment by Nelyus** [comment]
@dhoerl You could something like this, without any change to JSON:

```swift
if let number = json.number?.integerValue ?? json.null?.integerValue {
  // do stuff
}
```

It'd be more explicit, which can be good.
