### ISSUE TITLE
Current SwiftyJSON (via Swift 3.0) cannot be imported with Swift 3.0.2.

### ISSUE THREAD

**Issue by UncleRic** [SwiftyJSON/SwiftyJSON#771]
Environment: Xcode Version 8.2.1 (8C1002)

/Users/Ric/Workarea/SwiftStuff/SwiftTech/SwiftTech/Net.swift:11:8: Module compiled with Swift 3.0 cannot be imported in Swift 3.0.2: /Users/Ric/Workarea/SwiftStuff/SwiftTech/Carthage/Build/iOS/SwiftyJSON.framework/Modules/SwiftyJSON.swiftmodule/x86_64.swiftmodule

**Comment by wongzigii** [comment]
carthage update --no-use-binaries SwiftyJSON

**Comment by lawrencehjf** [comment]
carthage update --no-use-binaries SwiftyJSON --platform ios
