### ISSUE TITLE
creating new json with unlimited elements

### ISSUE THREAD

**Issue by alychyana** [SwiftyJSON/SwiftyJSON#773]
I am trying to create a JSON where to append elements as they occur

  var jsonTPXtest: JSON =  ["events": [:]]

  for index in 0...20 {
          jsonTPXtest["events"][index] = ["id":index,"x1":0,"x2":0]
        }

But it doesn't seem to add any element to the JSON.

**Comment by alexdd55** [comment]
i did this:
`	func prependObjectToJSON(_ data:JSON, newdata:JSON) -> JSON {
		let s = JSON(newdata.arrayObject! + data!)
		return s
	}

	func appendObjectToJSON(_ data:JSON, newdata:JSON) -> JSON {
		let s = JSON(dataarrayObject! + newdata.arrayObject!)
		return s
	}
`

**Comment by wongzigii** [comment]
Hey @alychyana. Sorry for the late response. From the code you given, I assume you are trying to set the `[:]` （which is a dictionary）

````swift
func testUnlimitedElements() {
        var jsonTPXtest: JSON = JSON(["events": [:]])
        
        for index in 0...20 {
            jsonTPXtest["events"]["\(index)"] = ["id":index,"x1":0,"x2":0]
            XCTAssertEqual(jsonTPXtest["events"]["\(index)"], ["id":index,"x1":0,"x2":0])
        }
    }
````

However, if you wanna set the array indeed, you would need to create a fixed size array.

````swift
func testUnlimitedElements() {
        var jsonTPXtest: JSON = JSON(["events": [[:], [:], [:], [:]]])
        
        for index in 0...4 {
            jsonTPXtest["events"][index] = ["id":index,"x1":0,"x2":0]
            XCTAssertEqual(jsonTPXtest["events"][index], ["id":index,"x1":0,"x2":0])
        }
    }
````
