### ISSUE TITLE
Cocoapods is still dispensing v`3.1.3`

### ISSUE THREAD

**Issue by gravicle** [SwiftyJSON/SwiftyJSON#776]
[SwiftyJSON on CP](https://cocoapods.org/?q=SwiftYJSO)
<img width="703" alt="screen shot 2017-01-03 at 12 10 48 pm" src="https://cloud.githubusercontent.com/assets/1091114/21621405/b16914e6-d1ad-11e6-8805-bbf932efd5ad.png">

**Fix**: amend release `3.1.4` with the correct version in `SwiftyJSON.podspec`.
**Note**: Sorry couldn't create a PR as the fix should be applied to a release. Please correct me if I am wrong.

**Comment by Sethmr** [comment]
I second this post!

**Comment by wongzigii** [comment]
Sorry for late reply. I had just pushed 3.1.4 to CocoaPods. Feel free to hit me up if there is still an issue. Closing. 🚢
