### ISSUE TITLE
Broken init of inner JSON with string concatenation

### ISSUE THREAD

**Issue by stefan-avramov** [SwiftyJSON/SwiftyJSON#785]
Hello, can someone please explain to me what is happening here?

```
        let inner = JSON.init([
            "some_field": "1" + "2",
        ])

        var json = JSON.init([
            "outer_field": "1" + "2",
            "inner_json": inner
        ])
```
(lldb) expr inner.description
(String) $R0 = "{\n  \"some_field\" : \"12\"\n}"
(lldb) expr json.description
(String) $R1 = "unknown"

If I remove the "+" all is fine.

**Comment by MikotoZero** [comment]
Maybe its not the +'s failure
Current initialize methods can not  handle mixed collection type which element contains both `Any` and `JSON`

``` swift
    public init(_ object: Any) {
        switch object {
        case let object as [JSON] where object.count > 0:
            self.init(array: object)
        case let object as [String: JSON] where object.count > 0:
            self.init(dictionary: object)
        case let object as Data:
            self.init(data: object)
        default:
            self.init(jsonObject: object)
        }
    }
```
It works just when your source is [JSON] or [String : JSON]

**Comment by MikotoZero** [comment]
Maybe not +'s fault.
Current initalize methods can not handle mixed element collection type unless it can be considerd as [JSON] or [String : JSON] anyway

`json` still `unkown` in this case
``` swift
let inner = JSON([
    "some_field": "1" + "2",
    ])

let string = "1"
var json = JSON([
    "outer_field": string,
    "inner_json": inner
    ])
```

**Comment by wongzigii** [comment]
Closing.
