### ISSUE TITLE
Module compiled with Swift 3.0

### ISSUE THREAD

**Issue by cikpis** [SwiftyJSON/SwiftyJSON#787]
Hi guys, I'm still having this problem:
```/Users/XXX/Desktop/XXX/Development/Projects/XXX/Source/Infrastructure/Managers/API/Services/Parsers/CarDraftParser.swift:10:8: Module compiled with Swift 3.0 cannot be imported in Swift 3.0.2: /Users/XXX/Desktop/XXX/Development/Projects/XXX/Carthage/Build/iOS/SwiftyJSON.framework/Modules/SwiftyJSON.swiftmodule/arm64.swiftmodule```

Is it possible for you to update it? It is an easy fix but a critical one for those like me that want to use carthage without the ```--no-use-binaries``` part.

Thanks in advance,
Carmelo

**Comment by wongzigii** [comment]
Hi @cikpis I just uploaded a latest release which still tagged `3.1.4`, there should not be an issue now. Thanks for filling an issue. Cheers!

**Comment by cikpis** [comment]
Thanks man! Cheers!

**Comment by cikpis** [comment]
Hey man is not working. I just fetched it and got the same error.

**Comment by wongzigii** [comment]
rm `Cartfile.resolve` file and run `carthage update` again.

**Comment by cikpis** [comment]
Always done that before calling update :)
