### ISSUE TITLE
SwiftyJSON not compiling with socket.io-swift

### ISSUE THREAD

**Issue by crickabhi** [SwiftyJSON/SwiftyJSON#790]
I have added socket.io and swiftyjson manually to my project. But my app is not compiling and showing issue.--> invalid redeclaration of JSON.
I have also attached the sample project.
[SocketWithSwiftyJSON.zip](https://github.com/SwiftyJSON/SwiftyJSON/files/752082/SocketWithSwiftyJSON.zip)

**Comment by wongzigii** [comment]
You should consider to use [CocoaPod](https://github.com/CocoaPods/CocoaPods) or [Carthage](https://github.com/Carthage/Carthage) to manage swift module.

**Comment by wongzigii** [comment]
The latest [Socket.IO](https://github.com/nuclearace/Socket.IO-Client-Swift) works for me. One thing need more consideration is:  JSON is a typealias of  [String: Any] in Socket.IO. 

See https://github.com/nuclearace/Socket.IO-Client-Swift/blob/163a770abc4842250d31b8662354d0df190c2885/Source/SocketTypes.swift#L45

**Comment by yonlau** [comment]
@wongzigii  What to do if duplicate typealias  "JSON" was defined ?

**Comment by wongzigii** [comment]
@yonlau You can specific the JSON with namespace, `SwiftyJSON.JSON` or `SocketIO.JSON`.
