### ISSUE TITLE
Question: JSON response from Google Distance Matrix API

### ISSUE THREAD

**Issue by calvinorchiz** [SwiftyJSON/SwiftyJSON#797]
Sorry for this beginner question. I use Xcode 8 and Swift 3.

In my app i get the distance between two locations from the Google Distance Matrix API (with Alamofire). This is working fine.

This is the response from Alamofire:

{
  "status" : "OK",
  "destination_addresses" : [
    "Heinrich-Steinmann-Straße 12, 51147 Köln, Germany"
  ],
  "origin_addresses" : [
    "Ubierring 88, 50678 Köln, Germany"
  ],
  "rows" : [
    {
      "elements" : [
        {
          "status" : "OK",
          "distance" : {
            "value" : 16617,
            "text" : "16.6 km"
          },
          "duration" : {
            "value" : 1248,
            "text" : "21 mins"
          }
        }
      ]
    }
  ]
}
Status:  OK

With SwiftyJSON i can access status, destination_addresses and origin_addresses like:
json["status"].stringValue)
json["destination_addresses"].arrayValue) 
json["origin_addresses"].arrayValue)

With json["rows"]["elements"]["status"] i get null.

How can i get the distance value/text and the duration value/text with SwiftyJSON?

**Comment by wongzigii** [comment]
From what I saw, `elements` is an array which wrapping with a `[]` . :)
