### ISSUE TITLE
Setting an array to empty not working

### ISSUE THREAD

**Issue by AnthonyMDev** [SwiftyJSON/SwiftyJSON#800]
When trying to set an array nested in my `JSON` to an empty array, nothing is happening.

````swift
let json =  JSON(["array": [1, 2, 3]])

json["array"] =  JSON([]) 
json["array"].array = JSON([])
json["array"].arrayObject = []

print(json) // ["array": [1, 2, 3]]
````

I currently have to do this to get it to properly set the array:

````swift
var json =  JSON(["array": [1, 2, 3]])

var dict = json.dictionaryObject
dict["array"] = []
json = JSON(dict)
````

This error is occurring using version `3.1.4`.

**Comment by JeffGuKang** [comment]
Is this typo? You did not close the bracket in  
`var json =  JSON(["array": [1, 2, 3])`

**Comment by AnthonyMDev** [comment]
Sorry. Yes, those were typos. I've fixed the typos. The bug report is valid.

**Comment by wongzigii** [comment]
Pretty strange behavior. 
````swift
mutable["mutable"] = [1, 2, 3] // this works
XCTAssertEqual(mutable["mutable"], [1, 2, 3])

mutable["mutable"] = [] // this fails
XCTAssertEqual(mutable["mutable"], [])
````

**Comment by AnthonyMDev** [comment]
In my use case, I was setting the array to an empty array. I didn't realize that this behavior only occurred in that situation. Good to know.

**Comment by MikotoZero** [comment]
Maybe i find what happend
`[]` has been convert to type `[JSON]`

There is a bug  in `v3.1.4`
`object`'s setter never assign value to rawArray
```swift
              case _ as [JSON]:
                _type = .array
            case nil:
                _type = .null
            case let array as [Any]:
                _type = .array
                self.rawArray = array
```

This bug fixed in #743 and #793

**Comment by wongzigii** [comment]
Hey @MikotoZero Thanks for your PR, I will review this at this weekend If I have some spare time. :)

**Comment by wongzigii** [comment]
#793 has been merged into master. 

For more mutability, please check out [MutabilityTests](https://github.com/SwiftyJSON/SwiftyJSON/blob/master/Tests/SwiftyJSONTests/MutabilityTests.swift)

Cheers.
