### ISSUE TITLE
Failed to parse json string with special character

### ISSUE THREAD

**Issue by interchen** [SwiftyJSON/SwiftyJSON#802]
**failed**
```
let jsonStr = "{\"nickName\":\"\\uD83C***\\uDF6C\"}"
let json = JSON(parseJSON: jsonStr)  
print("json = \(json)")
```
result:  json = null

**success**
```
let jsonStr = "{\"nickName\":\"hello\"}"
let json = JSON(parseJSON: jsonStr)  
print("json = \(json)")
```
result:  json = {"nickName": "hello"}

How can I fix it

**Comment by wongzigii** [comment]
Hey @interchen 
In your first example, `\uD83C***` is not a valid character. If you remove the duplicate `*`, JSON will be parsed successfully. Unfortunately, SwiftyJSON *does not*  provide a way to verify your character if is valid at this time. Let me know if there is any issue. :)
