### ISSUE TITLE
Add support for parsing bool from strings "0" or "1"

### ISSUE THREAD

**Issue by gregoryjose** [SwiftyJSON/SwiftyJSON#808]
As a checked in your source code, you do not have support for this.

Would be glad if you will. Thanks!

**Comment by Harshit31** [comment]
just add `"1"` to the array at line `883` in swiftyJSON.swift

**Comment by gregoryjose** [comment]
Yeah, I already figured out the solution. Maybe I just create a pull request for this. Many thanks!

**Comment by wongzigii** [comment]
Addressed in #887 Thanks!
