### ISSUE TITLE
Type [SubscriptType] Does not conform to protocol 'StringLiteralConvertible'

### ISSUE THREAD

**Issue by kiwox** [SwiftyJSON/SwiftyJSON#81]
I think this could be related to other issues reported before, but this has been frustrating me since yesterday and it didn't solve, even after update to the latest version.

I don't understand why it is firing inside a specific point, and I have also other lines where I do the same and they are not firing anything.

```
    searchReq = Alamofire.request(.GET, "https://maps.googleapis.com/maps/api/place/details/json", parameters:params)
        .responseSwiftyJSON({ (req:NSURLRequest, response:NSHTTPURLResponse?, data:SwiftyJSON.JSON, error:NSError?) -> Void in

            UIApplication.sharedApplication().networkActivityIndicatorVisible = false

            if data != nil && data["status"] == "OK" {

                println(data["result"]["formatted_address"])
                if data["result"]["geometry"]["location"].dictionary != nil {

                    // This is the line that fires error
                    let coords:CLLocationCoordinate2D = CLLocationCoordinate2DMake(data["result"]["geometry"]["location"]["lat"],
                                                                                   data["result"]["geometry"]["location"]["lng"])
                    self.addPinToLocation(coords, title:self.selectedLocationHint?["description"] as String!, subtitle:"", focus:true)
                }
            }
        })
```

![captura de pantalla 2014-10-22 a las 9 42 06](https://cloud.githubusercontent.com/assets/1884855/4736077/df1a1956-59e8-11e4-97fa-d4ed4a5577bd.png)

**Comment by philsquared** [comment]
I'm seeing the same issue. 
I'm using Xcode 6.2 (latest beta) with SwiftyJSON 2.1.3 (I think - how do I tell? It was the latest as of a few days ago, anyway).

I would put it down to an Xcode beta problem if it wasn't for the above reports. Is this an ongoing issue?

**Comment by pitiphong-p** [comment]
I found this issue. It's error in the json["key"].string which call in the switch statement.

````
switch (json["key1"], json["key2"]) {
````
