### ISSUE TITLE
extension NSNumber var isBool:Bool sometimes collides with Alamofire

### ISSUE THREAD

**Issue by dirk68-fu** [SwiftyJSON/SwiftyJSON#812]
### What did you do?

I tried to use Alamofire and SwiftyJSON in a xCode playground. Because there ist no multi-module/framework support in playgrounds yet. I had to copy Alamofire files and SwityJSON source into the playground's _sources_ directory

### What did you expect to happen?

Should work!

### What actually happened instead?

Got a compiler error because both frameworks define extension to NSNumber named **isBool**.

To make it work I had to change visibilty of isBool in SwityJSON to fileprivate.

This is the problematic code:
https://github.com/SwiftyJSON/SwiftyJSON/blob/1d64b89d9aba1e82bd74a6393cfc3061250a8a80/Source/SwiftyJSON.swift#L1344-L1345

**Comment by wongzigii** [comment]
Hey @dirk68-fu Did you try adding a module name before extension, for instance:

````swift
extension SwiftyJSON.NSNumber {
    var isBool:...
}
````
Is this solve your problem?

**Comment by dirk68-fu** [comment]
Hi,

unfortunately that does not work and results in the following error: "Use of undeclared type 'SwiftJSON'



Sincerely,

Dirk

**Comment by wongzigii** [comment]
I noticed your comment is `SwiftJSON`, is it a typo? (Should be Swift**y**JSON)

**Comment by dirk68-fu** [comment]
Sorry, that was a typo. It does not work even with "SwiftyJSON.NSNumber".

**Comment by wongzigii** [comment]
@dirk68-fu It seems like there is no way to disambiguate them. A workaround here would look like:

````swift
let a = 1 as SwiftyJSON.NSNumber
let b = 1 as Alamofire.NSNumber

a.isBool // SwiftyJSON's NSNumber extension
b.isBool // Alamofire NSNumber extension
````

**Comment by LambdaDigamma** [comment]
I don't know whether this affects the functionality of SwiftyJSON or Alamofire, but declaring them `fileprivate` seems to work.
