### ISSUE TITLE
What's the size of this library when I submit my app on AppStore

### ISSUE THREAD

**Issue by unittesting0** [SwiftyJSON/SwiftyJSON#818]
Hello guys,

Want to take rid of Realm, and use SwiftyJSON and I'm trying to figure out how many Mb will increase my app when I submit my app on AppStore.

I hope you understand my question.
Thanks.

**Comment by wongzigii** [comment]
Hey @unittesting0 ,  you will likely want to perform an ad-hoc export to see the size of each thinned variant of your app anyway. Does not test it but it may works.
