### ISSUE TITLE
boolValue "1' -> false

### ISSUE THREAD

**Issue by zidanex** [SwiftyJSON/SwiftyJSON#819]
In your current Version the boolValue property returns false for String "1", which ist the most common string for bool. Why don't just use native boolValue of NSString? Or At least you should add "1" to your list. Here is my fix:

`
//Non-optional bool
    public var boolValue: Bool {
        get {
            switch self.type {
            case .bool:
                return self.rawBool
            case .number:
                return self.rawNumber.boolValue
            case .string:
                return (self.stringValue as? NSString)?.boolValue ?? false                
            default:
                return false
            }
        }
        set {
            self.object = newValue
        }
    }
`

**Comment by wongzigii** [comment]
Addressed in #887
