### ISSUE TITLE
Having issues with looping through JSON...

### ISSUE THREAD

**Issue by bostonmacosx** [SwiftyJSON/SwiftyJSON#821]
### What did you do?

```
var test1:String = "{\"1\":\"test\",\"2\":\"test2\"}"
        var tempJSON:JSON = JSON(test1)
        print(tempJSON) //prints {"1":"test","2":"test2"}
        for(key, value):(String,JSON) in tempJSON {
            print(key)
            print(value)
        }
```
### What did you expect to happen?

Printing out the key and value of the json object.

### What actually happened instead?

no printing at all of key or value

### Environment

List the software versions you're using:

 - SwiftyJSON: *latest version just did pods update*
 

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.2.0* (Use `pod --version` in Terminal)

**Comment by wongzigii** [comment]
@bostonmacosx You should use 

    var tempJSON: JSON = JSON(parseJSON: test1)

to construct a JSON object if you are parsing from string literal.
