### ISSUE TITLE
Get the JSON Value using Key

### ISSUE THREAD

**Issue by TheGreenGentleman** [SwiftyJSON/SwiftyJSON#824]
I have a valid JSON file that I accessed using the code below using some parameters:

`Alamofire.request(url_string, parameters: parameters).validate().responseJSON { response in
`
`switch response.result {`
`case .success(let value):`
`let json = JSON(value)`
`print("JSON: \(json)")`
`let code = json["code"].stringValue`
`print(code)`
`case .failure(let error):`
`print(error)`
`}`
`}`

Here's the JSON output:

>JSON: [
  {
    "message" : "Access granted",
    "user_id" : "ushuam00",
    "code" : "login_success"
  }
]
>

What I'm trying to get here is the value "login_success" using the key "code"

I want to put the value "login_success" in a Core Data Entity that's why I want to output the value.

What am I doing wrong?

**Comment by Pranshugoyal** [comment]
Your json consists of a dictionary inside an array, try this:

json[0]["code"].stringValue

**Comment by TheGreenGentleman** [comment]
@Pranshugoyal thank you! That works :)
