### ISSUE TITLE
JSON.arrayObject?.remove at doesn't work

### ISSUE THREAD

**Issue by alicksnake22** [SwiftyJSON/SwiftyJSON#828]
let localPhotoArrNew = Defaults.array(forKey: "LocalPhotos")
var localPhotoArrJsonNew = JSON.init(localPhotoArrNew as Any)
localPhotoArrJsonNew.arrayObject?.remove(at: 0)

JSON.arrayObject?.remove at doesn't work , the sub item is still exist

**Comment by alicksnake22** [comment]
swift 3.0

**Comment by alicksnake22** [comment]
` let localPhotoArrNew = Defaults.array(forKey: "LocalPhotos")
                    var localPhotoArrJsonNew = JSON.init(localPhotoArrNew as Any)
                    localPhotoArrJsonNew.arrayObject?.remove(at: 0)`

**Comment by alicksnake22** [comment]
`
 let localPhotoArrNew = Defaults.array(forKey: "LocalPhotos")
 var localPhotoArrJsonNew = JSON.init(localPhotoArrNew as Any)
 localPhotoArrJsonNew.arrayObject?.remove(at: 0)
`

**Comment by garrettjmilovich** [comment]
I'm having a similar problem. I have a json array, and I cycle through it in reverse and remove certain objects: 

'filteredCategoriesList[category]["items"].arrayObject?.remove(at: item)'

However, if "item" is 0 and it is the final object in the json array, it doesn't remove.

**Comment by JeffGuKang** [comment]
@alicksnake22 @garrettjmilovich 

I tested `JSON.arrayObject?.remove` in playground.

```swift
var testJson = JSON.init([1, 2, 3])
print(testJson[0]) // 1
testJson.arrayObject?.remove(at: 0) // remove 1
print(testJson[0]) // 2
```

But I could not find any problems. How about giving information more include a part of original json with more codes?

**Comment by alicksnake22** [comment]
@JeffGuKang 
I test again.I'm sorry, I made a mistake...remove is fine.I will close this

**Comment by JeffGuKang** [comment]
@alicksnake22 Thank you for fast reaction. 
Happy coding!
