### ISSUE TITLE
.arrayObject setter not working in 3.1.4 (works in 3.1.3)

### ISSUE THREAD

**Issue by angrykilobyte** [SwiftyJSON/SwiftyJSON#829]
### What did you expect to happen?

Using the latest version 3.1.4, setting an array using `.arrayObject` of a dictionary JSON:

	var locationJson:JSON = [:]
	locationJson["foo"].string = "xy"
	locationJson["bar"].int = 12323
	json["arrayObject"].arrayObject = [locationJson]
	
would produce:

	{
	  "locations" : [
	    {
	      "bar" : 12323,
	      "foo" : "xy"
	    }
	  ]
	}

This was working in version 3.1.3.

### What actually happened instead?

Instead in version 3.1.4 I get:

	{
	  "locations" : [
	
	  ]
	}

### Environment

List the software versions you're using:

 - SwiftyJSON: *3.1.4*
 - Xcode Version: *8.3 (8E162)*
 - Swift Version: *`Xcode Default`*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.1.1* (Use `pod --version` in Terminal)

### Project that demonstrates the issue

1. Download [Issue](https://github.com/angrykilobyte/SwiftyJSON-Issue)
2. Open `Issue.wcworkspace`.
3. Build the `IssueFramework` scheme.
3. Open `IssuePlayground.playground` from the workspace.
4. Note Playground output.

**Comment by mkko** [comment]
I wonder if this is the same, but also this simple thing seems to fail with 3.1.4, but works with 3.1.3:

```
var json = JSON("items")
json.arrayObject = [JSON("1"), JSON("2")]

// Expected:
// [
//   "1",
//   "2"
// ],
// but is just an empty string
```

However, the following would make it work:

```
var json = JSON("items")
json.arrayObject = [1, JSON("1"), JSON("2")]
```

I'm using Carthage, but the rest of the configuration is exactly the same.

**Comment by mattshaffer11** [comment]
This is actually fixed in master. It might be a good time to release a new version `3.1.5` so this fix can go in, seems pretty important.

For now, if you are looking for a workaround and are using Cocoa pods, you can just put the following in your Podfile to use the master version:

```ruby
pod 'SwiftyJSON', git: 'https://github.com/SwiftyJSON/SwiftyJSON.git', commit: 'f9afe96'
```

**Comment by angrykilobyte** [comment]
Confirmed, thanks! Closing issue and awaiting official 3.1.5 release.
