### ISSUE TITLE
how to conert JSON to String without "\n" and "\\"? in a elegant way?

### ISSUE THREAD

**Issue by zhihuitang** [SwiftyJSON/SwiftyJSON#837]
Here my "**info**" is a JSON object, info.rawString() give a String with "\n".
But actually I don't want to have the "\n". I searched the documentation,  it seems there is only one member in WritingOptions, that is prettyPrinted. Then what is the non-prettyPrinted?

Another issue I don't want **"/storage/emulated/0/Pictures/camera"** to be converted to **"\\\\/storage\\\\/emulated\\\\/0\\\\/Pictures\\\\/camera\"**.

I know there is a ugly way that using aString.replace() to replace "\n" and "\\" stuff.
But I think there should have a elegant way to do it since it is a quite common requirement.
Any help would be much appreciated.

```
(lldb) po info.rawString()
▿ Optional<String>
  - some : "{\n  \"orientation\" : 3,\n  \"dataPath\" : \"\\/storage\\/emulated\\/0\\/Pictures\\/camera\",\n  \"height\" : 3264,\n  \"mimeType\" : \"JPEG\",\n  \"dateModified\" : 1492765012428,\n  \"width\" : 2448,\n  \"displayName\" : \"IMG_0002.JPG\",\n  \"title\" : \"IMG_0002.JPG\",\n  \"fileSize\" : 1418517,\n  \"dateAdded\" : 1492765012428,\n  \"bucketDisplayName\" : \"camera\",\n  \"mediaContentUri\" : \"\"\n}"

```

**Comment by CraigSiemens** [comment]
I just ran into this. `rawString` has a `options` parameter that defaults to `.prettyPrinted`. To get it to not pretty print (not have indenting/newlines) you just need to pass an empty option set

```swift
json.rawString(options: [])
```

**Comment by wongzigii** [comment]
Hey @zhihuitang In your case, info is a JSON object, so calling `rawString()`  results in the string representation of JSON. 

FWIW, you can still obtain the string value without `\\` and `\n` if you access the value directly.

**Comment by chanonly123** [comment]
in Swift 4 
let jsonString = JSON(arrayIds).rawString([:]) 
not working

**Comment by dubiao** [comment]
in Swift 4
let jsonString = JSON(arrayIds).rawString([:])
not working

**Comment by thepinyo** [comment]
what is solution?

**Comment by ghafartanveer** [comment]
any solution?
