### ISSUE TITLE
Nothing happens when setting arrayObject to empty array []

### ISSUE THREAD

**Issue by philippeauriach** [SwiftyJSON/SwiftyJSON#840]
### What did you do?
`elt["activities"].arrayObject = []    //here activities is already set to an array value`

### What did you expect to happen?
`elt["activities"] array to take the new value (empty array)`

### What actually happened instead?
nothing, index "activities" is still set to the previous value. this seems to happen only when setting an empty array

### Environment
 - SwiftyJSON: *3.1.4*
 - Xcode Version: *8.3.2 (8E2002)*
 - Swift Version: *Xcode Default*
 - Cocoapods: *1.2.0*

### Project that demonstrates the issue

        var myJson = JSON([
            "array" : [JSON(0)]
            ])

        print("initial: ", myJson["array"]) // display [0], OK

        // ISSUE
        myJson["array"].arrayObject = []
        print("setting to []: ", myJson["array"])   // display [0], KO should be []

        // WORKAROUND        
        myJson["array"].arrayObject = nil
        myJson["array"].arrayObject = []
        print("setting to nil then to []: ", myJson["array"])   // display [], OK
```

**Comment by wongzigii** [comment]
Hey @philippeauriach  Sorry for the late response.
Just drop the arrayObject:

````swift
myJson["array"]= []
````

**Comment by M-HERBRICH-ITC** [comment]
@wongzigii Your approach is not working. I've the same issue like @philippeauriach and only workaround is as he mentioned to set is to JSON.null first and then to empty array.
You should re-open this issue.
