### ISSUE TITLE
Reference semantics

### ISSUE THREAD

**Issue by mzbik** [SwiftyJSON/SwiftyJSON#841]
```swift
var x = JSON( [ "foo": [ "bar": "baz"]] as [ String: Any ] )
var y = x["foo"]
y["bar"] = 42
// x["foo"]["bar"] is still "baz", not 42
// This is due to Swift's value vs reference semantics for dictionaries and arrays. When
// y is initialized, it's dictionary is a copy of the one in X. Modifying it does not modify the one in X
```

Two solutions:
1. Document it. Easiest.
2. Have JSON be a class that individually wraps directories and arrays. This requires conversion at construction and when serializing.

**Comment by wongzigii** [comment]
Hey @mzbik Thanks for pointing this out, I would prefer the first solution. In SwiftyJSON, JSON is designated to be a struct type, from this point, we are not expecting the JSON(data from server) is *strictly mutable*.
