### ISSUE TITLE
JsonPath support

### ISSUE THREAD

**Issue by dyang** [SwiftyJSON/SwiftyJSON#842]
Hi,

I'm trying to use SwiftyJSON on a project where we use [JsonPath](https://github.com/json-path/JsonPath) to define how data should be parsed.  So far it doesn't seem that JsonPath parsing is supported. I wonder if it's possible to add that support in a future version?

Thanks!

**Comment by wongzigii** [comment]
Sorry @dyang , we are not going to support this.

**Comment by michallaskowski** [comment]
Hi,
I understand you are not going to work on support for JsonPath. But would you be willing to accept PRs adding at least some support for it? Like access through keys, array indexes, and filtering arrays based on objects keys/values ( ?(@.key == 'value')?
