### ISSUE TITLE
swift struct to oc

### ISSUE THREAD

**Issue by YongruiDuan** [SwiftyJSON/SwiftyJSON#843]
why do not you implement '_ObjectiveCBridgeable'? can you tell me your reasons?

**Comment by wongzigii** [comment]
AFAIK, `_ObjectiveCBridgeable` is a private protocol use internally within swift standard library, it may be changed in the future release.
Considering this, we are not going to implement this until [0058-objectivecbridgeable](https://forums.developer.apple.com/thread/44731) is launched.
