### ISSUE TITLE
Single scheme?

### ISSUE THREAD

**Issue by ddddxxx** [SwiftyJSON/SwiftyJSON#845]
Since SwiftyJSON is platform independent, separate scheme is redundant and ugly.

**Comment by wongzigii** [comment]
[Carthage](https://github.com/Carthage/Carthage/) is using this to checkout and build the scheme independently.

**Comment by XQS6LB3A** [comment]
It's not indispensable, see http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/

**Comment by wongzigii** [comment]
A pr for this issue will be appreciated :D

**Comment by XQS6LB3A** [comment]
I'm working on it.

**Comment by XQS6LB3A** [comment]
I found the `Product Bundle Identifier` of target `SwiftyJSON tvOS Tests` is `com.tangplin.SwiftyJSON-tvOS-Tests`, which is different from the others (`com.swiftyjson.$(PRODUCT_NAME:rfc1034identifier)`), Why?

**Comment by XQS6LB3A** [comment]
there are several inconsistent settings:
- target `OSX`, `OSX Tests` and `tvOS Tests` set `DEBUG_INFORMATION_FORMAT`, but the others didn't.
- `PRODUCT_NAME` of target `OSX` is `$(PROJECT_NAME)`, the others' is `SwiftyJSON`.
- the most ridiculous, target `watchOS` uses `Info-OSX.plist`.
