### ISSUE TITLE
Question: How to save JSON to file with proper new line return?

### ISSUE THREAD

**Issue by alejandroluengo** [SwiftyJSON/SwiftyJSON#847]
Dear all:

I am trying to export the processed json using the lib like that

let representation = try! json.rawData()
try! representation.write(to: URL(fileURLWithPath: path))

That gives me this exported JSON in a file

{"rss":{"green":255,"red":255,"url":"http:\/\/www.abc.es\/rss\/feeds\/abc_ultima.xml","blue

But original JSON it's more much human readable

{
  "rss" : {
    "green" : 255,
    "red" : 255,
    "url" : "http:\/\/www.abc.es\/rss\/feeds\/abc_ultima.xml",
    "blue" : 255,
    "ypos" : 960
  }, [...]
}

Is there something I can do to export the JSON like that?

Thanks in advance for helping me

**Comment by wongzigii** [comment]
Try this: http://json.parser.online.fr/

**Comment by alejandroluengo** [comment]
Thanks for that!
