### ISSUE TITLE
SwifyJSON to Swift Array/Dictionary

### ISSUE THREAD

**Issue by praveenambekar** [SwiftyJSON/SwiftyJSON#849]
i'm trying to convert SwiftyJSOn array to Swift array as below:
````swift
self.responseArray = [Anyobject]()
self.responseArray = jsonString!.arrayValue.map { $0.arrayObject!}
````
Application is crashing everytime. Can someone pls let me know how to convert swiftyJSON Array/Dictionary to Swift Array/ Dictionary.

Appreciate your help. Thanks!

**Comment by wongzigii** [comment]
@praveenambekar Can you post the crash message here?

**Comment by andy1247008998** [comment]
I'd like to reopen this issue cuz I'm seeking for same function as mentioned here.

Example response:
```
{
    "action" : "post",
    "application" : "a2e433a0-ab1a-11e2-a134-85fca932f094",
    "params" : { },
    "path" : "/users",
    "uri" : "https://a1.easemob.com/easemob-demo/chatdemoui/users",
    "entities" : [ {
        "uuid" : "7f90f7ca-bb24-11e2-b2d0-6d8e359945e4",
        "type" : "user",
        "created" : 1368377620796,
        "modified" : 1368377620796,
        "username" : "jliu",
        "activated" : true
        }
  	} ],
  	"timestamp" : 1368377620793,
  	"duration" : 125,
  	"organization" : "easemob-demo",
  	"applicationName" : "chatdemo"
}
```

I'd like to have entities stored as [String:String]? 
For now, I am supposed to look into the dictionaryObject of type [String:Any], cast that Any to String, then I will get [String:String], save each item to a new dictionary.

Would be nice if SwiftyJSON can do call this work for me.
Thank you
