### ISSUE TITLE
Can't install SwiftyJSON

### ISSUE THREAD

**Issue by Sukhrob** [SwiftyJSON/SwiftyJSON#856]
### What did you do?
    pod 'SwiftyJSON', '~> 3.1'
    pod install

### What did you expect to happen?
Installation

### What actually happened instead?
    [!] Error installing SwiftyJSON
    [!] /usr/local/bin/git clone https://github.com/SwiftyJSON/SwiftyJSON.git 
    /var/folders/d3/_ys3ct5j2770983xyqxdtwmh0000gp/T/d20170605-6874-fiwxdp --template= --single-branch --depth 1 --branch v3.1.1

    Cloning into '/var/folders/d3/_ys3ct5j2770983xyqxdtwmh0000gp/T/d20170605-6874-fiwxdp'...
    warning: Could not find remote branch v3.1.1 to clone.
    fatal: Remote branch v3.1.1 not found in upstream origin

### Environment

List the software versions you're using:

 - SwiftyJSON: 3.1.1
 - Xcode Version: 8.2.1
 - Swift Version: 3.0.2

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.2.1
 - Swift Package Manager 3.0.2 (swiftpm-11750)

**Comment by wongzigii** [comment]
Relate to https://github.com/SwiftyJSON/SwiftyJSON/issues/839

**Comment by Sukhrob** [comment]
This didn't work

    pod 'SwiftyJSON', '~> 3.1.1'

**Comment by wongzigii** [comment]
pod 'SwiftyJSON-3.1.1'

**Comment by Sukhrob** [comment]
![swiftyjson](https://cloud.githubusercontent.com/assets/1179760/26794563/8b79f0f0-4a3b-11e7-85a4-3c4b74e46372.png)

**Comment by wongzigii** [comment]
@Sukhrob You need to update your local pod spec.

**Comment by Sukhrob** [comment]
Fixed by updating pods. Thanks
