### ISSUE TITLE
"yes". boolValue -> false

### ISSUE THREAD

**Issue by SongHuaixu** [SwiftyJSON/SwiftyJSON#863]
### What did you do?

When I was using "yes".boolValue , I returned false,suggesting that the array be added "yes""

[ Suggesting code](https://github.com/SwiftyJSON/SwiftyJSON/blob/1d64b89d9aba1e82bd74a6393cfc3061250a8a80/Source/SwiftyJSON.swift#L822-L825)

**Comment by wongzigii** [comment]
Addressed in #887
