### ISSUE TITLE
the NSNumber extension isBool conflict when import Alamofire

### ISSUE THREAD

**Issue by hanzhuzi** [SwiftyJSON/SwiftyJSON#864]
extension NSNumber {
   var isBool: Bool {
        let objCType = String(cString: self.objCType)
        if (self.compare(trueNumber) == .orderedSame && objCType == trueObjCType) || (self.compare(falseNumber) == .orderedSame && objCType == falseObjCType) {
            return true
        } else {
            return false
        }
    }
}

this isBool value Needed to add fileprivate when I import Alamofire source files compliling I get a extension error. invalid redeclaration of 'isBool' value. so I add fileprivate compelling pass.

modify
extension NSNumber {
    fileprivate var isBool: Bool {
        let objCType = String(cString: self.objCType)
        if (self.compare(trueNumber) == .orderedSame && objCType == trueObjCType) || (self.compare(falseNumber) == .orderedSame && objCType == falseObjCType) {
            return true
        } else {
            return false
        }
    }
}

**Comment by wongzigii** [comment]
Fixed in #848
