### ISSUE TITLE
Removing the objects from JSON array is not working as desire when there is only one object in array. No way to remove all elements from array.

### ISSUE THREAD

**Issue by dipesh282** [SwiftyJSON/SwiftyJSON#870]
Hi,
I found one issue while removing the object from the array which has only one value. I tried by using following sample code. But it never removes the object from the list.

var arrJson = JSON(["Test"])
      arrJson.arrayObject?.remove(at: 0)
      print(arrJson)

Even I tired to remove all objects from the array but it was not working as well.
arrJson.arrayObject?.removeAll()

List the software versions you're using:

 - SwiftyJSON: 3.1.4
 - Xcode Version: 8.3.1
 - Swift Version: 3.1

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.2.1

**Comment by wongzigii** [comment]
Please check out the testcase of #875
