### ISSUE TITLE
Add migration guide for 4.0.0

### ISSUE THREAD

**Issue by wongzigii** [SwiftyJSON/SwiftyJSON#888]

**Comment by TheBogueRat** [comment]
The Conversion is handled by Xcode during the migration.  Update your pods or grab the latest master branch.  I selected only the swiftyJSON target for conversion and it required no changes.

**Comment by webmaster128** [comment]
Is this about Swift 4 or SwiftyJSON 4?

**Comment by masiama** [comment]
@webmaster128, SwiftyJSON 4

**Comment by webmaster128** [comment]
Okay then the Swift4 label is misleading ;)

**Comment by masiama** [comment]
@webmaster128, Sorry, I am not sure, but I think version 4.0.0 is update for SwiftyJSON  written in Swift 4

**Comment by webmaster128** [comment]
There is no mentioning of Swift 4 support in the SwiftyJSON 4 [release notes](https://github.com/SwiftyJSON/SwiftyJSON/releases) and people are [asking for Swift 4 support](https://github.com/SwiftyJSON/SwiftyJSON/issues/914), so I think Swift 4 or SwiftyJSON 4 are not coupled.

**Comment by masiama** [comment]
@webmaster128, so yeah, then Swift 4 label is misleading
