### ISSUE TITLE
Continue with Swift 4, please?

### ISSUE THREAD

**Issue by cityinthepark** [SwiftyJSON/SwiftyJSON#894]
Hi there,

Will SwiftyJSON continue to support Swift 4?

JSONDecoder is good, only if the data is formatted well. But in my case, the keys themselves are variable, worked as ID for the sub node. It's quite headache to use JSONDecoder.

I'm using SwiftyJSON in my app with Swift 3, worked like a charm. Please continue to support Swift 4. But right now I can't use it in my Xcode 9 beta.

Can any one tell me the plan for this framework? If not continuing, will have to find another solution.

Thanks a lot!!

**Comment by wongzigii** [comment]
SwiftyJSON will continue with Swift 4.
