### ISSUE TITLE
Please add support for Swift 4.* and iOS 11

### ISSUE THREAD

**Issue by fahad-larasoft** [SwiftyJSON/SwiftyJSON#895]
I am using XCode version 9.0

Please find error in attached screenshot:
<img width="280" alt="screen shot 2017-09-25 at 7 28 00 pm copy" src="https://user-images.githubusercontent.com/7126820/30813993-595e1bec-a228-11e7-9750-7a1e6703283d.png">
<img width="1166" alt="screen shot 2017-09-25 at 7 22 19 pm" src="https://user-images.githubusercontent.com/7126820/30814116-be47760c-a228-11e7-9333-d13218a06895.png">

**Comment by mludowise** [comment]
Version [4.0.0-alpha.1](https://github.com/SwiftyJSON/SwiftyJSON/releases/tag/4.0.0-alpha.1) is out as a prerelease which supports Swift 4. If you're using Cocoapods, you can specify '~> 4.0.0-alpha' as the version in your Podfile.

I am interested to know when version 4 will be officially released, now that XCode 9 is official.

**Comment by cptobvious** [comment]
To add to this, with carthage 4.0.0-alpha.1 can be used by putting `github "SwiftyJSON/SwiftyJSON" ~> 4.0.0` into the Cartfile.

**Comment by i-asm** [comment]
Is there is any update on the swift 4.0 support

**Comment by keason** [comment]
pod 'SwiftyJSON', '~> 4.0.0-alpha'  is not working, need I update Cocoapods?

**Comment by wongzigii** [comment]
@keason If you run `pod search SwiftyJSON` locally and the resut of seach is missing something likes:

    -> SwiftyJSON (4.0.0-alpha.1)
    SwiftyJSON makes it easy to deal with JSON data in Swift
    pod 'SwiftyJSON', '~> 4.0.0-alpha.1'
    .......

You will need to run `pod repo update` to update the latest pod spec

**Comment by keason** [comment]
THANKS MUCH!!!!!
I get following :
Installing SwiftyJSON 4.0.0-alpha.1 (was 3.1.4)
BUT Xcode Log:
The following binaries use incompatible versions of Swift:
/Users/XXXX/Library/Developer/Xcode/DerivedData/XXXXX-bvrohlgxnwocydctlpjdtuliesbw/Build/Products/Debug-iphoneos/XXXXXX.app/XXXXX
/Users/XXXX/Library/Developer/Xcode/DerivedData/XXXXX-byzhxnqdqrbakvcmectefzrwollw/Build/Products/Debug-iphonesimulator/SwiftyJSON/SwiftyJSON.framework/SwiftyJSON

**Comment by keason** [comment]
THANKS MUCH!!!!!

I get following :
Installing SwiftyJSON 4.0.0-alpha.1 (was 3.1.4)
BUT Xcode Log:
The following binaries use incompatible versions of Swift:
/Users/XXXX/Library/Developer/Xcode/DerivedData/XXXXX-bvrohlgxnwocydctlpjdtuliesbw/Build/Products/Debug-iphoneos/XXXXXX.app/XXXXX
/Users/XXXX/Library/Developer/Xcode/DerivedData/XXXXX-byzhxnqdqrbakvcmectefzrwollw/Build/Products/Debug-iphonesimulator/SwiftyJSON/SwiftyJSON.framework/SwiftyJSON


how can I fix it ! Thanks for your helping.


Best Regards,
Even Wong
Tel  : (852) 2408 0938 
Mobile: 6184 4207
web-site : tree-apps.com <http://www.tree-apps.com/>
E-Mail : even <mailto:even@tree-apps.com>@tree-apps.com <mailto:even@tree-apps.com>
Our Science Park Link Here <http://www.hkstp.org/zh-HK/Company-Directory/Company-Details.aspx?itemid=42495#.VK-X3Fpz7TU>tree Apps Limited
HK office: Flat C,6/F., First Asia Tower, 8 Fui Yiu Kok, Tsuen Wan,NT., Hong Kong
Development Office: Unit 308-313, 3/F Enterprise Place No. 5 Science Park West Avenue, H.K.

**Comment by wongzigii** [comment]
@keason I've found a similar issue here, not sure if this helps. 
https://stackoverflow.com/questions/38793192/xcode-8-beta-4-build-fails-with-the-following-binaries-use-incompatible-versio
I would recommend you to open another new issue to address this.

**Comment by keason** [comment]
Thanks Much!!

Best Regards,
Even Wong
Tel  : (852) 2408 0938 
Mobile: 6184 4207
web-site : tree-apps.com <http://www.tree-apps.com/>
E-Mail : even <mailto:even@tree-apps.com>@tree-apps.com <mailto:even@tree-apps.com>
Our Science Park Link Here <http://www.hkstp.org/zh-HK/Company-Directory/Company-Details.aspx?itemid=42495#.VK-X3Fpz7TU>tree Apps Limited
HK office: Flat C,6/F., First Asia Tower, 8 Fui Yiu Kok, Tsuen Wan,NT., Hong Kong
Development Office: Unit 308-313, 3/F Enterprise Place No. 5 Science Park West Avenue, H.K.

**Comment by wongzigii** [comment]
4.0.0 is out! 🎉

**Comment by esusslin** [comment]
is a SwiftyJSON.framework file available for 4.0.0?  My mind is blown trying to find it on the release page & I need to link the binary itself in my build phases - please help!
