### ISSUE TITLE
rawString() always returns nil

### ISSUE THREAD

**Issue by bb-git** [SwiftyJSON/SwiftyJSON#904]
I have an array of dictionaries, that I want to send to my server as JSON. But `.rawString() `always returns nil. What am I doing wrong?

This is the array logged from the console.
`[["food_id": 65, "name": "Weizenbrötchen (Stück), 870g", "protein": 72.5, "fat": 15.95000076293945, "key": "food1508681103516", "kcal": 2363, "date": 2017-10-22 00:00:00 +0000, "carbs": 482.8499755859375, "meal": "breakfast", "timestamp": 1508681103], ["food_id": 65, "name": "Weizenbrötchen (Stück), 870g", "protein": 72.5, "fat": 15.95000076293945, "key": "food1508681347250", "kcal": 2363, "date": 2017-10-23 00:00:00 +0000, "carbs": 482.8499755859375, "meal": "breakfast", "timestamp": 1508681347]]`

When I check the variable in the "Variables view", I can see, that the rawArray holds the right number of fields after calling `JSON(myArray)`.

Thanks

**Comment by wongzigii** [comment]
Hello @bb-git

````swift
let array = [
    ["food_id": 65, "name": "Weizenbrötchen (Stück), 870g", "protein": 72.5, "fat": 15.95000076293945, "key": "food1508681103516", "kcal": 2363, "date": "2017-10-22 00:00:00 +0000", "carbs": 482.8499755859375, "meal": "breakfast", "timestamp": 1508681103],
    ["food_id": 65, "name": "Weizenbrötchen (Stück), 870g", "protein": 72.5, "fat": 15.95000076293945, "key": "food1508681347250", "kcal": 2363, "date": "2017-10-23 00:00:00 +0000", "carbs": 482.8499755859375, "meal": "breakfast", "timestamp": 1508681347]
]
let js = JSON(array)
print(js.rawString())
````

This will return the rawString of JSON. I am not sure what you've done wrong. 😕 
Let me know if you need more help. Closing.
