### ISSUE TITLE
Availability of version 4

### ISSUE THREAD

**Issue by Jeyhey** [SwiftyJSON/SwiftyJSON#906]
I'm waiting for the update to version 4 to move to Xcode 9. Unfortunately SwiftyJSON 4 is still at the alpha stage. What is the timeline for version 4 ? Are there any issues with the alpha version that prevent releasing the update?

**Comment by Shah0786** [comment]
Any update on this?

**Comment by justdan0227** [comment]
update?

**Comment by wongzigii** [comment]
Sorry for the late response. 4.0.0 is out!

**Comment by justdan0227** [comment]
so does pod 'SwiftyJSON' pull the latest?

**Comment by wongzigii** [comment]
@justdan0227 

````
pod 'SwiftyJSON', '<~ 4.0.0'
````
