### ISSUE TITLE
Swift 4 - Support 

### ISSUE THREAD

**Issue by baltameme** [SwiftyJSON/SwiftyJSON#913]
Dear;

I want to enquire of SwiftyJSON 3.1.4 supports Swift 4.

### Environment

List the software versions you're using:

 - SwiftyJSON: *3.1.4*
 - Xcode Version: *9.1*
 - Swift Version: *4*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.3.1*

**Comment by wongzigii** [comment]
@baltameme 

The latest SwiftyJSON 4.0.0 is Swift 4.0 compatible.
