### ISSUE TITLE
Update to Swift 4

### ISSUE THREAD

**Issue by marchy** [SwiftyJSON/SwiftyJSON#914]
Any plans for updating to Swift 4?

We are blocked on a shared library which needs to compile in Swift 4, but which due to the lack of per-pod Swift support for Cocoapods (https://www.cerebralgardens.com/blog/entry/2017/10/04/mix-and-match-swift-3-swift-4-libraries-with-cocoapods) cannot compile due to SwiftyJSON still being compiled against Swift 3.

Would be wonderful to unblock this at first chance

**Comment by wongzigii** [comment]
SwiftyJSON 4.0.0 is Swift 4 compatiable.
