### ISSUE TITLE
Issue with using old code with new Swifty

### ISSUE THREAD

**Issue by nemanjaNisic** [SwiftyJSON/SwiftyJSON#917]
Hi guys,

I've been given an app to update to Swift 4, and I've never used swift before so this is kinda new, but I only got one error remaining and didn't find any solution online. Here is the code example

let resultStep1 = NSData(data: data!) as Data!
let readableResultStep1 = JSON(data: data!, options: .mutableContainers, error: nil)

The second line returns "Type of expression is ambiguous without more context"

I would appreciate any input, thanks!

**Comment by wongzigii** [comment]
Hey @nemanjaNisic 

What's the type of `data` in your case?

    let json1 = try? JSON(data: jsonData!)  // jsonData is type of Data or NSData
