### ISSUE TITLE
UnSpecified Swift Language Version installed by Cocoapods

### ISSUE THREAD

**Issue by ZZinKin** [SwiftyJSON/SwiftyJSON#920]
### What did you do?

Hello, I'm using this repo by cocoapods. Very time I type `pod install`, build error because the swift version is unspecified. It's pretty annoying to set the swift version always.

### What did you expect to happen?

Please specify swift version at Podspec file

### What actually happened instead?
UnSpecified Swift Language Version.

### Environment

List the software versions you're using:

 - SwiftyJSON (4.0.0)
 - Xcode Version: 9.2
 - Swift Version: 4.0
- Main project includes ObjC files

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.3.1 

### Project that demonstrates the issue

https://github.com/ZZinKin/SwiftyProblem

**Comment by wongzigii** [comment]
https://stackoverflow.com/questions/46338588/xcode-9-swift-language-version-swift-version

**Comment by bigbangvn** [comment]
I still get this issue with Cocoapod 1.5.0, need to set swift version everytime 'pod install'
