### ISSUE TITLE
Wrong type inference? 

### ISSUE THREAD

**Issue by Behinder** [SwiftyJSON/SwiftyJSON#926]
Ok, I am not sure if this is SwiftyJSON, Alamofire or Swifts fault but I got very annoyed yesterday.

When I try parse json strange things happened.
stacje[index]["stationName"].type got me "string" which is ok, then
let a = stacje[index]["stationName"]
print a.type get me JSON 👎  what the hell.
I wouldn't notice that if Xcode didn't provide me errors about adding to [String].
So IMO something is very wrong here, and I had to come back to parsing JSON in obj-c and bridge.

![zrzut ekranu 2018-01-11 o 19 02 40](https://user-images.githubusercontent.com/591766/34852444-f9a79a78-f72e-11e7-991b-156451f3608f.png)

**Comment by wongzigii** [comment]
let a = stacje[index]["stationName"]
you can then get string by `a`.string or `a`.stringValue

**Comment by Behinder** [comment]
Yes, I could. But this defy the whole point of using this library.
The inferred type should be STRING. It's kinda ridiculous geting stringValue from something that IS string.
