### ISSUE TITLE
Module compiled with Swift 4.0 cannot be imported in Swift 4.0.3

### ISSUE THREAD

**Issue by vivek4292** [SwiftyJSON/SwiftyJSON#932]
### What did you do?

I added SwiftyJSON with Carthage, add framework to the project embedded binary and then build.

### What did you expect to happen?

It should be compiled with the latest version of Xcode

### What actually happened instead?

It showing module compilation error.

### Environment

List the software versions you're using:

 - SwiftyJSON: Latest 
 - Xcode Version: 9.2
 - Swift Version: 4.0.3

Please also mention which package manager you used and its version. Delete the
other package managers on this list:

 - Cocoapods: 1.3.1 (But I'm not using pod)
 - Carthage: 0.27.0
 - Swift Package Manager: Swift 4.0.0-dev (swiftpm-13126)
![2018-01-21](https://user-images.githubusercontent.com/34335017/35206809-3da95d40-ff65-11e7-9cff-b488ebdb2da8.png)

**Comment by wongzigii** [comment]
carthage update --platform iOS --no-use-binaries
