### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by black-lotus** [SwiftyJSON/SwiftyJSON#935]
### What did you do?

parse raw string into JSON

### What did you expect to happen?

should be no error, and i can access parameter even it's empty

### What actually happened instead?

i got an error, that make my app force closed

### Environment

List the software versions you're using:

 - SwiftyJSON: 4.0.0
 - Xcode Version: 9.2 (9C40b)
 - Swift Version: 3.2

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.3.1
 - Carthage: none
 - Swift Package Manager: none

### Project that demonstrates the issue

<img width="868" alt="screen shot 2018-01-30 at 09 19 17" src="https://user-images.githubusercontent.com/3261560/35545009-a4dfecd2-059f-11e8-8edb-c92c92079fc8.png">

<img width="994" alt="screen shot 2018-01-30 at 09 17 12" src="https://user-images.githubusercontent.com/3261560/35545028-b95c3bfc-059f-11e8-8577-45cc6f09e62d.png">

Please help how to resolve this error
Thank you

**Comment by wongzigii** [comment]
@black-lotus Sorry for my late response. Could you send me an example project which can reproduce this issue?

**Comment by black-lotus** [comment]
hello,

i have already fix the issue
the issue not come from SwiftyJSON, but it because i change dictionary data without method that Apple provide

I used to this style
some_dictionary["key"] = some_new_value

I fix using apple provide method
some_dictionary.updateValue(some_new_value, forKey: "key")

Thank you.
💯
