### ISSUE TITLE
.float doesn't work

### ISSUE THREAD

**Issue by spooler** [SwiftyJSON/SwiftyJSON#938]
### What did you do?
```
let json = JSON(parseJSON: "{ \"foo\": \"8.5\" }")
print(json["foo"].floatValue)
print(json["foo"].float)
```
### What did you expect to happen?
_output:_
```
8.5
Optional(8.5)
```
### What actually happened instead?
_output:_
```
8.5
nil
```
### Environment
 - SwiftyJSON: 4.0.0
 - Xcode Version: 9.2 (9C40b)
 - Swift Version: 4.0
 - Cocoapods: 1.3.1

**Comment by wongzigii** [comment]
@spooler This is an expected behavior.

    public var float: Float? {
        get {
            return self.number?.floatValue
        }
        set {
            if let newValue = newValue {
                self.object = NSNumber(value: newValue)
            } else {
                self.object = NSNull()
            }
        }
    }

`json.float` will try to get the number of json since the value of key `foo` is a string `"8.5"`
