### ISSUE TITLE
compatible with swift 4.1?

### ISSUE THREAD

**Issue by anshuvij** [SwiftyJSON/SwiftyJSON#949]
is the current swiftyjson compatible with swift 4.1?

**Comment by JackTudor96** [comment]
I'm currently using 4.1 and I'm getting an error.

https://github.com/SwiftyJSON/SwiftyJSON/issues/934

It seems to removes support for _incremental protocol

**Comment by ladislas** [comment]
same here

**Comment by JackTudor96** [comment]
I worked out that one of the dependencies I was using, had an older version of SwiftyJSON. I've updated it and this is solved for me

**Comment by wongzigii** [comment]
The latest version is compatible with Swift 4.1.

**Comment by wongzigii** [comment]
I am going to close this issue. If you have any questions, please open another issue. Thanks.
