### ISSUE TITLE
Argument labels '(jsonDictionary:)' do not match any available overloads

### ISSUE THREAD

**Issue by antsangrigoli** [SwiftyJSON/SwiftyJSON#950]
See attached screeenshot.

List the software versions you're using:

 - SwiftyJSON: *?.?.?*
 - Xcode Version: Version 9.3 (9E145)
 - Swift Version: Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.4.0.beta.2 (Use `pod --version` in Terminal)
 - Carthage: *?.?* (Use `carthage version` in Terminal)
 - Apple Swift Package Manager - Swift 4.1.0 (swiftpm-14050)

![screen shot 2018-04-10 at 9 50 52 am](https://user-images.githubusercontent.com/15269174/38561003-e9103a38-3ca4-11e8-8cfb-85e516b570aa.png)

**Comment by wongzigii** [comment]
@antsangrigoli 

`let jsonObject = JSON(jsonRequest)`would be fine.
