### ISSUE TITLE
Incompatible Swift Version  4.1 when built in 4.1.2. Help

### ISSUE THREAD

**Issue by mdtaber** [SwiftyJSON/SwiftyJSON#969]
Hi. I dont have any coding capabilities at all. I am trying to implement Watson Assistant for IOS with Swift. For that, I have to install watson sdk and i get the following error message:

Skipped installing swift-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.1 (swiftlang-902.0.48 clang-902.0.37.1) and the local version is 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)."
A shell task (/usr/bin/xcrun xcodebuild -project /Users/mdtaber/Downloads/Iris-Swift/Carthage/Checkouts/Starscream/Starscream.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

How do I fix this?

List the software versions you're using:
I am on Swift version 4.1.2
 

Thank you for your help!

**Comment by wongzigii** [comment]
> "Incompatible Swift version - framework was built with 4.1 (swiftlang-902.0.48 clang-902.0.37.1) and the local version is 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)."
A shell task (/usr/bin/xcrun xcodebuild -project /Users/mdtaber/Downloads/Iris-Swift/Carthage/Checkouts/Starscream/Starscream.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

Seems like you are using Carthage to build Starscream framework. 

You can use `carthage update --no-use-binaries` to re-build the pre-build framework with the Xcode you've selected. For more info for the `--no-use-binaries` flag, see [here](https://stackoverflow.com/questions/41442601/whats-the-purpose-of-no-use-binaries-in-carthage)
