### ISSUE TITLE
'JSON' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by Viranchee** [SwiftyJSON/SwiftyJSON#981]
### What did you do?

Copy paste Sources/SwiftyJSON.swift to my Playground Sources

### What did you expect to happen?

Successful compilation

### What actually happened instead?

all 22 'extension JSON' giving 'JSON' is ambiguous for type lookup in this context ERROR
### Environment

List the software versions you're using:

 - SwiftyJSON: latest GitHub code
 - Xcode Version: 9.4.1
 - Swift Version: Preferences; Components > Toolchains shows only all iOS watchOS and tvOS versions, not swift versions

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: nil
 - Carthage: nil
 - Swift Package Manager nil

**Comment by wongzigii** [comment]
Hey @Viranchee I am afraid you could not just copy the code into playground.
Instead, you should import the 3rd framework into playground.
Please check out the Example in the workspace.
