### ISSUE TITLE
Error ' Umbrella header 'SwiftyJSON-umbrella.h' not found ' in xcode 10.0

### ISSUE THREAD

**Issue by huFly** [SwiftyJSON/SwiftyJSON#984]
### What did you do?

 I just update xcode to 10.0.

### What did you expect to happen?

I think my project will prefrom well.
### What actually happened instead?

An error  of     'Umbrella header 'SwiftyJSON-umbrella.h' not found'   happened;

### Environment
 - SwiftyJSON: *4.1.0*
 - Xcode Version: *10.0* 
 - Swift Version: *4.1* 
 - Cocoapods: *1.5.3* 
I also attempt to use Cocoapods 1.6.0.beta.1, but it still doesn't work.

![wx20180919-153359](https://user-images.githubusercontent.com/8486300/45737875-88ced880-bc21-11e8-8fa3-3317a5f8792d.png)

**Comment by wongzigii** [comment]
https://stackoverflow.com/questions/30355133/swift-framework-umbrella-header-h-not-found

This may helps.

**Comment by huFly** [comment]
the .h file is in right place. And the project has no error in xcode 9.4.   I have sloved it by create a new project using xcode 10.

**Comment by sssuourabh** [comment]
Running the test app on Xcode 10 and getting two errors as follows:
Use of undeclared type JSON in swiftyJSON
and Umbrella header 'SwiftyJSON-umbrella.h' not found
Please provide a solution for this
