### ISSUE TITLE
 Swift 4.2 and Xcode 10

### ISSUE THREAD

**Issue by shoaibnomani** [SwiftyJSON/SwiftyJSON#988]
Can you please update this library for swift 4.2 and Xcode 10?

**Comment by gabber3000** [comment]
same necessity

**Comment by kscheff** [comment]
Whats the specific issue you experience in this configuration? In my project it compiles fine and appears to be running.

**Comment by bukira** [comment]
the watchOS framework need to be a min or 3+ to upload to App Store

**Comment by ermalkaleci** [comment]
@kscheff watchOS min version 3.0

**Comment by kscheff** [comment]
OK, in my project I am using iOS with Swift 4.2 and Xcode 10.0
Thus I am using the `--platform iOS` build option.

**Comment by bukira** [comment]
That works fine, its the watchFramework that doesn't build

**Comment by wongzigii** [comment]
Alright, I will update the min wathOS requirement. :) Thanks for the feedback!

**Comment by ermalkaleci** [comment]
@wongzigii it builds fine but apple will reject your binary if min version is not set 3.+

**Comment by ermalkaleci** [comment]
WATCHOS_DEPLOYMENT_TARGET = 3.0

**Comment by wongzigii** [comment]
🎉  Congrats

 🚀  SwiftyJSON (4.2.0) successfully published
 📅  September 25th, 20:08
 🌎  https://cocoapods.org/pods/SwiftyJSON
 👍  Tell your friends!

**Comment by shoaibnomani** [comment]
Thank you for the quick response.
